let bowData = [
    {
        name: "Kamura Iron Bow I",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Iron Bow II",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "70",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Iron Bow III",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Iron Bow IV",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Iron Bow V",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Bow",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Weaver of Flame I",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating/Exhaust Coating",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "25",
        affinity: "20",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Silkbind Boost",
    },
    {
        name: "Weaver of Flame II",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating/Exhaust Coating",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "29",
        affinity: "25",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Fire Boost II/Silkbind Boost",
    },
    {
        name: "Araknatorch",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating/Exhaust Coating",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "33",
        affinity: "30",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Fire Boost II/Silkbind Boost",
    },
    {
        name: "Blessed Rain I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Exhaust Coating",
        damage: "120",
        elementType: "Water",
        elementalDamage: "11",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
    },
    {
        name: "Blessed Rain II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Exhaust Coating",
        damage: "190",
        elementType: "Water",
        elementalDamage: "13",
        affinity: "10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
    },
    {
        name: "Dawn Ray Bow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "5",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Lasting Arc Shot/Silkbind Boost",
    },
    {
        name: "Dawn Ray Bow II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Lasting Arc Shot/Silkbind Boost",
    },
    {
        name: "Summit's Grand Glow",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost /Lasting Arc Shot/Silkbind Boost",
    },
    {
        name: "Hidden Bow I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Poison Coating/Para Coating",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Lasting Arc Shot",
    },
    {
        name: "Hidden Bow II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Poison Coating/Para Coating",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "35",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost I/Lasting Arc Shot",
    },
    {
        name: "Night Flight",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Poison Coating/Para Coating",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Lasting Arc Shot",
    },
    {
        name: "Kadachi Strikebow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating/Para Coating",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "16",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Thunder Boost II",
    },
    {
        name: "Kadachi Strikebow II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating/Para Coating",
        damage: "150",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "15",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Thunder Boost II",
    },
    {
        name: "Kadachi Strikebow III",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating/Para Coating",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "21",
        affinity: "15",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Thunder Boost II",
    },
    {
        name: "Flying Kadachi Striker",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating/Para Coating",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "23",
        affinity: "15",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Thunder Boost III",
    },
    {
        name: "Ice Crest I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Sleep Coating/Exhaust Coating",
        damage: "100",
        elementType: "Ice",
        elementalDamage: "14",
        affinity: "20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Ice Crest II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Sleep Coating/Exhaust Coating",
        damage: "120",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "25",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Ice Crest III",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Sleep Coating/Exhaust Coating",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "17",
        affinity: "25",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Edelweiss",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Sleep Coating/Exhaust Coating",
        damage: "200",
        elementType: "Ice",
        elementalDamage: "19",
        affinity: "30",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Wroggi Revolver I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Lasting Arc Shot/Buddy Rally",
    },
    {
        name: "Wroggi Revolver II",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Lasting Arc Shot/Buddy Rally",
    },
    {
        name: "Hoodwinker's Revolver",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Lasting Arc Shot/Buddy Rally",
    },
    {
        name: "Arzuros Bow I",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "15",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Defense Boost I/Small Monster Exploit",
    },
    {
        name: "Arzuros Bow II",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost I/Small Monster Exploit",
    },
    {
        name: "Arzuros' Honeypot",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "15",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Lasting Arc Shot",
    },
    {
        name: "Iron Bow I",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Iron Bow II",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Steel Bow",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Hunter's Stoutbow I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Hunter's Stoutbow II",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Hunter's Prodbow",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Yekla Arc I",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "5",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Master Rider",
    },
    {
        name: "Yekla Arc II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "8",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Master Rider",
    },
    {
        name: "Herald's Battlebow",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost III/Master Rider",
    },
    {
        name: "Crystalline Flower I",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "140",
        elementType: "Ice",
        elementalDamage: "40",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost I/Element Exploit",
    },
    {
        name: "Crystalline Flower II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "45",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Ice Boost I/Element Exploit",
    },
    {
        name: "Heaven's Glaze",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "50",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost II/Element Exploit",
    },
    {
        name: "Mud Shot I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "140",
        elementType: "Water",
        elementalDamage: "27",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Water Boost I/Element Exploit",
    },
    {
        name: "Mud Shot II",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "150",
        elementType: "Water",
        elementalDamage: "29",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost I/Element Exploit",
    },
    {
        name: "Hail of Mud",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "170",
        elementType: "Water",
        elementalDamage: "34",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost II/Element Exploit",
    },
    {
        name: "Queen Blaster I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Poison Coating/Para Coating",
        damage: "110",
        elementType: "Fire",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Fire Boost I/Small Monster Exploit",
    },
    {
        name: "Queen Blaster II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Poison Coating/Para Coating",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "15",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Fire Boost I/Small Monster Exploit",
    },
    {
        name: "Queen's Melody",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Poison Coating/Para Coating",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "16",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Fire Boost I/Small Monster Exploit",
    },
    {
        name: "Prominence Bow I",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "17",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Prominence Bow II",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "200",
        elementType: "Fire",
        elementalDamage: "21",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Dark Filament",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "21",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Kulu's Flight I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Para Coating/Sleep Coating/Blast Coating",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Sleep Coating Boost/Spiribird Doubled",
    },
    {
        name: "Kulu's Flight II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Para Coating/Sleep Coating/Blast Coating",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Sleep Coating Boost/Spiribird Doubled",
    },
    {
        name: "Kulu Piercer",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Para Coating/Sleep Coating/Blast Coating",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost II/Sleep Coating Boost/Spiribird Doubled",
    },
    {
        name: "Khezu Bow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Sleep Coating",
        damage: "90",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Khezu Bow II",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Sleep Coating",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "21",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Galvanized Core",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Sleep Coating",
        damage: "150",
        elementType: "Thunder",
        elementalDamage: "24",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Bone Gun I",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Blast Coating/Exhaust Coating",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Gun II",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Blast Coating/Exhaust Coating",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Hyper Bone Gun",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Blast Coating/Exhaust Coating",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Hunter's Bow I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Blast Coating/Exhaust Coating",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Poison Coating Boost",
    },
    {
        name: "Hunter's Bow II",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Blast Coating/Exhaust Coating",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Poison Coating Boost",
    },
    {
        name: "Master Hunter's Bow",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Blast Coating/Exhaust Coating",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Poison Coating Boost",
    },
    {
        name: "Tigrex Archer I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Tigrex Archer II",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tigrex Whisker",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "250",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Diablos Coilbender I",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Exhaust Coating",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Defense Boost I/Lasting Arc Shot",
    },
    {
        name: "Diablos Coilbender II",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "Close-range Coating/Exhaust Coating",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost I/Lasting Arc Shot",
    },
    {
        name: "Usurper's Rumble I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Exhaust Coating",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "14",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Rumble II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Exhaust Coating",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot's Earlybolt",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Exhaust Coating",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Pukei Bow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Para Coating/Blast Coating",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost I/Paralysis Coating Boost",
    },
    {
        name: "Pukei Bow II",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Para Coating/Blast Coating",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost I/Paralysis Coating Boost",
    },
    {
        name: "Venomtongue Strike",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Poison Coating/Para Coating/Blast Coating",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Paralysis Coating Boost",
    },
    {
        name: "Flammenbogen I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "5",
        affinity: "-20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flammenbongen II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "220",
        elementType: "Fire",
        elementalDamage: "7",
        affinity: "-20",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
    },
    {
        name: "Flaming Rage Bow",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "240",
        elementType: "Fire",
        elementalDamage: "9",
        affinity: "-20",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost III/Brutal Strike",
    },
    {
        name: "Spongia Bow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "90",
        elementType: "Water",
        elementalDamage: "20",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Spongia Bow II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "140",
        elementType: "Water",
        elementalDamage: "22",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Spongia Bow III",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "170",
        elementType: "Water",
        elementalDamage: "24",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Porifero Bow",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Exhaust Coating",
        damage: "200",
        elementType: "Water",
        elementalDamage: "26",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Baggi Bow I",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Poison Coating Boost/Buddy Rally",
    },
    {
        name: "Baggi Bow II",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost xII/Poison Coating Boost/Buddy Rally",
    },
    {
        name: "Hypnoshot",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Poison Coating Boost/Buddy Rally",
    },
    {
        name: "Arko Nulo I",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "5",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Arko Nulo II",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "5",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Arko Unu",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Arko Nulo Black I",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "19",
        affinity: "15",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost II/Dragon Boost I/Dragon Exploit",
    },
    {
        name: "Arko Nulo Black II",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "21",
        affinity: "15",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost II/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Arko Nulu Black",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "24",
        affinity: "20",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Arko Nulo Yellow I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "140",
        elementType: "Thunder",
        elementalDamage: "23",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Arko Nulo Yellow II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "27",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Arko Unu Yellow",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "29",
        affinity: "15",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Arko Nulo Red I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "90",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Arko Nulo Red II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "130",
        elementType: "Fire",
        elementalDamage: "26",
        affinity: "15",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Arko Unu Red",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "28",
        affinity: "20",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost II/Fireblight Exploit",
    },
    {
        name: "Arko Nulo White I",
        type: "Bow",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "5",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost I/Iceblight Exploit",
    },
    {
        name: "Arko Nulo White II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "140",
        elementType: "Ice",
        elementalDamage: "24",
        affinity: "5",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost I/Iceblight Exploit",
    },
    {
        name: "Arko Unu White",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Para Coating",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "26",
        affinity: "10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost II/Iceblight Exploit",
    },
    {
        name: "Sinister Bow I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Blast Coating/Exhaust Coating",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "14",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Bow II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Blast Coating/Exhaust Coating",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "16",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Soulpiercer",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Blast Coating/Exhaust Coating",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "19",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Kelbi Stingshot I",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Exhaust Coating",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Lasting Arch Shot/Paralysis Coating Boost",
    },
    {
        name: "Kelbi Stingshot II",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Exhaust Coating",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Lasting Arch Shot/Paralysis Coating Boost",
    },
    {
        name: "Kelbi Strongshot",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Exhaust Coating",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Lasting Arc Shot/Paralysis Coating Boost",
    },
    {
        name: "Beast Thunderbow I",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "9",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Master Rider",
    },
    {
        name: "Beast Thunderbow II",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "10",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Master Rider",
    },
    {
        name: "Azure Elder Bow I",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Exhaust Coating",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "10",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Bow II",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Exhaust Coating",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "13",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Bow I",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Para Coating/Sleep Coating/Blast Coating",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "30",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Icesteel Bow I",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "30",
        affinity: "10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Bow of Hope & Valor I",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating/Sleep Coating",
        damage: "180",
        elementType: "Blast",
        elementalDamage: "27",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Genie's Grimoire I",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Morsel Bowfish I",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Sleep Coating",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Master Rider/Anti-aquatic Species",
    },
    {
        name: "Morsel Bowfish II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Sleep Coating",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Master Rider/Anti-aquatic Species",
    },
    {
        name: "Ample Bowfish",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Sleep Coating",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Master Rider/Anti-Aquatic Species",
    },
    {
        name: "Felyne Bow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "2",
        phialOrShellingType: "Close-range Coating/Power Coating/Para Coating",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Brutal Strike/Buddy Rally",
    },
    {
        name: "Felyne Bow II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "9",
        phialOrShellingType: "Close-range Coating/Power Coating/Para Coating",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Brutal Strike/Buddy Rally",
    },
    {
        name: "Felyne Trickbow",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "18",
        phialOrShellingType: "Close-range Coating/Power Coating/Para Coating",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Brutal Strike/Buddy Rally",
    },
    {
        name: "Chaos Bow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Lasting Arc Shot/Spiribird Doubled",
    },
    {
        name: "Chaos Bow II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Lasting Arc Shot/Spiribird Doubled",
    },
    {
        name: "Chaotic Rapture",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost II/Lasting Arc Shot/Spiribird Doubled",
    },
    {
        name: "Ivory Bow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Defense Boost I/Spiribird Doubled",
    },
    {
        name: "Ivory Bow II",
        type: "Bow",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Defense Boost I/Spiribird Doubled",
    },
    {
        name: "Frozen Bow",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Sleep Coating/Blast Coating/Exhaust Coating",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Defense Boost I/Spiribird Doubled",
    },
    {
        name: "Arachnid Bow I",
        type: "Bow",
        rarity: "2",
        defenseIncrease: "25",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost I/Poison Coating Boost/Silkbind Boost",
    },
    {
        name: "Arachnid Bow II",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "25",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Poison Coating Boost/Silkbind Boost",
    },
    {
        name: "Arachnid Silversting",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "25",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating/Sleep Coating",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost III/Poison Coating Boost/Silkbind Boost",
    },
    {
        name: "Rampage Bow I",
        type: "Bow",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Bow II",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Bow III",
        type: "Bow",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Bow IV",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Bow V",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Abyssal Gale Bow",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Exhaust Coating",
        damage: "220",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Bow",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Para Coating/Sleep Coating/Blast Coating",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "35",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Beastking Thunderbow",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "220",
        elementType: "Thunder",
        elementalDamage: "11",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Thunder Boost II/Master Rider",
    },
    {
        name: "Bow of Light & Courage",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Sleep Coating",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "31",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Daora's Sagittarii",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "37",
        affinity: "15",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Demon's Guidance",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Poison Coating/Para Coating",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Rampage Bow S",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Reddnaught Dragon Arc",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "39",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Tyrant Bow",
        type: "Bow",
        rarity: "7",
        defenseIncrease: "15",
        phialOrShellingType: "Close-range Coating/Exhaust Coating",
        damage: "250",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Lasting Arc Shot",
    },
    {
        name: "Heaven's Manna",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType:
            "Close-range Coating/Power Coating/Para Coating/Exhaust Coating",
        damage: "210",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Water Boost II",
    },
    {
        name: "Redwing Bow I",
        type: "Bow",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Close-range Coating/Power Coating",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "36",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
];

export default bowData;