let chargeBladeData = [
    {
        name: "Kamura C. Blade I",
        type: "ChargeBlade",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura C. Blade II",
        type: "ChargeBlade",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura C. Blade III",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura C. Blade IV",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura C. Blade V",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja C. Blade",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Dear Lutemis I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Fire Boost I/Small Monster Exploit",
    },
    {
        name: "Dear Lutemis II",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "25",
        yellowSharpness: "15",
        greenSharpness: "25",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Fire Boost I/Small Monster Exploit",
    },
    {
        name: "Dear Lutemia",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "25",
        yellowSharpness: "10",
        greenSharpness: "30",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Fire Boost II/Small Monster Exploit",
    },
    {
        name: "Weissritter I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "17",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Weissritter II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "110",
        elementType: "Ice",
        elementalDamage: "19",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "18",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Weissritter III",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "130",
        elementType: "Ice",
        elementalDamage: "22",
        affinity: "25",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "18",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Paladire Charge Blade",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "26",
        affinity: "25",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Usurper's Lightning I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Lightning II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "17",
        greenSharpness: "20",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot's Thundergale",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Shovedown Blade I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "Impact Phial",
        damage: "100",
        elementType: "Water",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost I/Dulling Strike",
    },
    {
        name: "Shovedown Blade II",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "10",
        phialOrShellingType: "Impact Phial",
        damage: "170",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost II/Dulling Strike",
    },
    {
        name: "Spinning Takedown",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "Impact Phial",
        damage: "210",
        elementType: "Water",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "32",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost III/Dulling Strike",
    },
    {
        name: "Giga Grips I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "Impact Phial",
        damage: "100",
        elementType: "Poison",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "35",
        yellowSharpness: "9",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Poison Boost I/Dulling Strike",
    },
    {
        name: "Giga Grips II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "Impact Phial",
        damage: "140",
        elementType: "Poison",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "33",
        yellowSharpness: "9",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Poison Boost II/Dulling Strike",
    },
    {
        name: "Giga Grips III",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "Impact Phial",
        damage: "140",
        elementType: "Poison",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "33",
        yellowSharpness: "10",
        greenSharpness: "21",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Poison Boost II/Silkbind Boost",
    },
    {
        name: "Titan's Vise",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "20",
        phialOrShellingType: "Impact Phial",
        damage: "200",
        elementType: "Poison",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "33",
        yellowSharpness: "10",
        greenSharpness: "19",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Poison Boost III/Silkbind Boost",
    },
    {
        name: "Surprise Axe I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "9",
        affinity: "-20",
        redSharpness: "21",
        orangeSharpness: "7",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost I/Brutal Strike",
    },
    {
        name: "Surprise Axe II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "11",
        affinity: "-20",
        redSharpness: "21",
        orangeSharpness: "9",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost II/Brutal Strike",
    },
    {
        name: "Stunning Axe",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "230",
        elementType: "Ice",
        elementalDamage: "13",
        affinity: "-20",
        redSharpness: "21",
        orangeSharpness: "9",
        yellowSharpness: "23",
        greenSharpness: "10",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost III/Brutal Strike",
    },
    {
        name: "Hyperguard I",
        type: "ChargeBlade",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Hyperguard II",
        type: "ChargeBlade",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "13",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Regas Hyper",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "12",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Elite Blade I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "15",
        yellowSharpness: "8",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Elite Blade II",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "20",
        yellowSharpness: "12",
        greenSharpness: "12",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Kaiser Blade",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "20",
        yellowSharpness: "9",
        greenSharpness: "12",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Silkbind Boost",
    },
    {
        name: "K. Captain's Blade I",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "150",
        elementType: "Thunder",
        elementalDamage: "29",
        affinity: "15",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "13",
        greenSharpness: "12",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "K. Captain's Blade II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "33",
        affinity: "20",
        redSharpness: "23",
        orangeSharpness: "15",
        yellowSharpness: "11",
        greenSharpness: "13",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Die Walküre",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "37",
        affinity: "20",
        redSharpness: "23",
        orangeSharpness: "17",
        yellowSharpness: "15",
        greenSharpness: "14",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Biting Edge I",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "29",
        affinity: "25",
        redSharpness: "47",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "8",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Silkbind Boost",
    },
    {
        name: "Biting Edge II",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "31",
        affinity: "25",
        redSharpness: "47",
        orangeSharpness: "12",
        yellowSharpness: "12",
        greenSharpness: "8",
        blueSharpness: "8",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Fire Boost II/Silkbind Boost",
    },
    {
        name: "Araknablade",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "34",
        affinity: "30",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "10",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Fire Boost II/Silkbind Boost",
    },
    {
        name: "Tigrex Divide I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "16",
        orangeSharpness: "7",
        yellowSharpness: "24",
        greenSharpness: "24",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Tigrex Divide II",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "12",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tigrex Blade",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "12",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "31",
        blueSharpness: "12",
        whiteSharpness: "5",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Mizuniya Drill I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "110",
        elementType: "Water",
        elementalDamage: "21",
        affinity: "10",
        redSharpness: "27",
        orangeSharpness: "10",
        yellowSharpness: "8",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
    },
    {
        name: "Mizuniya Drill II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "170",
        elementType: "Water",
        elementalDamage: "24",
        affinity: "15",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "16",
        greenSharpness: "11",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Kadachi Slasher I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "30",
        orangeSharpness: "8",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Thunder Boost II",
    },
    {
        name: "Kadachi Slasher II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "140",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "15",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "12",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Thunder Boost II",
    },
    {
        name: "Kadachi Otenta",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "15",
        redSharpness: "28",
        orangeSharpness: "18",
        yellowSharpness: "7",
        greenSharpness: "7",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Thunder Boost III",
    },
    {
        name: "Wind Thief Sickle I",
        type: "ChargeBlade",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "70",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "9",
        yellowSharpness: "12",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Wind Thief Sickle II",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "15",
        orangeSharpness: "9",
        yellowSharpness: "9",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Gale Sickle",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "25",
        orangeSharpness: "11",
        yellowSharpness: "12",
        greenSharpness: "11",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Hidden Arsenal I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        redSharpness: "12",
        orangeSharpness: "15",
        yellowSharpness: "18",
        greenSharpness: "30",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Grinder I",
    },
    {
        name: "Hidden Arsenal II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "35",
        redSharpness: "16",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "26",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost I/Defense Grinder I",
    },
    {
        name: "Scream in the Night",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "16",
        orangeSharpness: "11",
        yellowSharpness: "26",
        greenSharpness: "21",
        blueSharpness: "21",
        whiteSharpness: "5",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Defense Grinder II",
    },
    {
        name: "Bone Sgrongarm I",
        type: "ChargeBlade",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Sgrongarm II",
        type: "ChargeBlade",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Hard Bone Strongarm",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Bone Blade I Charge Blade",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Bone Blade II",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Bonesilt Veil",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Jyura Silt I",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Water",
        elementalDamage: "10",
        affinity: "-10",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Affinity Boost I/Water Boost I/Brutal Strike",
    },
    {
        name: "Jyura Silt II",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Water",
        elementalDamage: "11",
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "25",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Affinity Boost I/Water Boost II/Brutal Strike",
    },
    {
        name: "Clutch of the Deep",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "230",
        elementType: "Water",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "30",
        orangeSharpness: "30",
        yellowSharpness: "8",
        greenSharpness: "8",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Affinity Boost II/Water Boost II/Brutal Strike",
    },
    {
        name: "Axelion Blade I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "120",
        elementType: "Fire",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Axelion Blade II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Bardichion Blade",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Bellowing Blow I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "90",
        elementType: "Sleep",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Bellowing Blow II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "130",
        elementType: "Sleep",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "12",
        yellowSharpness: "21",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Illusory Frilled Wail",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "Sleep",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "12",
        yellowSharpness: "35",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Poisonous Veil I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "110",
        elementType: "Poison",
        elementalDamage: "8",
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "7",
        yellowSharpness: "10",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Poison Boost I/Dulling Strike",
    },
    {
        name: "Poisonous Veil II",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "11",
        affinity: "-10",
        redSharpness: "35",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Poison Boost II/Dulling Strike",
    },
    {
        name: "Infected Veil",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "210",
        elementType: "Poison",
        elementalDamage: "14",
        affinity: "-10",
        redSharpness: "40",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Poison Boost II/Dulling Strike",
    },
    {
        name: "Dragon Veil I",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "35",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Dragon Boost I/Element Exploit",
    },
    {
        name: "Dragon Veil II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "24",
        affinity: "-10",
        redSharpness: "38",
        orangeSharpness: "11",
        yellowSharpness: "9",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dragon Boost I/Element Exploit",
    },
    {
        name: "Dragonsong",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "36",
        affinity: "-5",
        redSharpness: "40",
        orangeSharpness: "7",
        yellowSharpness: "10",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Dragon Boost II/Element Exploit",
    },
    {
        name: "Barroth Anchor I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "35",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Brutal Strike",
    },
    {
        name: "Barroth Anchor II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "37",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost II/Brutal Strike",
    },
    {
        name: "Rugged Anchor",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "37",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Brutal Strike",
    },
    {
        name: "Diablos Strongarm I",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "Impact Phial",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "10",
        orangeSharpness: "40",
        yellowSharpness: "8",
        greenSharpness: "25",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dulling Strike",
    },
    {
        name: "Diablos Strongarm II",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "Impact Phial",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "10",
        orangeSharpness: "40",
        yellowSharpness: "5",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Dulling Strike",
    },
    {
        name: "Rough Roller I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "100",
        elementType: "Paralysis",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost I/Defense Grinder I",
    },
    {
        name: "Rough Roller II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "170",
        elementType: "Paralysis",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Defense Grinder I",
    },
    {
        name: "Rotaxion",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "200",
        elementType: "Paralysis",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Defense Boost II/Defense Grinder I",
    },
    {
        name: "Sinister Slasher I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "17",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Slasher II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Shade Axe",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "5",
        greenSharpness: "19",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Undying Blade I",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "5",
        yellowSharpness: "24",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Undying Blade II",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "230",
        elementType: "Thunder",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Azure Elder Blade I",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "6",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "30",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Blade II",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "Dragon",
        elementalDamage: "9",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "12",
        greenSharpness: "12",
        blueSharpness: "26",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Sawtooth I",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "45",
        greenSharpness: "10",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora's Casca I",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "30",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Teostra's Striker I",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "Blast",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "32",
        orangeSharpness: "4",
        yellowSharpness: "15",
        greenSharpness: "17",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Arcane Draw I",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "16",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Ricebane I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "Impact Phial",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "27",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost I/Defense Grinder I",
    },
    {
        name: "Ricebane II",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "15",
        phialOrShellingType: "Impact Phial",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Defense Boost II/Defense Grinder II",
    },
    {
        name: "Pounder of Rice",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "Impact Phial",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "12",
        yellowSharpness: "12",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost III/Defense Grinder II",
    },
    {
        name: "Cuddly Cat I",
        type: "ChargeBlade",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "80",
        elementType: "Paralysis",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "25",
        yellowSharpness: "8",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost I/Paralysis Boost I",
    },
    {
        name: "Cuddly Cat II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "130",
        elementType: "Paralysis",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "25",
        yellowSharpness: "12",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Paralysis Boost I",
    },
    {
        name: "Felyne Fancy",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "140",
        elementType: "Paralysis",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "25",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Paralysis Boost I",
    },
    {
        name: "Mandible Blade I",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "120",
        elementType: "Dragon",
        elementalDamage: "14",
        affinity: "10",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Mandible Blade II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "130",
        elementType: "Dragon",
        elementalDamage: "17",
        affinity: "10",
        redSharpness: "6",
        orangeSharpness: "25",
        yellowSharpness: "6",
        greenSharpness: "16",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Maxilla Edge",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "22",
        affinity: "15",
        redSharpness: "6",
        orangeSharpness: "35",
        yellowSharpness: "6",
        greenSharpness: "20",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost III/Dragon Exploit",
    },
    {
        name: "Vaik Veil I",
        type: "ChargeBlade",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "100",
        elementType: "Water",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "20",
        yellowSharpness: "14",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost II/Dulling Strike",
    },
    {
        name: "Vaik Veil II",
        type: "ChargeBlade",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "140",
        elementType: "Water",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "21",
        yellowSharpness: "12",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Water Boost II/Dulling Strike",
    },
    {
        name: "Shieldraad",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "150",
        elementType: "Water",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "25",
        yellowSharpness: "15",
        greenSharpness: "12",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Water Boost III/Dulling Strike",
    },
    {
        name: "Rampage C. Blade I",
        type: "ChargeBlade",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "17",
        yellowSharpness: "21",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage C. Blade II",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage C. Blade III",
        type: "ChargeBlade",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "8",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage C. Blade IV",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "7",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage C. Blade V",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Redwing Edge I",
        type: "ChargeBlade",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Abyssal Gale Ward",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "3",
        orangeSharpness: "3",
        yellowSharpness: "18",
        greenSharpness: "15",
        blueSharpness: "20",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Ward",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "40",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Cera Strongarm",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "20",
        phialOrShellingType: "Impact Phial",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "10",
        orangeSharpness: "25",
        yellowSharpness: "2",
        greenSharpness: "20",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Defense Grinder II",
    },
    {
        name: "Daora's Thwartoise",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "36",
        affinity: "10",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "6",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Etherward",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "39",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Ikaji Immortal",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "240",
        elementType: "Thunder",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "14",
        yellowSharpness: "18",
        greenSharpness: "22",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Rampage C.Blade S",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "8",
        greenSharpness: "12",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Skaltecore",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Teostra's Nova",
        type: "ChargeBlade",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Impact Phial",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "43",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "4",
        greenSharpness: "15",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
    },
];

export default chargeBladeData;