let dualBladesData = [
    {
        name: "Kamura Glintblades I",
        type: "DualBlades",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Glintblades II",
        type: "DualBlades",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Glintblades III",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Glintblades IV",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Glintblades V",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Blades",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Mud Ripper I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Water",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Water Boost I/Element Exploit",
    },
    {
        name: "Mud Ripper II",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Water",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost I/Element Exploit",
    },
    {
        name: "Mud Twister",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Water",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost II/Element Exploit",
    },
    {
        name: "Usurper's Fulgur I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Fulgur II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot's Blitz",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Blizzarioths I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Blizzarioths II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "18",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "5",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Mountain Blizzarioths",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Desperado I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Poison",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Poison Boost I/Buddy Rally",
    },
    {
        name: "Desperado II",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Poison",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Poison Boost I/Buddy Rally",
    },
    {
        name: "The Kid",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Poison",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Poison Boost II/Buddy Rally",
    },
    {
        name: "Khezu Daggers I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Paralysis Boost I",
    },
    {
        name: "Khezu Daggers II",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "24",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Paralysis Boost I",
    },
    {
        name: "Khezu Skards",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Thunder",
        elementalDamage: "28",
        affinity: "10",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost IV/Thunder Boost II/Paralysis Boost II",
    },
    {
        name: "Matched Slicers I",
        type: "DualBlades",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Matched Slicers II",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Dual Daggers",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Hurricane I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Silk Boost",
    },
    {
        name: "Hurricane II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost III/Silk Boost",
    },
    {
        name: "Cyclone",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost III/Silk Boost",
    },
    {
        name: "Rex Slicers I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        redSharpness: "15",
        orangeSharpness: "5",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Rex Slicers II",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tigrex Claws",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "12",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "30",
        blueSharpness: "17",
        whiteSharpness: "6",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Morning Dawn I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Water",
        elementalDamage: "12",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Morning Dawn II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Schirmscorn I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Schirmscorn II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Daybreak Daggers",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "35",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost II/Fireblight Exploit",
    },
    {
        name: "Kulu's Peck I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Spiribird Doubled",
    },
    {
        name: "Kulu's Peck II",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Spiribird Doubled",
    },
    {
        name: "Kulu's Lasher",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "20",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Spiribird Doubled",
    },
    {
        name: "Gelid Mind I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Ice Boost I/Dulling Strike",
    },
    {
        name: "Gelid Mind II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Ice Boost II/Dulling Strike",
    },
    {
        name: "Gelid Soul",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Ice",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Ice Boost III/Dulling Strike",
    },
    {
        name: "Hidden Gemini I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Gemini II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "10",
        orangeSharpness: "5",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Night Wings",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "17",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "22",
        blueSharpness: "16",
        whiteSharpness: "10",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
    },
    {
        name: "Twin Chainsaws I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "8",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Twin Chainsaws II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Guillotines",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Dual Hatchets I",
        type: "DualBlades",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "5",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Thunder Boost I/Small Monster Exploit",
    },
    {
        name: "Dual Hatchets II",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost I/Small Monster Exploit",
    },
    {
        name: "Dual Cleavers",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Small Monster Exploit",
    },
    {
        name: "Cerulean Axes I",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "10",
        yellowSharpness: "35",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I/Dulling Strike",
    },
    {
        name: "Cerulean Axes II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Dulling Strike",
    },
    {
        name: "Ashigara Axes",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost II/Dulling Strike",
    },
    {
        name: "Flammenschild I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "10",
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flammenschild II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "15",
        affinity: "-15",
        redSharpness: "30",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
    },
    {
        name: "Gnashing Flammenschild",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "Fire",
        elementalDamage: "18",
        affinity: "-15",
        redSharpness: "30",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost II/Brutal Strike",
    },
    {
        name: "Bone Hatchets I",
        type: "DualBlades",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Hatchets II",
        type: "DualBlades",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Wild Hatchets",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Talon Carvers I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Talon Carvers II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Talon Twins",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Twin Flames I",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Twin Flames II",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "5",
        yellowSharpness: "30",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Wyvern Lovers",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Fire",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "11",
        yellowSharpness: "16",
        greenSharpness: "22",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Diablos Bashers I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dulling Strike",
    },
    {
        name: "Diablos Bashers II",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "12",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "35",
        orangeSharpness: "25",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Dulling Strike",
    },
    {
        name: "Diablos Mashers",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "16",
        phialOrShellingType: "None",
        damage: "250",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "30",
        orangeSharpness: "10",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Dulling Strike",
    },
    {
        name: "Jyura Duo I",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Water",
        elementalDamage: "8",
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "17",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Water Boost I/Brutal Strike",
    },
    {
        name: "Jyura Duo II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Water",
        elementalDamage: "10",
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Water Boost II/Brutal Strike",
    },
    {
        name: "Jyura Pulverizers",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Water",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "30",
        orangeSharpness: "25",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Water Boost II/Brutal Strike",
    },
    {
        name: "Kadachi Twinblades I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "12",
        affinity: "10",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Thunder Boost II",
    },
    {
        name: "Kadachi Twinblades II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Thunder Boost II",
    },
    {
        name: "Shockblades",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "6",
        greenSharpness: "12",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Thunder Boost III",
    },
    {
        name: "Blazeblades I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "70",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "-10",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Dulling Strike",
    },
    {
        name: "Blazeblades II",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Fire",
        elementalDamage: "23",
        affinity: "-10",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Dulling Strike",
    },
    {
        name: "Infernal Furies",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "30",
        affinity: "-10",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Dulling Strike",
    },
    {
        name: "Ludroth Pair I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Ludroth Pair II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Water",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost II/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Double Droth",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Frilled Claw I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Sleep",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Frilled Claw II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Sleep",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Illusory Frilled Claw",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Sleep",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "30",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Snow Slicers I",
        type: "DualBlades",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost I/Small Monster Exploit",
    },
    {
        name: "Snow Slicers II",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Ice",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Ice Boost II/Small Monster Exploit",
    },
    {
        name: "Snow Sisters",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost II/Dulling Strike",
    },
    {
        name: "Sinister Blades I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Blades II",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Famineblades",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Suzuka Takamaru I",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "16",
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Suzuka Takamaru II",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "5",
        yellowSharpness: "35",
        greenSharpness: "25",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Azure Elder Blades I",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "6",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Blades II",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "8",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "30",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Blades I",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "45",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Rookslayer Handaxes I",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "10",
        affinity: "-10",
        redSharpness: "12",
        orangeSharpness: "20",
        yellowSharpness: "12",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Brutal Strike",
    },
    {
        name: "Rookslayer Handaxes II",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "12",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Brutal Strike",
    },
    {
        name: "Bazelhawk Rookslayer",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Blast Boost III/Brutal Strike",
    },
    {
        name: "Icesteel Fang I",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Twin Nails I",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Blast",
        elementalDamage: "24",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost II/Teostra Soul",
    },
    {
        name: "Rogue Flames I",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "32",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Felyne Claws I",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Paralysis",
        elementalDamage: "5",
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Hellion Mode/Buddy Rally",
    },
    {
        name: "Felyne Claws II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Paralysis",
        elementalDamage: "8",
        affinity: "-10",
        redSharpness: "30",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Hellion Mode/Buddy Rally",
    },
    {
        name: "Raging Claws",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Paralysis",
        elementalDamage: "10",
        affinity: "-10",
        redSharpness: "30",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Hellion Mode/Buddy Rally",
    },
    {
        name: "Rainy Jelly I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Paralysis",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affiinity Boost I/Paralysis Boost I",
    },
    {
        name: "Rainy Jelly II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Paralysis",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affiinity Boost/Paralysis Boost I",
    },
    {
        name: "Rain of Gore",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Paralysis",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "30",
        yellowSharpness: "20",
        greenSharpness: "3",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affiinity Boost/Paralysis Boost I",
    },
    {
        name: "Qornu Waga I",
        type: "DualBlades",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Dragon",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Qornu Waga II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "40",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Ro Waga",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Dragon",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost III/Dragon Exploit",
    },
    {
        name: "Sworn Rapiers I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Water",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost II/Anti-Aerial Species",
    },
    {
        name: "Sworn Rapiers II",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost II/Anti-Aerial Species",
    },
    {
        name: "Holy Sabers",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Water Boost III/Anti-Aerial Species",
    },
    {
        name: "Altair I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Dragon",
        elementalDamage: "13",
        affinity: "10",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "5",
        greenSharpness: "5",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Master Rider/Dragon Exploit",
    },
    {
        name: "Altair II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "22",
        affinity: "12",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Master Rider/Dragon Exploit",
    },
    {
        name: "Fortis Gran",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "24",
        affinity: "15",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Master Rider/Dragon Exploit",
    },
    {
        name: "Stealth Dango I",
        type: "DualBlades",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Sleep",
        elementalDamage: "3",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dulling Strike/Spiribird Doubled",
    },
    {
        name: "Stealth Dango II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Sleep",
        elementalDamage: "5",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Dulling Strike/Spiribird Doubled",
    },
    {
        name: "Perfected Dango",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Sleep",
        elementalDamage: "8",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Dulling Strike/Spiribird Doubled",
    },
    {
        name: "Rampage Twinblades I",
        type: "DualBlades",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "17",
        orangeSharpness: "17",
        yellowSharpness: "21",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Twinblades II",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Twinblades III",
        type: "DualBlades",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "16",
        yellowSharpness: "18",
        greenSharpness: "9",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Twinblades IV",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "8",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Twinblades V",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Evening Dusk",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Water",
        elementalDamage: "18",
        affinity: "15",
        redSharpness: "10",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Water Boost II",
    },
    {
        name: "Redwing Blades I",
        type: "DualBlades",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Suzuka Otakemaru",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "-20",
        redSharpness: "18",
        orangeSharpness: "8",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Abyssal Gale Blades",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "3",
        orangeSharpness: "3",
        yellowSharpness: "18",
        greenSharpness: "15",
        blueSharpness: "20",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Blades",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "40",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora's Hook",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "16",
        greenSharpness: "6",
        blueSharpness: "5",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Fire and Ice",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Blast",
        elementalDamage: "36",
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Teostra Soul",
    },
    {
        name: "Dual Chameleos",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "10",
        yellowSharpness: "12",
        greenSharpness: "15",
        blueSharpness: "4",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Reddnaught Dragon Wing",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rampage Twinblades S",
        type: "DualBlades",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "8",
        greenSharpness: "12",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
];

export default dualBladesData;