
let seededGreatSwordData = [
    {
        name: "Kamura Cleaver I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Cleaver II",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Cleaver III",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Cleaver IV",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Cleaver V",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "25",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Cleaver",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "25",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "15",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Gossblade I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost I/Brutal Strike",
    },
    {
        name: "Gossblade II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Ice",
        elementalDamage: "17",
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost II/Brutal Strike",
    },
    {
        name: "Abominable Great Sword",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost III/Brutal Strike",
    },
    {
        name: "Hanayako Yohino I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Water",
        elementalDamage: "20",
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
    },
    {
        name: "Hanayako Yohino II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "25",
        affinity: "10",
        redSharpness: "30",
        orangeSharpness: "30",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Axeblade I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "1",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Dulling Strike/Defense Grinder I",
    },
    {
        name: "Axeblade II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Dulling Strike/Defense Grinder I",
    },
    {
        name: "Colossal Axeblade",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "30",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Defense Boost III/Dulling Strike/Defense Grinder I",
    },
    {
        name: "Carapace Sword I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "12",
        orangeSharpness: "15",
        yellowSharpness: "35",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Brutal Strike",
    },
    {
        name: "Carapace Sword II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "12",
        orangeSharpness: "15",
        yellowSharpness: "30",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost II/Brutal Strike",
    },
    {
        name: "Carapace Blade",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "55",
        greenSharpness: "15",
        blueSharpness: "1",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Brutal Strike",
    },
    {
        name: "Tiger Jawblade I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "20",
        orangeSharpness: "5",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "3",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Tiger Jawblade II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "12",
        orangeSharpness: "10",
        yellowSharpness: "35",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tigrex Great Sword",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "12.5",
        orangeSharpness: "10",
        yellowSharpness: "35",
        greenSharpness: "35",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Khezu Shock Sword I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Thunder",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Khezu Shock Sword II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Thunder",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Khezu Shock Blade",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Thunder",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Izuchi Blade I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "69",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "7",
        orangeSharpness: "20",
        yellowSharpness: "27.5",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Izuchi Blade II",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "12",
        redSharpness: "6",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Snapper Blade",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "12.5",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Deadly Serpentblade I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Poison",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "17",
        yellowSharpness: "22",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Poison Boost I/Dulling Strike",
    },
    {
        name: "Deadly Serpentblade II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Poison",
        elementalDamage: "42",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Poison Boost I/Dulling Strike",
    },
    {
        name: "Poison Serpentblade",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Poison",
        elementalDamage: "45",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Poison Boost I/Dulling Strike",
    },
    {
        name: "Hidden Blade I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        redSharpness: "12",
        orangeSharpness: "20",
        yellowSharpness: "22",
        greenSharpness: "30",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Blade II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        redSharpness: "27",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "30",
        blueSharpness: "15",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Dark of Night",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "35",
        redSharpness: "18",
        orangeSharpness: "10",
        yellowSharpness: "35",
        greenSharpness: "25",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
    },
    {
        name: "Frilled Blade I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Sleep",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "15",
        yellowSharpness: "35",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Frilled Blade II",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Sleep",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "17",
        yellowSharpness: "30",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Illusory Frilled Blade",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Sleep",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "13",
        orangeSharpness: "25",
        yellowSharpness: "35",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Iron Sword I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Steel Sword",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Buster Sword I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "17",
        yellowSharpness: "17",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Buster Blade",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "17",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Chrome Razor I",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Poison",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "30",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Poison Boost I/Silkbind Boost",
    },
    {
        name: "Chrome Quietus",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Poison Boost I/Silkbind Boost",
    },
    {
        name: "Barbaroi Blade I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Defense Grinder I",
    },
    {
        name: "Barbaroi Blade II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Fire",
        elementalDamage: "42",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "13",
        yellowSharpness: "30",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Defense Grinder I",
    },
    {
        name: "Crimson Goat",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "45",
        affinity: "0",
        redSharpness: "13",
        orangeSharpness: "16",
        yellowSharpness: "43",
        greenSharpness: "7",
        blueSharpness: "3",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Defense Boost II/Defense Grinder II",
    },
    {
        name: "Pukei Edge I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Poison",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "9",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Pukei Edge II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Poison",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "25",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Datura Cleaver",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "17",
        yellowSharpness: "12",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Poison Boost II",
    },
    {
        name: "Icicle Fang I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Ice",
        elementalDamage: "30",
        affinity: "30",
        redSharpness: "13",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Icicle Fang II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Ice",
        elementalDamage: "34",
        affinity: "30",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "30",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Paladire",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "38",
        affinity: "35",
        redSharpness: "13",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "30",
        blueSharpness: "13",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Aknosom Blade I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Eploit",
    },
    {
        name: "Aknosom Blade II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Fire",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "22",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Fireblight Eploit",
    },
    {
        name: "Daybreak Cleaver",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "15",
        yellowSharpness: "28",
        greenSharpness: "36",
        blueSharpness: "4",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost II/Fireblight Eploit",
    },
    {
        name: "Tetranadon Edge I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Water",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "13",
        yellowSharpness: "25",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost I/Dulling Strike",
    },
    {
        name: "Tetranadon Edge II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Water",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost II/Dulling Strike",
    },
    {
        name: "Tetranadon Cutter",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "21",
        yellowSharpness: "27",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost III/Dulling Strike",
    },
    {
        name: "Bone Blade I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "9",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "25",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Slasher",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Jawblade I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Giant Jawblade",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "20",
        yellowSharpness: "17",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Wyvern Fang I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Dragon",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "7",
        yellowSharpness: "27",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost I/Dulling Strike",
    },
    {
        name: "Great Wyvern Fang",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "11",
        yellowSharpness: "30",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Dragon Boost I/Dulling Strike",
    },
    {
        name: "Golem Blade I",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "16",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Blade of Talos",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "15",
        yellowSharpness: "19",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Valkyrie Blade I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "22",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Valkyrie Blade II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "23",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Sieglinde",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Poison",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Jyura Mudblade I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "30",
        orangeSharpness: "22",
        yellowSharpness: "7",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Water Boost I/Brutal Strike",
    },
    {
        name: "Jyura Mudblade II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Water",
        elementalDamage: "17",
        affinity: "-10",
        redSharpness: "30",
        orangeSharpness: "17",
        yellowSharpness: "7",
        greenSharpness: "21",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Water Boost II/Brutal Strike",
    },
    {
        name: "Terracutter",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Water",
        elementalDamage: "20",
        affinity: "-10",
        redSharpness: "28",
        orangeSharpness: "17",
        yellowSharpness: "7",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Water Boost II/Brutal Strike",
    },
    {
        name: "Red Wing I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "19",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Bonus II/Fire Boost I/Element Exploit",
    },
    {
        name: "Red Wing II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "10",
        yellowSharpness: "29",
        greenSharpness: "29",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Bonus II/Fire Boost I/Element Exploit",
    },
    {
        name: "Rathalos Firesword",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Quarrel Hornsword I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "8",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        redSharpness: "14",
        orangeSharpness: "10",
        yellowSharpness: "11",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dulling Strike",
    },
    {
        name: "Quarrel Hornsword II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "12",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "7",
        greenSharpness: "27",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost I/Defense Grinder I",
    },
    {
        name: "Feud Hornsword",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "16",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        redSharpness: "9",
        orangeSharpness: "15",
        yellowSharpness: "19",
        greenSharpness: "28",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Defense Grinder I",
    },
    {
        name: "Hack Blade I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "26",
        yellowSharpness: "7",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost I/Dulling Strike/Small Monster Exploit",
    },
    {
        name: "Hack Blade II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "34",
        yellowSharpness: "7",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Dulling Strike/Small Monster Exploit",
    },
    {
        name: "Jaggi Greatblade",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "38",
        yellowSharpness: "7",
        greenSharpness: "7",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Dulling Strike/Defense Grinder I",
    },
    {
        name: "Flammenzahn I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "-20",
        redSharpness: "28",
        orangeSharpness: "17",
        yellowSharpness: "7",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flammenzahn II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Fire",
        elementalDamage: "24",
        affinity: "-20",
        redSharpness: "28",
        orangeSharpness: "25",
        yellowSharpness: "8",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
    },
    {
        name: "Gnashing Flammenzahn",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Fire",
        elementalDamage: "26",
        affinity: "-20",
        redSharpness: "30",
        orangeSharpness: "30",
        yellowSharpness: "9",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost III/Brutal Strike",
    },
    {
        name: "Usurper's Storm I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "12",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Storm II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "6",
        yellowSharpness: "25",
        greenSharpness: "29",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Cataclysm Sword I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Water",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Cataclysm Sword II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Water",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Cataclysm Blade",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Water",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "10",
        yellowSharpness: "28",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Snowclad I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "19",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost I/Small Monster Exploit",
    },
    {
        name: "Snowclad II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Ice",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "10",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Ice Boost II/Small Monster Exploit",
    },
    {
        name: "Lagombi Charlotte",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "7",
        yellowSharpness: "24",
        greenSharpness: "24",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost II/Dulling Strike",
    },
    {
        name: "Sinister Blade I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "37",
        orangeSharpness: "4",
        yellowSharpness: "10",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Blade II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "21",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Shadowblade",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "3",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Demon Rod I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "10",
        redSharpness: "11",
        orangeSharpness: "4",
        yellowSharpness: "24",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Demon Rod II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "24",
        affinity: "10",
        redSharpness: "4",
        orangeSharpness: "9",
        yellowSharpness: "25",
        greenSharpness: "21",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Azure Elder Great Sword I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Great Sword II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "11",
        greenSharpness: "10",
        blueSharpness: "21",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Great Sword I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "46",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "46",
        greenSharpness: "9",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Icesteel Edge I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "40",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Teostra Blade I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "30",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Grand Shamshir I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "60",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Wyvern's Perch I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Poison",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "6",
        yellowSharpness: "35",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Poison Boost I/Dulling Strike/Spiribird Doubled",
    },
    {
        name: "Wyvern's Perch II",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "10",
        yellowSharpness: "40",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Poison Boost I/Dulling Strike/Spiribird Doubled",
    },
    {
        name: "Roguish Deathcap",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Poison",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "6",
        yellowSharpness: "41",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Poison Boost I/Dulling Strike/Spiribird Doubled",
    },
    {
        name: "Sleepy Shellblade I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Sleep",
        elementalDamage: "8",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "11",
        yellowSharpness: "21",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost I/Sleep Boost I/Anti-Aquatic Species",
    },
    {
        name: "Sleepy Shellblade II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "17",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Sleep",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "21",
        yellowSharpness: "25",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Sleep Boost I/Anti-Aquatic Species",
    },
    {
        name: "Soporific Shellblade",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Sleep",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "20",
        yellowSharpness: "31",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost III/Sleep Boost II/Anti-Aquatic Species",
    },
    {
        name: "Frozen Speartuna I",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Ice",
        elementalDamage: "50",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "10",
        yellowSharpness: "27",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Element Exploit/Iceblight Exploit",
    },
    {
        name: "Frozen Speartuna II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Ice",
        elementalDamage: "60",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "10",
        yellowSharpness: "26",
        greenSharpness: "24",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Element Exploit/Iceblight Exploit",
    },
    {
        name: "Freezer Speartuna",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "70",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "22",
        greenSharpness: "25",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Element Exploit/Iceblight Exploit",
    },
    {
        name: "Ninja Parasol I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "26",
        yellowSharpness: "11",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Ninja Parasol II",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "26",
        yellowSharpness: "12",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Defense Boost III/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Dragonslayer Parasol",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Dragon",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "25",
        yellowSharpness: "15",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Defense Boost III/Dragon Boost III/Dragon Exploit",
    },
    {
        name: "Cat's Soul I",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Paralysis",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "10",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dulling Strike/Buddy Rally",
    },
    {
        name: "Cat's Soul II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Paralysis",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dulling Strike/Buddy Rally",
    },
    {
        name: "Cat's Curse",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Paralysis",
        elementalDamage: "45",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "14",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Dulling Strike/Buddy Rally",
    },
    {
        name: "Rampage Cleaver I",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "16",
        yellowSharpness: "22",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Cleaver II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Cleaver III",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Cleaver IV",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "4",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Cleaver V",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Akanesasu",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Water",
        elementalDamage: "30",
        affinity: "15",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Water Boost II",
    },
    {
        name: "Despot's Blackstorm",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "9",
        yellowSharpness: "28",
        greenSharpness: "19",
        blueSharpness: "8",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Abyssal Galeblade",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Cleaver",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "50",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "50",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora's Decimator",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "45",
        affinity: "10",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "15",
        greenSharpness: "8",
        blueSharpness: "6",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Foreboding Shamshir",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "66",
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "8",
        yellowSharpness: "20",
        greenSharpness: "18",
        blueSharpness: "16",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Great Demon Rod",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "26",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "18",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "King Teostra Blade",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "45",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "10",
        yellowSharpness: "5",
        greenSharpness: "18",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Redwing Claymore I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "42",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Reddnaught Claymore",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "45",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rampage Cleaver S",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
];

export default seededGreatSwordData;