let gunLanceData = [
    {
        name: "Kamura Gunlance I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "1",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "20",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Gunlance II",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "1",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Gunlance III",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "22",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Gunlance IV",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Gunlance V",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "20",
        yellowSharpness: "22",
        greenSharpness: "9",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Gunlance",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "21",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Ukiyo no Yamiwo I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "120",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "12",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
    },
    {
        name: "Ukiyo no Yamiwo II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "190",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "21",
        orangeSharpness: "19",
        yellowSharpness: "17",
        greenSharpness: "20",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Mizumori",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "210",
        elementType: "Water",
        elementalDamage: "24",
        affinity: "15",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Princess Panoply I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "100",
        elementType: "Poison",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "7",
        yellowSharpness: "17",
        greenSharpness: "17",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Princess Panoply II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "21",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "6",
        yellowSharpness: "14",
        greenSharpness: "31",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Ortlinde",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "5",
        damage: "200",
        elementType: "Poison",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "6",
        yellowSharpness: "19",
        greenSharpness: "34",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Red Rook I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "19",
        yellowSharpness: "21",
        greenSharpness: "24",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Red Rook II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "200",
        elementType: "Fire",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "19",
        yellowSharpness: "16",
        greenSharpness: "25",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Crimson Rook",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Delex Harpoon I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "1",
        damage: "100",
        elementType: "Water",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "19",
        yellowSharpness: "11",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Defense Boost I/Small Monster Exploit",
    },
    {
        name: "Delex Harpoon II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "110",
        elementType: "Water",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "26",
        yellowSharpness: "16",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost I/Small Monster Exploit",
    },
    {
        name: "Sand Blaster Gunlance",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "190",
        elementType: "Water",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "12",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Small Monster Exploit",
    },
    {
        name: "Usurper's Roar I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Roar II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "12",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot's Phlogiston",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "21",
        yellowSharpness: "30",
        greenSharpness: "11",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Twinfang I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "22",
        affinity: "30",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "17",
        greenSharpness: "17",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Twinfang II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "24",
        affinity: "35",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Ambermarch",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "26",
        affinity: "40",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "17",
        greenSharpness: "20",
        blueSharpness: "13",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost III/Iceblight Exploit",
    },
    {
        name: "Iron Gunlance I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "1",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Iron Gunlance II",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "1",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Eizenlitter",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "20",
        yellowSharpness: "11",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Striker's Ggunlance I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Striker's Ggunlance II",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "11",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Imperial Guardlance",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "12",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Silkbind Boost",
    },
    {
        name: "General's Arbalance I",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "11",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Dragon Exploit/Wyrmstake Boost",
    },
    {
        name: "General's Arbalance II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "17",
        greenSharpness: "14",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Dragon Exploit/Wyrmstake Boost",
    },
    {
        name: "Admiralls Arbalance",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Dragon Exploit/Wyrmstake Boost",
    },
    {
        name: "Pukei Gunlance I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "160",
        elementType: "Poison",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "16",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Poison Boost II",
    },
    {
        name: "Pukei Gunlance II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "21",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Poison Boost II",
    },
    {
        name: "Datura Gunlance",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "45",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Defense Boost III/Poison Boost III",
    },
    {
        name: "Diablos Gunlance I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "16",
        greenSharpness: "17",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dulling Strike",
    },
    {
        name: "Diablos Gunlance II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "21",
        orangeSharpness: "19",
        yellowSharpness: "20",
        greenSharpness: "24",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Dulling Strike",
    },
    {
        name: "Diablos Cannon",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "250",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "21",
        orangeSharpness: "14",
        yellowSharpness: "20",
        greenSharpness: "34",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Dulling Strike",
    },
    {
        name: "Aknosom Gunlance I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "11",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Aknosom Gunlance II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "90",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Aknosom Gunlance III",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "26",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost II/Fireblight Exploit",
    },
    {
        name: "Dawnbreaker Gunlance",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "14",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost II/Fireblight Exploit",
    },
    {
        name: "Almudron Gunlance I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "120",
        elementType: "Water",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "12",
        yellowSharpness: "25",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Water Boost I/Element Exploit",
    },
    {
        name: "Almudron Gunlance II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "160",
        elementType: "Water",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost I/Element Exploit",
    },
    {
        name: "Doombringer Gunlance",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "5",
        damage: "170",
        elementType: "Water",
        elementalDamage: "46",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "16",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost II/Element Exploit",
    },
    {
        name: "Full Voltage I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "1",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "13",
        affinity: "10",
        redSharpness: "9",
        orangeSharpness: "21",
        yellowSharpness: "9",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Full Voltage II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "150",
        elementType: "Thunder",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "9",
        orangeSharpness: "25",
        yellowSharpness: "16",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "High Volt Gunlance",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Shattershot I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "100",
        elementType: "Paralysis",
        elementalDamage: "24",
        affinity: "-10",
        redSharpness: "30",
        orangeSharpness: "10",
        yellowSharpness: "11",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Dulling Strike",
    },
    {
        name: "Shattershot II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "160",
        elementType: "Paralysis",
        elementalDamage: "26",
        affinity: "-10",
        redSharpness: "33",
        orangeSharpness: "10",
        yellowSharpness: "12",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Defense Boost II/Dulling Strike",
    },
    {
        name: "Shatter God",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "180",
        elementType: "Paralysis",
        elementalDamage: "28",
        affinity: "-1",
        redSharpness: "37",
        orangeSharpness: "12",
        yellowSharpness: "13",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Defense Boost III/Dulling Strike",
    },
    {
        name: "Baggi Gunlance I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "1",
        damage: "80",
        elementType: "Sleep",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "6",
        yellowSharpness: "13",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Sleep Boost I/Buddy Rally",
    },
    {
        name: "Baggi Gunlance II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "100",
        elementType: "Sleep",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "15",
        yellowSharpness: "11",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Sleep Boost I/Buddy Rally",
    },
    {
        name: "Baggi Gunlance III",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "140",
        elementType: "Sleep",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "15",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Sleep Boost I/Buddy Rally",
    },
    {
        name: "Lullabyte Sleeplance",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "180",
        elementType: "Sleep",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Sleep Boost II/Buddy Rally",
    },
    {
        name: "Kadachi Striker I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "19",
        affinity: "15",
        redSharpness: "28",
        orangeSharpness: "12",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Thunder Boost II",
    },
    {
        name: "Kadachi Striker II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Long ",
        shellingLevel: "3",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "24",
        affinity: "15",
        redSharpness: "24",
        orangeSharpness: "20",
        yellowSharpness: "12",
        greenSharpness: "18",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Thunder Boost III",
    },
    {
        name: "Mythic Kadachi Striker",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "27",
        affinity: "20",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "6",
        greenSharpness: "22",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Thunder Boost III",
    },
    {
        name: "Bone Gunlance I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "1",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Gunlance II",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "1",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Wyvern Bone Gunlance",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "14",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Golem Gunlance I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Golem Gunlance II",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Behemoth Gunlance",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Hidden Gunlance I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Gunlance II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "11",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "24",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Fading Night",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "12",
        orangeSharpness: "18",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "15",
        whiteSharpness: "5",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
    },
    {
        name: "Flaming Gunlance I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "15",
        affinity: "-20",
        redSharpness: "24",
        orangeSharpness: "21",
        yellowSharpness: "6",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flaming Gunlance II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "17",
        affinity: "-20",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "6",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flaming Gunlance III",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "21",
        affinity: "-15",
        redSharpness: "35",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
    },
    {
        name: "Barbarous Firelance",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "230",
        elementType: "Fire",
        elementalDamage: "24",
        affinity: "-15",
        redSharpness: "42",
        orangeSharpness: "15",
        yellowSharpness: "5",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost III/Brutal Strike",
    },
    {
        name: "Barroth Loader I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "35",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Brutal Strike",
    },
    {
        name: "Barroth Loader II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "11",
        orangeSharpness: "20",
        yellowSharpness: "32",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost II/Brutal Strike",
    },
    {
        name: "Rugged Loader",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "10",
        yellowSharpness: "45",
        greenSharpness: "12",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Brutal Strike",
    },
    {
        name: "Tiger Blast I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "16",
        orangeSharpness: "6",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Tiger Blast II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "11",
        orangeSharpness: "6",
        yellowSharpness: "31",
        greenSharpness: "24",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tigrex Gunlance",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "27",
        greenSharpness: "28",
        blueSharpness: "10",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Lagomberator I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "1",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost I/Small Monster Exploit",
    },
    {
        name: "Lagomberator II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "120",
        elementType: "Ice",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "20",
        yellowSharpness: "14",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Ice Boost II/Small Monster Exploit",
    },
    {
        name: "Lagomberator III",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "20",
        yellowSharpness: "16",
        greenSharpness: "24",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Ice Boost II/Small Monster Exploit",
    },
    {
        name: "Lagomberatrix",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "210",
        elementType: "Ice",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "20",
        yellowSharpness: "21",
        greenSharpness: "26",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Ice Boost III/Small Monster Exploit",
    },
    {
        name: "Ludroth Harpoon I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "80",
        elementType: "Water",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "24",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Ludroth Harpoon II",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "10",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "140",
        elementType: "Water",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "27",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost II/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Ludroth Harpoon III",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "15",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "160",
        elementType: "Water",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "22",
        greenSharpness: "12",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Ludroth Shellbreaker",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "15",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "180",
        elementType: "Water",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "12",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Water Boost III/Waterblight Exploit",
    },
    {
        name: "Fiore Nulo I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "1",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "11",
        yellowSharpness: "10",
        greenSharpness: "1",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Master Rider",
    },
    {
        name: "Fiore Nulo II",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Normal ",
        shellingLevel: "2",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "15",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I/Master Rider",
    },
    {
        name: "Fiore Unu",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "7",
        yellowSharpness: "7",
        greenSharpness: "12",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Dragon Exploit/Master Rider",
    },
    {
        name: "Rakna Gunlance I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "25",
        redSharpness: "45",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "6",
        blueSharpness: "14",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Silkbind Boost",
    },
    {
        name: "Rakna Gunlance II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "25",
        affinity: "25",
        redSharpness: "45",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "10",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Fire Boost II/Silkbind Boost",
    },
    {
        name: "Arknalance",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "5",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "27",
        affinity: "25",
        redSharpness: "55",
        orangeSharpness: "5",
        yellowSharpness: "11",
        greenSharpness: "5",
        blueSharpness: "20",
        whiteSharpness: "4",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Fire Boost II/Silkbind Boost",
    },
    {
        name: "Fiore Nulo Black I",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "150",
        elementType: "Dragon",
        elementalDamage: "21",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "7",
        yellowSharpness: "7",
        greenSharpness: "19",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Element Exploit",
    },
    {
        name: "Fiore Nulo Black II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost III/Element Exploit",
    },
    {
        name: "Fiore Unu Black",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "20",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost III/Element Exploit",
    },
    {
        name: "Fiore Nulo White I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "4",
        yellowSharpness: "6",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Element Exploit/Silkbind Boost",
    },
    {
        name: "Fiore Nulo White II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "130",
        elementType: "Ice",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "34",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Element Exploit/Silkbind Boost",
    },
    {
        name: "Fiore Unu White",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "34",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Element Exploit/Silkbind Boost",
    },
    {
        name: "Fiore Nulo Green I",
        type: "GreatSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "1",
        damage: "80",
        elementType: "Paralysis",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "7",
        yellowSharpness: "7",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Paralysis Boost I/Anti-Aerial Species",
    },
    {
        name: "Fiore Nulo Green II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "130",
        elementType: "Paralysis",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "34",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Paralysis Boost I/Anti-Aerial Species",
    },
    {
        name: "Fiore Unu Green",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "3",
        damage: "140",
        elementType: "Paralysis",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "34",
        orangeSharpness: "7",
        yellowSharpness: "7",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost III/Paralysis Boost II/Anti-Aerial Species",
    },
    {
        name: "Sinister Gunlance I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "4",
        yellowSharpness: "10",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Gunlance II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "22",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Shadowshot",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Demon Gunlance I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "16",
        affinity: "-10",
        redSharpness: "10",
        orangeSharpness: "5",
        yellowSharpness: "24",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Demon Gunlance II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "-10",
        redSharpness: "9",
        orangeSharpness: "5",
        yellowSharpness: "30",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Azure Elder Gunlance I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "10",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Gunlance II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "11",
        greenSharpness: "11",
        blueSharpness: "26",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Gunlance I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "46",
        greenSharpness: "10",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Bazel Buster I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "15",
        orangeSharpness: "22",
        yellowSharpness: "15",
        greenSharpness: "23",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Wyrmstake Boost",
    },
    {
        name: "Bazel Bluster II",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "210",
        elementType: "Blast",
        elementalDamage: "14",
        affinity: "-10",
        redSharpness: "12",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "17",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Wyrmstake Boost",
    },
    {
        name: "Bazel Destroyer",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "220",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "12",
        orangeSharpness: "25",
        yellowSharpness: "16",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Blast Boost III/Wyrmstake Boost",
    },
    {
        name: "Icesteel Gunlance I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "5",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "42",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "8",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Venomous Cologne I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "220",
        elementType: "Poison",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "30",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Canyne Cannon I",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "5",
        phialOrShellingType: "Long",
        shellingLevel: "2",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "24",
        yellowSharpness: "15",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Wyrmstake Boost",
    },
    {
        name: "Canyne Cannon II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "5",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "27",
        yellowSharpness: "15",
        greenSharpness: "19",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Wyrmstake Boost/Buddy Rally",
    },
    {
        name: "Howlitzer",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "Long",
        shellingLevel: "5",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "28",
        yellowSharpness: "14",
        greenSharpness: "18",
        blueSharpness: "11",
        whiteSharpness: "5",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost III/Buddy Rally",
    },
    {
        name: "Cornpopper I",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "9",
        yellowSharpness: "34",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Wyrmstake Boost/Anti-Aquatic Species/Spiribird Doubled",
    },
    {
        name: "Cornpopper II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "40",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Wyrmstake Boost/Anti-Aquatic Species/Spiribird Doubled",
    },
    {
        name: "Mighty Cornpopper",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "5",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "40",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Anti-Aquatic Species/Spiribird Doubled",
    },
    {
        name: "Sleepy Shellgun I",
        type: "GreatSword",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "100",
        elementType: "Sleep",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "21",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost I/Sleep Boost I/Anti-Aquatic Species",
    },
    {
        name: "Sleepy Shellgun II",
        type: "GreatSword",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "Wide",
        shellingLevel: "2",
        damage: "130",
        elementType: "Sleep",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Sleep Boost I/Anti-Aquatic Species",
    },
    {
        name: "Soporific Shellgun",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "Wide",
        shellingLevel: "3",
        damage: "190",
        elementType: "Sleep",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "21",
        yellowSharpness: "25",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost III/Sleep Boost II/Anti-Aquatic Species",
    },
    {
        name: "Rampage Gunlance I",
        type: "GreatSword",
        rarity: "4",
        defenseIncrease: "00",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "16",
        yellowSharpness: "21",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Gunlance II",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Gunlance III",
        type: "GreatSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "7",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Gunlance IV",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "20",
        yellowSharpness: "17",
        greenSharpness: "7",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Gunlance V",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Great Demon Gunlance",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "7",
        damage: "220",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "-10",
        redSharpness: "10",
        orangeSharpness: "4",
        yellowSharpness: "21",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Abyssal Gale Gunlance",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Wide",
        shellingLevel: "4",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Gunlance",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "4",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "41",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "50",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora's Brigia",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "5",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "44",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "15",
        greenSharpness: "8",
        blueSharpness: "6",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Venomous Attar",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "3",
        damage: "230",
        elementType: "Poison",
        elementalDamage: "31",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "22",
        greenSharpness: "18",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Redwing Gunlance I",
        type: "GreatSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Reddnaught Gunlance",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Long",
        shellingLevel: "4",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rampage Gunlance S",
        type: "GreatSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Normal",
        shellingLevel: "2",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
];

export default gunLanceData;