let hammerData = [
    {
        name: "Kamura Hammer I",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "25",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Hammer II",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Hammer III",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Hammer IV",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Hammer V",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Hammer",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Purity Hammer I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Water",
        elementalDamage: "21",
        affinity: "15",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost I",
    },
    {
        name: "Purity Hammer II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Water",
        elementalDamage: "26",
        affinity: "15",
        redSharpness: "25",
        orangeSharpness: "25",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Sinter Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Water",
        elementalDamage: "31",
        affinity: "20",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Water Boost II",
    },
    {
        name: "Binding Bludgeon I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Paralysis",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Dulling Strike",
    },
    {
        name: "Binding Bludgeon II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Paralysis",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost II/Dulling Strike",
    },
    {
        name: "Armored Gogue",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Paralysis",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "12",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Defense Boost III/Dulling Strike",
    },
    {
        name: "Almudron Hammer I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Water",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "13",
        yellowSharpness: "22",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Water Boost I/Element Exploit",
    },
    {
        name: "Almudron Hammer II",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Water",
        elementalDamage: "48",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "23",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Water Boost I/Element Exploit",
    },
    {
        name: "Doom Bringer Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Water",
        elementalDamage: "51",
        affinity: "0",
        redSharpness: "13",
        orangeSharpness: "13",
        yellowSharpness: "30",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost II/Element Exploit",
    },
    {
        name: "Five-Pronged Hammer I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "30",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Anti-Aerial Species/Silkbind Boost",
    },
    {
        name: "Five-Pronged Hammer II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "38",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Anti-Aerial Species/Silkbind Boost",
    },
    {
        name: "Great Pronged Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "43",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Anti-Aerial Species/Silkbind Boost",
    },
    {
        name: "Wroggi Hammer I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Poison",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "8",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Poison Boost I/Buddy Rally",
    },
    {
        name: "Wroggi Hammer II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Poison",
        elementalDamage: "31",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "9",
        yellowSharpness: "20",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Poison Boost I/Buddy Rally",
    },
    {
        name: "Dirty Hammer",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Poison",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Affinity Boost II/Poison Boost II/Buddy Rally",
    },
    {
        name: "Gun Hammer I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "4",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Fire",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "12",
        yellowSharpness: "13",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Fireblight Exploit/Small Monster Exploit",
    },
    {
        name: "Gun Hammer II",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "8",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "45",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "17",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Fireblight Exploit/Small Monster Exploit",
    },
    {
        name: "Deadeye Revolver",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "50",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "21",
        yellowSharpness: "8",
        greenSharpness: "11",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost IV/Fireblight Exploit/Small Monster Exploit",
    },
    {
        name: "Iron Hammer I",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Iron Devil",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "War Hammer I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "16",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "War Mace",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "16",
        yellowSharpness: "10",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "War Stamp I",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "19",
        yellowSharpness: "20",
        greenSharpness: "11",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbind Boost",
    },
    {
        name: "War Basher",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "12",
        yellowSharpness: "27",
        greenSharpness: "11",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Great Nova I",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "5",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "8",
        yellowSharpness: "22",
        greenSharpness: "14",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Defense Boost III/Dragon Exploit/Element Exploit",
    },
    {
        name: "Great Nova II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "5",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "11",
        yellowSharpness: "29",
        greenSharpness: "13",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Defense Boost III/Dragon Exploit/Element Exploit",
    },
    {
        name: "Super Nova",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "5",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "13",
        yellowSharpness: "22",
        greenSharpness: "16",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Defense Boost III/Dragon Exploit/Element Exploit",
    },
    {
        name: "Striped Striker I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "16",
        orangeSharpness: "8",
        yellowSharpness: "23",
        greenSharpness: "21",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Striped Striker II",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "11",
        orangeSharpness: "8",
        yellowSharpness: "31",
        greenSharpness: "24",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tigrex Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "12",
        orangeSharpness: "9",
        yellowSharpness: "30",
        greenSharpness: "30",
        blueSharpness: "12",
        whiteSharpness: "5",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Flaming Fury I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "17",
        affinity: "-20",
        redSharpness: "28",
        orangeSharpness: "17",
        yellowSharpness: "6",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flaming Fury II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "-20",
        redSharpness: "28",
        orangeSharpness: "23",
        yellowSharpness: "7",
        greenSharpness: "8",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
    },
    {
        name: "Phoenix Fury",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "-20",
        redSharpness: "30",
        orangeSharpness: "29",
        yellowSharpness: "6",
        greenSharpness: "13",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost III/Brutal Strike",
    },
    {
        name: "Glacial Bash I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "21",
        affinity: "30",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "16",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Glacial Bash II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Ice",
        elementalDamage: "23",
        affinity: "30",
        redSharpness: "11",
        orangeSharpness: "17",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Glacial Crunch",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "27",
        affinity: "35",
        redSharpness: "10",
        orangeSharpness: "18",
        yellowSharpness: "19",
        greenSharpness: "22",
        blueSharpness: "14",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Kulu Bludgeon I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "16",
        orangeSharpness: "12",
        yellowSharpness: "10",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Spiribird Doubled",
    },
    {
        name: "Kulu Bludgeon II",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Spiribird Doubled",
    },
    {
        name: "Kulu Crusher",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "20",
        redSharpness: "19",
        orangeSharpness: "19",
        yellowSharpness: "17",
        greenSharpness: "14",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Spiribird Doubled",
    },
    {
        name: "Devil Masher I",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Paralysis",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "5",
        yellowSharpness: "45",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Paralysis Boost I/Anti-Aquatic Species",
    },
    {
        name: "Devil Masher II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Paralysis",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "45",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Paralysis Boost II/Anti-Aquatic Species",
    },
    {
        name: "Iron Devil's Soul",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Paralysis",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "6",
        yellowSharpness: "45",
        greenSharpness: "24",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Paralysis Boost II/Anti-Aquatic Species",
    },
    {
        name: "Unbearable Hammer I",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "32",
        orangeSharpness: "8",
        yellowSharpness: "7",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Defense Boost II/Small Monster Exploit",
    },
    {
        name: "Unbearable Hammer II",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost II/Small Monster Exploit",
    },
    {
        name: "Barbearic Hammer",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "7",
        yellowSharpness: "19",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Small Monster Exploit",
    },
    {
        name: "Frilled Blow I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Sleep",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "16",
        yellowSharpness: "27",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Frilled Blow II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Sleep",
        elementalDamage: "21",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "9",
        yellowSharpness: "27",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Illusory Frilled Blow",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Sleep",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "23",
        yellowSharpness: "28",
        greenSharpness: "27",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Bag o' Horrors I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Thunder",
        elementalDamage: "42",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "10",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Bag o' Horrors II",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Thunder",
        elementalDamage: "43",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "14",
        yellowSharpness: "11",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Bag o' Thunder",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Thunder",
        elementalDamage: "46",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "9",
        yellowSharpness: "17",
        greenSharpness: "16",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Frozen Core I",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "13",
        yellowSharpness: "14",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Ice Boost I/Buddy Rally",
    },
    {
        name: "Frozen Core II",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Ice",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "12",
        yellowSharpness: "14",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Ice Boost I/Buddy Rally",
    },
    {
        name: "Cocytus",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "14",
        yellowSharpness: "19",
        greenSharpness: "11",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Defense Boost/Element Exploit/Buddy Rally",
    },
    {
        name: "Bone Hammer I",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "23",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Hammer II",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "13",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Hard Bone Hammer",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "21",
        yellowSharpness: "18",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Bone Bludgeon I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "19",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Bone Bludgeon II",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "15",
        yellowSharpness: "26",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Heavy Bone Bludgeon",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Diablos Hammer I",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        redSharpness: "11",
        orangeSharpness: "39",
        yellowSharpness: "6",
        greenSharpness: "24",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Brutal Strike",
    },
    {
        name: "Diablos Hammer II",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        redSharpness: "12",
        orangeSharpness: "40",
        yellowSharpness: "5",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defemse Boost II/Brutal Strike",
    },
    {
        name: "Cyclo-Hammer I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "18",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Master Rider/Spiribird Doubled",
    },
    {
        name: "Cyclo-Hammer II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "23",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Master Rider/Spiribird Doubled",
    },
    {
        name: "Atlas Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "37",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Master Rider/Spiribird Doubled",
    },
    {
        name: "Pukei Hammer I",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Poison",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "21",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Poison Boost II",
    },
    {
        name: "Pukei Hammer II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "47",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "21",
        greenSharpness: "28",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Poison Boost II",
    },
    {
        name: "Datura Club",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "54",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "28",
        yellowSharpness: "9",
        greenSharpness: "18",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Defense Boost III/Poison Boost II",
    },
    {
        name: "Basarios Blow I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "33",
        yellowSharpness: "13",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Attack Boost II/Dulling Strike",
    },
    {
        name: "Basarios Blow II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "31",
        yellowSharpness: "11",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Attack Boost III/Dulling Strike",
    },
    {
        name: "Basarios Bash",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "31",
        yellowSharpness: "16",
        greenSharpness: "13",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Attack Boost III/Dulling Strike",
    },
    {
        name: "Red Bludgeon I",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "27",
        affinity: "5",
        redSharpness: "56",
        orangeSharpness: "3",
        yellowSharpness: "2",
        greenSharpness: "17",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Red Bludgeon II",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Fire",
        elementalDamage: "31",
        affinity: "5",
        redSharpness: "54",
        orangeSharpness: "2",
        yellowSharpness: "3",
        greenSharpness: "16",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Huracan Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "34",
        affinity: "5",
        redSharpness: "55",
        orangeSharpness: "2",
        yellowSharpness: "3",
        greenSharpness: "16",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Yeti Hammer I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "13",
        affinity: "-15",
        redSharpness: "24",
        orangeSharpness: "6",
        yellowSharpness: "21",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost I/Brutal Strike",
    },
    {
        name: "Yet Hammer II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "-15",
        redSharpness: "24",
        orangeSharpness: "6",
        yellowSharpness: "26",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost II/Brutal Strike",
    },
    {
        name: "Yeti Hammer III",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Ice",
        elementalDamage: "17",
        affinity: "-15",
        redSharpness: "24",
        orangeSharpness: "6",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost II/Brutal Strike",
    },
    {
        name: "Abominable Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "-15",
        redSharpness: "24",
        orangeSharpness: "6",
        yellowSharpness: "21",
        greenSharpness: "14",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost III/Brutal Strike",
    },
    {
        name: "Usurper's Thunder I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "21",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Thunder II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "16",
        greenSharpness: "21",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot's Crackle",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "24",
        greenSharpness: "24",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Calamitous Portent I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Poison",
        elementalDamage: "12",
        affinity: "5",
        redSharpness: "21",
        orangeSharpness: "14",
        yellowSharpness: "20",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Poison Boost I/Dulling Strike",
    },
    {
        name: "Calamitous Portent II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Poison",
        elementalDamage: "14",
        affinity: "5",
        redSharpness: "29",
        orangeSharpness: "11",
        yellowSharpness: "11",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Poison Boost I/Dulling Strike",
    },
    {
        name: "Catastrophic Portent",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "16",
        affinity: "10",
        redSharpness: "30",
        orangeSharpness: "15",
        yellowSharpness: "11",
        greenSharpness: "14",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Poison Boost II/Dulling Strike",
    },
    {
        name: "Droth Splashhammer I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Water",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "10",
        yellowSharpness: "21",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Droth Splashhammer II",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Water",
        elementalDamage: "31",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Ludroth Dousehammer",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Water",
        elementalDamage: "31",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "9",
        yellowSharpness: "27",
        greenSharpness: "14",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Izuchi Hammer I",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "70",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "18",
        yellowSharpness: "23",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Izuchi Hammer II",
        type: "Hammer",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "12",
        redSharpness: "6",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Snapper Hammer",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "6",
        orangeSharpness: "19",
        yellowSharpness: "13",
        greenSharpness: "17",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Hidden Breaker I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "11",
        orangeSharpness: "17",
        yellowSharpness: "19",
        greenSharpness: "24",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Breaker II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "24",
        orangeSharpness: "6",
        yellowSharpness: "16",
        greenSharpness: "25",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Night Eternal",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "45",
        redSharpness: "17",
        orangeSharpness: "13",
        yellowSharpness: "29",
        greenSharpness: "22",
        blueSharpness: "14",
        whiteSharpness: "5",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Carapace Hammer I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "5",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "35",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dulling Strike",
    },
    {
        name: "Carapace Hammer II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "8",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "47",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dulling Strike",
    },
    {
        name: "Barroth Hammer",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-5",
        redSharpness: "30",
        orangeSharpness: "7",
        yellowSharpness: "19",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Dulling Strike",
    },
    {
        name: "Sinister Hammer I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "53",
        orangeSharpness: "4",
        yellowSharpness: "8",
        greenSharpness: "18",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Hammer II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "21",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Shade Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "4",
        greenSharpness: "21",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Egg Hammer I",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "11",
        orangeSharpness: "24",
        yellowSharpness: "24",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Dragon Exploit/Anti-Aerial Species/Anti-Aquatic Species",
    },
    {
        name: "Egg Hammer II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "11",
        orangeSharpness: "24",
        yellowSharpness: "36",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Dragon Exploit/Anti-Aerial Species/Anti-Aquatic Species",
    },
    {
        name: "Gargwa Hammer",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "260",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "11",
        orangeSharpness: "24",
        yellowSharpness: "47",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Dragon Exploit/Anti-Aerial Species/Anti-Aquatic Species",
    },
    {
        name: "Mane Malice I",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "11",
        affinity: "-20",
        redSharpness: "11",
        orangeSharpness: "4",
        yellowSharpness: "23",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Mane Malice II",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Thunder",
        elementalDamage: "13",
        affinity: "-15",
        redSharpness: "11",
        orangeSharpness: "18",
        yellowSharpness: "24",
        greenSharpness: "24",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Azure Elder Hammer I",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "10",
        blueSharpness: "23",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Hammer II",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Hammer I",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "47",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "45",
        greenSharpness: "9",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Icesteel Hammer I",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "36",
        affinity: "10",
        redSharpness: "16",
        orangeSharpness: "10",
        yellowSharpness: "26",
        greenSharpness: "22",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Teostra Cratermaker I",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Blast",
        elementalDamage: "40",
        affinity: "5",
        redSharpness: "36",
        orangeSharpness: "4",
        yellowSharpness: "16",
        greenSharpness: "22",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Genie's Expanse I",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "6",
        yellowSharpness: "20",
        greenSharpness: "23",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Chameleos Soul",
    },
    {
        name: "Teddybear I",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Sleep",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "5",
        yellowSharpness: "30",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Teddybear II",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Sleep",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "4",
        yellowSharpness: "33",
        greenSharpness: "14",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Sleepy Bear",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Sleep",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "4",
        yellowSharpness: "45",
        greenSharpness: "15",
        blueSharpness: "9",
        whiteSharpness: "9",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost IV/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Graceful Death I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "3",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Dragon",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dragon Boost I/Dragon Exploit",
    },
    {
        name: "Graceful Death II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "5",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Dragon",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "16",
        yellowSharpness: "18",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost I/Dragon Exploit",
    },
    {
        name: "Graceful Death III",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "8",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "23",
        yellowSharpness: "22",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Yadora Morte",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "46",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "24",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Pumpking I",
        type: "Hammer",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Fire",
        elementalDamage: "8",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "25",
        yellowSharpness: "6",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Master Rider/Spiribird Doubled",
    },
    {
        name: "Pumpking II",
        type: "Hammer",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "24",
        yellowSharpness: "4",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Master Rider/Spiribird Doubled",
    },
    {
        name: "Jack-'o-lantern King",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "24",
        yellowSharpness: "9",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Master Rider/Spiribird Doubled",
    },
    {
        name: "Rampage Hammer I",
        type: "Hammer",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Hammer II",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Hammer III",
        type: "Hammer",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "19",
        greenSharpness: "7",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Hammer IV",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "24",
        yellowSharpness: "9",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Hammer V",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "17",
        yellowSharpness: "12",
        greenSharpness: "12",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Redwing Drill I",
        type: "Hammer",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Abyssal Gale Mauler",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Mauler",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "49",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "50",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora's Colossus",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "42",
        affinity: "10",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "15",
        greenSharpness: "8",
        blueSharpness: "6",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Diablos Tail",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-25",
        redSharpness: "10",
        orangeSharpness: "0",
        yellowSharpness: "2",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Brutal Strike",
    },
    {
        name: "Diamalto's Dream",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Poison",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Mane Malice Rajang",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "Thunder",
        elementalDamage: "16",
        affinity: "-10",
        redSharpness: "12",
        orangeSharpness: "12",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Teostra Cratergouger",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "46",
        affinity: "5",
        redSharpness: "30",
        orangeSharpness: "4",
        yellowSharpness: "6",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Reddnaught Hammer",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "43",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rampage Hammer S",
        type: "Hammer",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
];

export default hammerData;