let heavyBowgunData = [
    {
        name: "Kamura H. Bowgun I",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "60",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura H. Bowgun II",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "70",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura H. Bowgun III",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura H. Bowgun IV",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "140",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura H. Bowgun V",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "160",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja H. Bowgun",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "190",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Tigrex Howl I",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average //Below Avg.//Arc Shot//Wyvernheart",
        damage: "160",
        affinity: "-10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Sticky Effect I/Cluster Effect I",
    },
    {
        name: "Tigrex Howl II",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R. Severe//Average//Below Avg.//Arc Shot//Wyvernheart",
        damage: "230",
        affinity: "-10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Sticky Effect I/Cluster Effect II",
    },
    {
        name: "Cirrus Blaster I",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernsnipe",
        damage: "130",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Normal Effect I",
    },
    {
        name: "Cirrus Blaster II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernsnipe",
        damage: "190",
        affinity: "10",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Normal Effect I",
    },
    {
        name: "Reversal Shot I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//High//Below Avg.//N/A//Wyvernsnipe",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost I/Cluster Effect I/Waterblight Exploit",
    },
    {
        name: "Reversal Shot II",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//High//Below Avg.//N/A//Wyvernsnipe",
        damage: "170",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Cluster Effect I/Waterblight Exploit",
    },
    {
        name: "Reversal Shot III",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "17",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//High//Below Avg.//N/A//Wyvernsnipe",
        damage: "180",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Cluster Effect I/Waterblight Exploit",
    },
    {
        name: "Reversal Barrage",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//High//Below Avg.//N/A//Wyvernsnipe",
        damage: "220",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Cluster Effect II/Waterblight Exploit",
    },
    {
        name: "Queen's Longfire I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//N/A//Wyvernsnipe",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Spread Effect I/Small Monster Exploit",
    },
    {
        name: "Queen's Longfire II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Spread Effect I/Small Monster Exploit",
    },
    {
        name: "Queen's Farflier",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "210",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Spread Effect II/Small Monster Exploit",
    },
    {
        name: "Guerrera Cannon I",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//N/A//Wyvernsnipe",
        damage: "180",
        affinity: "20",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost/Iceblight Exploit",
    },
    {
        name: "Guerrera Cannon II",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//N/A//Wyvernsnipe",
        damage: "190",
        affinity: "20",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Arzuros Gun I",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernsnipe",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Defense Boost I/Small Monster Exploit",
    },
    {
        name: "Arzuros Gun II",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernsnipe",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost I/Small Monster Exploit",
    },
    {
        name: "Arzuros Fishergun",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernsnipe",
        damage: "170",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost II/Small Monster Exploit",
    },
    {
        name: "Usurper's Tremor I",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernheart",
        damage: "140",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Tremor II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernheart",
        damage: "200",
        affinity: "10",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot's Paroxysm",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernheart",
        damage: "220",
        affinity: "10",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Anti-Aquatic Species",
    },
    {
        name: "Iron Assault I",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernheart",
        damage: "80",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Iron Assault II",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Average//N/A//Wyvernheart",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Steel Assault",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Average//N/A//Wyvernheart",
        damage: "140",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Striker's Bowgun I",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernheart",
        damage: "170",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Striker's Bowgun II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernheart",
        damage: "190",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Elite Bowgun",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernheart",
        damage: "230",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Flammenkanone I Heavy Bowgun",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Severe//High//Below Avg.//Arc Shot//Wyvernheart",
        damage: "210",
        affinity: "-20",
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Cluster Effect I/Brutal Strike",
    },
    {
        name: "Flammenkanone II Heavy Bowgun",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Severe//High//Below Avg.//Arc Shot//Wyvernheart",
        damage: "220",
        affinity: "-20",
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Cluster Effect I/Brutal Strike",
    },
    {
        name: "Meteor Bazooka I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//N/A//Wyvernsnipe",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Pierce Effect I/Shrapnel Effect I",
    },
    {
        name: "Meteor Bazooka II",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//N/A//Wyvernsnipe",
        damage: "160",
        affinity: "0",
        stringRampageSkills:
            "Attack Boost III/Pierce Effect I/Shrapnel Effect I",
    },
    {
        name: "Meteor Cannon",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below//N/A//Wyvernsnipe",
        damage: "200",
        affinity: "0",
        stringRampageSkills:
            "Attack Boost IV/Pierce Effect I/Shrapnel Effect I",
    },
    {
        name: "Rock Eater I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernsnipe",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Spread Effect I/Cluster Effect I",
    },
    {
        name: "Rock Eater II",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernsnipe",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Spread Effect I/Cluster Effect I",
    },
    {
        name: "Earth Eater",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernsnipe",
        damage: "180",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Spread Effect II/Cluster Effect I",
    },
    {
        name: "Marino Burst I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild//Average//Below Avg.//Level Shot//Wyvernheart",
        damage: "80",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Normal Effect I/Spread Effect I/Shrapnel Effect I",
    },
    {
        name: "Marino Burst II",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild//Average//Below Avg.//Level Shot//Wyvernheart",
        damage: "90",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Normal Effect II/Spread Effect I/Shrapnel Effect I",
    },
    {
        name: "Marino Cannon",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild//Average//Below Avg.//Level Shot//Wyvernheart",
        damage: "160",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Normal Effect II/Spread Effect II/Shrapnel Effect II",
    },
    {
        name: "Carom Shot I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild //Average//Below Avg.//Arc Shot//Wyvernheart",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I/Normal Effect I",
    },
    {
        name: "Carom Shot II",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild//Average//Below Avg.//Arc Shot//Wyvernheart",
        damage: "160",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Normal Effect I",
    },
    {
        name: "Rebound Shot",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild//Average//Below Avg.//Arc Shot//Wyvernheart",
        damage: "200",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost II/Normal Effect II",
    },
    {
        name: "Wind Thief Crossbow I",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernsnipe",
        damage: "80",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Wind Thief Crossbow II",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernsnipe",
        damage: "90",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Wind Thief Crossbow III",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernsnipe",
        damage: "160",
        affinity: "10",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Gale Crossbow",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernsnipe",
        damage: "180",
        affinity: "10",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost IV/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Fulgent Shot I",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "170",
        affinity: "40",
        stringRampageSkills: "Attack Boost III/Pierce Effect I/Silkbind Boost",
    },
    {
        name: "Fulgent Shot II",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "180",
        affinity: "40",
        stringRampageSkills: "Attack Boost III/Pierce Effect I/Silkbind Boost",
    },
    {
        name: "Bone Shooter I",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernsnipe",
        damage: "90",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Shooter II",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernsnipe",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Bone Buster",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernsnipe",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Pukei Launcher I",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernsnipe",
        damage: "190",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Spread Effect I",
    },
    {
        name: "Pukei Launcher II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernsnipe",
        damage: "200",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost I/Spread Effect I",
    },
    {
        name: "Venomhail",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernsnipe",
        damage: "210",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost I/Spread Effect II",
    },
    {
        name: "Anteka Burst I",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//Arc Shot//Wyvernheart",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Pierce Effect I/Spread Effect I",
    },
    {
        name: "Anteka Burst II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//Arc Shot//Wyvernheart",
        damage: "180",
        affinity: "0",
        stringRampageSkills: "Defense Boost II/Pierce Effect I/Spread Effect I",
    },
    {
        name: "Anteka Blaster",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//Arc Shot//Wyvernheart",
        damage: "200",
        affinity: "0",
        stringRampageSkills:
            "Defense Boost II/Pierce Effect I/Spread Effect II",
    },
    {
        name: "Dual Threat I",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Sever//Average//Slow//Arc Shot//Wyvernsnipe",
        damage: "220",
        affinity: "-30",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Brutal Strike",
    },
    {
        name: "Dual Threat II",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Sever//Average//Slow//Arc Shot//Wyvernsnipe",
        damage: "240",
        affinity: "-30",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Brutal Strike",
    },
    {
        name: "Kadachi Cannon I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "120",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Normal Effect I",
    },
    {
        name: "Kadachi Cannon II",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "160",
        affinity: "10",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Normal Effect I",
    },
    {
        name: "Kadachi Raijodo",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "200",
        affinity: "10",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Normal Effect I",
    },
    {
        name: "Rapidcaster I",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//Arc Shot//Wyvernheart",
        damage: "90",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Normal Effect I/Spread Effect I",
    },
    {
        name: "Rapidcaster II",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//Arc Shot//Wyvernheart",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Normal Effect II/Spread Effect I",
    },
    {
        name: "Cyclecaster",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//Arc Shot//Wyvernheart",
        damage: "160",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Normal Effect II/Spread Effect II",
    },
    {
        name: "Hidden Gambit I",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "110",
        affinity: "30",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Gambit II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "170",
        affinity: "30",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Baleful Night",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "190",
        affinity: "30",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
    },
    {
        name: "Highpriest Bowgun I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild//Some//Below Avg.//N/A//Wyvernsnipe",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Shrapnel Effect I/Silkbind Boost",
    },
    {
        name: "Highpriest Bowgun II",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild//Some//Below Avg.//N/A//Wyvernsnipe",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Shrapnel Effect I/Silkbind Boost",
    },
    {
        name: "Bishaten's Grace",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Mild//Some//Below Avg.//N/A//Wyvernsnipe",
        damage: "180",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Shrapnel Effect II/Silkbind Boost",
    },
    {
        name: "Spheniscine Slayer I",
        type: "HeavyBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernsnipe",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Pierce Effect I/Small Monster Exploit",
    },
    {
        name: "Spheniscine Slayer II",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernsnipe",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Pierce Effect I/Small Monster Exploit",
    },
    {
        name: "Spheniscine Ruler",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernsnipe",
        damage: "170",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Pierce Effect I/Normal Effect II",
    },
    {
        name: "Sinister Volley I",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//High//Fast//Arc Shot//Wyvernsnipe",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Cluster Effect I/Magnamalo Soul",
    },
    {
        name: "Sinister Volley II",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//High//Fast//Arc Shot//Wyvernsnipe",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Cluster Effect I/Magnamalo Soul",
    },
    {
        name: "Sinister Dreadvolley",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//High//Fast//Arc Shot//Wyvernsnipe",
        damage: "220",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Cluster Effect II/Magnamalo Soul",
    },
    {
        name: "Rajang Shooter I",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Average//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "190",
        affinity: "-20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Normal Effect I/Sticky Effect I/Brutal Strike",
    },
    {
        name: "Rajang Shooter II",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Average//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "210",
        affinity: "-20",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Normal Effect I/Sticky Effect I/Brutal Strike",
    },
    {
        name: "Azure Elder Cannon I",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Above Avg.//Arc Shot//Wyvernheart",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Pierce Effect I/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Cannon II",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Above Avg.//Arc Shot//Wyvernheart",
        damage: "200",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Pierce Effect I/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Thunderbolt Cannon I",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Some//Average//Arc Shot//Wyvernsnipe",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Carrozza Bazooka I",
        type: "HeavyBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Pierce Effect I/Spread Effect I/Shrapnel Effect I",
    },
    {
        name: "Carrozza Bazooka II",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Pierce Effect I/Spread Effect I/Shrapnel Effect I",
    },
    {
        name: "Cendrillon",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "180",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Pierce Effect II/Spread Effect I/Shrapnel Effect I",
    },
    {
        name: "Journey Jelly I",
        type: "HeavyBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R. Mild//Average//Above Avg.//N/A//Wyvernheart",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I/Normal Effect I",
    },
    {
        name: "Journey Jelly II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "R. Mild//Average//Above Avg.//N/A//Wyvernheart",
        damage: "170",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Normal Effect I",
    },
    {
        name: "Guiding Light",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "R. Mild//Average//Above Avg.//N/A//Wyvernheart",
        damage: "190",
        affinity: "0",
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Normal Effect I",
    },
    {
        name: "Ladybug Cannon I",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Slow//Arc Shot//Wyvernheart",
        damage: "160",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Pierce Effect I/Spread Effect I",
    },
    {
        name: "Ladybug Cannon II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Slow//Arc Shot//Wyvernheart",
        damage: "180",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Pierce Effect II/Spread Effect I",
    },
    {
        name: "Ladybug Morta",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Slow//Arc Shot//Wyvernheart",
        damage: "200",
        affinity: "0",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Pierce Effect I/Spread Effect I",
    },
    {
        name: "Felyne Bowgun I",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Below Avg.//Level Shot//Wyvernsnipe",
        damage: "160",
        affinity: "0",
        stringRampageSkills: "Attack Boost I/Spread Effect I/Cluster Effect I",
    },
    {
        name: "Felyne Bowgun II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Below Avg.//Level Shot//Wyvernsnipe",
        damage: "180",
        affinity: "0",
        stringRampageSkills:
            "Attack Boost II/Spread Effect II/Cluster Effect I",
    },
    {
        name: "Felyne Cannon",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Below Avg.//Level Shot//Wyvernsnipe",
        damage: "200",
        affinity: "0",
        stringRampageSkills:
            "Attack Boost III/Spread Effect II/Cluster Effect II",
    },
    {
        name: "Rampage H. Bowgun I",
        type: "HeavyBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Severe//Average//Below Avg.//N/A//Wyvernheart",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage H. Bowgun II",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Severe//Average//Below Avg.//N/A//Wyvernheart",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage H. Bowgun III",
        type: "HeavyBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Severe//Average//Below Avg.//N/A//Wyvernheart",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage H. Bowgun IV",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L. Severe//Average//Below Avg.//N/A//Wyvernheart",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage H. Bowgun V",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Severe//Average//Average//N/A//Wyvernheart",
        damage: "200",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Kamaeleon I",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Fast//Arc Shot//Wyvernsnipe",
        damage: "210",
        affinity: "30",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Defense Boost II/Spread Effect I/Chameleos Soul",
    },
    {
        name: "Teostra's Artillery I",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Average//Arc Shot//Wyvernsnipe",
        damage: "210",
        affinity: "5",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Sticky Effect I/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Daora's Delphinidae",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//Average//Fast//Arc Shot//Wyvernsnipe",
        damage: "210",
        affinity: "10",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Pierce Effect I/Kushala Daora Soul",
    },
    {
        name: "Diablazooka",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Severe//Average//Below Avg.//Arc Shot//Wyvernsnipe",
        damage: "250",
        affinity: "-30",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Brutal Strike",
    },
    {
        name: "Araknamortar",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Fast//Arc Shot//Wyvernsnipe",
        damage: "190",
        affinity: "40",
        stringRampageSkills: "Attack Boost IV/Pierce Effect I/Silkbind Boost",
    },
    {
        name: "Gnashing Flammenkanone",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Severe//High//Average//Arc Shot//Wyvernsnipe",
        damage: "230",
        affinity: "-20",
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Cluster Effect I/Brutal Strike",
    },
    {
        name: "Thorn Cannon",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Very Fast//N/A//Wyvernsnipe",
        damage: "200",
        affinity: "20",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Mountainous Roar",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Fast//N/A//Wyvernsnipe",
        damage: "210",
        affinity: "10",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Normal Effect I",
    },
    {
        name: "Tigrex Skull",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Average//Arc Shot//Wyvernheart",
        damage: "240",
        affinity: "-10",
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Sticky Effect I/Cluster Effect II",
    },
    {
        name: "Redwing Cannon I",
        type: "HeavyBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "--//Low//Very Fast//Arc Shot//Wyvernheart",
        damage: "200",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Abyssal Gale Barrage",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Fast//Arc Shot//Wyvernheart",
        damage: "210",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Barrage",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Some//Above Avg.//Arc Shot//Wyvernsnipe",
        damage: "200",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora Grande",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//Average//Fast//Arc Shot//Wyvernsnipe",
        damage: "220",
        affinity: "10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Diabolica",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Low//Very Fast//Arc Shot//Wyvernheart",
        damage: "210",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Normal Effect II/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rajang's Rage",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Average//Fast//Arc Shot//Wyvernsnipe",
        damage: "230",
        affinity: "-20",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Normal Effect II/Sticky Effect II/Brutal Strike",
    },
    {
        name: "Rampage H. Bowgun S",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Severe//Average//Average//--//Wyvernheart",
        damage: "210",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Teostra's Flames",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Average//Arc Shot//Wyvernheart",
        damage: "230",
        affinity: "5",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Sticky Effect II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Veiled Kamaeleon",
        type: "HeavyBowgun",
        rarity: "7",
        defenseIncrease: "30",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Fast//Arc Shot//Wyvernsnipe",
        damage: "220",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Defense Boost III/Spread Effect II/Chameleos Soul",
    },
];

export default heavyBowgunData;