let huntingHornData = [
    {
        name: "Kamura Chorus I",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "18",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
        melody: "Defense Up\n Attack Up\n Health Recovery (S)",
    },
    {
        name: "Kamura Chorus II",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
        melody: "Defense Up\n Attack Up\n Health Recovery (S)",
    },
    {
        name: "Kamura Chorus III",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "16",
        yellowSharpness: "22",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
        melody: "Defense Up\n Attack Up\n Health Recovery (S)",
    },
    {
        name: "Kamura Chorus IV",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "20",
        yellowSharpness: "18",
        greenSharpness: "5",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
        melody: "Defense Up\n Attack Up\n Health Recovery (S)",
    },
    {
        name: "Kamura Chorus V",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "19",
        yellowSharpness: "21",
        greenSharpness: "10",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Master Rider",
        melody: "Defense Up\n Attack Up\n Health Recovery (S) + Antidote",
    },
    {
        name: "Kamura Ninja Horn",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
        melody: "Defense Up\n Attack Up\n Health Recovery (S) + Antidote",
    },
    {
        name: "Poetic Bell I",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Water",
        elementalDamage: "20",
        affinity: "10",
        redSharpness: "13",
        orangeSharpness: "9",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
        melody: " Health Recovery (S)\n Blight Negated\n Stamina Use Reduced",
    },
    {
        name: "Poetic Bell II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Water",
        elementalDamage: "24",
        affinity: "10",
        redSharpness: "14",
        orangeSharpness: "20",
        yellowSharpness: "23",
        greenSharpness: "18",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Element Exploit",
        melody: " Health Recovery (S)\n Blight Negated\n Stamina Use Reduced",
    },
    {
        name: "Sublime Bell I",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Fire",
        elementalDamage: "24",
        affinity: "30",
        redSharpness: "45",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Silkbind Boost",
        melody: " Blight Negated\n Elemental Attack Boost\n Knockbacks Negated",
    },
    {
        name: "Sublime Bell II",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "26",
        affinity: "30",
        redSharpness: "45",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "10",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Fire Boost II/Silkbind Boost",
        melody: " Blight Negated\n Elemental Attack Boost\n Knockbacks Negated",
    },
    {
        name: "Araknahorn",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "29",
        affinity: "30",
        redSharpness: "47",
        orangeSharpness: "7",
        yellowSharpness: "10",
        greenSharpness: "7",
        blueSharpness: "10",
        whiteSharpness: "4",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Fire Boost II/Silkbind Boost",
        melody: "Blight Negated\n Elemental Attack Boost\n Knockbacks Negated",
    },
    {
        name: "Basarios Rock I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Fire",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "40",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Fire Boost I/Dulling Strike",
        melody: " Tremors Negated\n Sonic Barrier\n Stamina Use Reduced",
    },
    {
        name: "Basarios Rock Mk.II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "2",
        yellowSharpness: "43",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Fire Boost II/Dulling Strike",
        melody: " Tremors Negated\n Sonic Barrier\n Stamina Use Reduced",
    },
    {
        name: "Gigant Rock",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "7",
        yellowSharpness: "42",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Fire Boost III/Dulling Strike",
        melody: " Tremors Negated\n Sonic Barrier\n Stamina Use Reduced",
    },
    {
        name: "Usurper's Growl I",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "23",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-aquatic Species",
        melody: " Stun Negated\n Attack Up\n Knockbacks Negated",
    },
    {
        name: "Usurper's Growl II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "6",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-aquatic Species",
        melody: " Stun Negated\n Attack Up\n Knockbacks Negated",
    },
    {
        name: "Despot's Thunderclap",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "10",
        yellowSharpness: "28",
        greenSharpness: "24",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-aquatic Species",
        melody: " Stun Negated\n Attack Up\n Knockbacks Negated",
    },
    {
        name: "Zurogong Primo I",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "4",
        yellowSharpness: "8",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Defense Boost I/Small Monster Exploit",
        melody: " Attack Up\n Defense Up\n Sonic Barrier",
    },
    {
        name: "Zurogong Primo II",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "6",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost I/Small Monster Exploit",
        melody: " Attack Up\n Defense Up\n Sonic Barrier",
    },
    {
        name: "Zurogong Secundo",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "10",
        yellowSharpness: "35",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Small Monster Exploit",
        melody: " Attack Up\n Defense Up\n Sonic Barrier",
    },
    {
        name: "Striped Dragonga I",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "6",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Maximum Volume",
        melody: "Earplus (S)\n Attack Up\n Sonic Wave",
    },
    {
        name: "Striped Dragonga II",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "11",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "24",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Maximum Volume",
        melody: "Earplus (S)\n Attack Up\n Sonic Wave",
    },
    {
        name: "Tigrex Horn",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "12",
        orangeSharpness: "13",
        yellowSharpness: "16",
        greenSharpness: "30",
        blueSharpness: "7",
        whiteSharpness: "7",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Maximum Volume",
        melody: "Earplus (S)\n Attack Up\n Sonic Wave",
    },
    {
        name: "Bariguiro I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
        melody: " Stamina Recovery Up\n Health Recovery (S)\n Affinity Up",
    },
    {
        name: "Bariguiro II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "18",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "6",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
        melody: " Stamina Recovery Up\n Health Recovery (S)\n Affinity Up",
    },
    {
        name: "Algiguiro",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "16",
        yellowSharpness: "24",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
        melody: " Stamina Recovery Up\n Health Recovery (S)\n Affinity Up",
    },
    {
        name: "Frilled Flute I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Sleep",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "28",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Sleep Boost I/Dulling Strike",
        melody: " Attack Up\n Earplugs (S)\n Defense Up",
    },
    {
        name: "Frilled Flute II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Sleep",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "11",
        yellowSharpness: "25",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Sleep Boost I/Dulling Strike",
        melody: " Attack Up\n Earplugs (S)\n Defense Up",
    },
    {
        name: "Illusory Flute",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Sleep",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "28",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Sleep Boost I/Dulling Strike",
        melody: " Attack Up\n Earplugs (S)\n Defense Up",
    },
    {
        name: "Iron Horn I",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "70",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
        melody: " Sonic Wave\n Stamina Recovery Up\n Defense Up",
    },
    {
        name: "Wind Horn",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
        melody: " Sonic Wave\n Stamina Recovery Up\n Defense Up",
    },
    {
        name: "Metal Bagpipe I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
        melody: " Sonic Wave\n Stamina Recovery Up\n Defense Up",
    },
    {
        name: "Great Bagpipe",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "17",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
        melody: " Sonic Wave\n Stamina Recovery Up\n Defense Up",
    },
    {
        name: "Heavy Bagpipe I",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "12",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "21",
        yellowSharpness: "20",
        greenSharpness: "11",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Silkbind Boost",
        melody: " Sonic Wave\n Stamina Recovery Up\n Defense Up",
    },
    {
        name: "Fortissimo",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "22",
        yellowSharpness: "23",
        greenSharpness: "10",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Silkbind Boost",
        melody: " Sonic Wave\n Stamina Recovery Up\n Defense Up",
    },
    {
        name: "Hidden Harmonic I",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "24",
        orangeSharpness: "6",
        yellowSharpness: "15",
        greenSharpness: "24",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
        melody: " Stamina Recovery Up\n Attack Up\n Affinity Up",
    },
    {
        name: "Hidden Harmonic II",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "35",
        greenSharpness: "20",
        blueSharpness: "15",
        whiteSharpness: "5",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
        melody: " Stamina Recovery Up\n Attack Up\n Affinity Up",
    },
    {
        name: "Cry in the Night",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "25",
        greenSharpness: "22",
        blueSharpness: "17",
        whiteSharpness: "7",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
        melody: " Stamina Recovery Up\n Attack Up\n Affinity Up",
    },
    {
        name: "Pukei Bagpipe I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Poison",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "5",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I/Poison Boost I",
        melody: " Elemental Attack Boost\nStamina Recovery Up\n Health Regeneration",
    },
    {
        name: "Pukei Bagpipe II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "14",
        yellowSharpness: "15",
        greenSharpness: "21",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Poison Boost I",
        melody: " Elemental Attack Boost\nStamina Recovery Up\n Health Regeneration",
    },
    {
        name: "Datura Lurr",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "24",
        greenSharpness: "25",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Poison Boost I",
        melody: " Elemental Attack Boost\nStamina Recovery Up\n Health Regeneration",
    },
    {
        name: "Flammenkornett I",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "18",
        affinity: "-15",
        redSharpness: "33",
        orangeSharpness: "27",
        yellowSharpness: "6",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
        melody: " Stamina Recovery Up\n Health Recovery (S)\n Attack Up",
    },
    {
        name: "Flammenkornett II",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "-15",
        redSharpness: "30",
        orangeSharpness: "30",
        yellowSharpness: "4",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
        melody: " Stamina Recovery Up\n Health Recovery (S)\n Attack Up",
    },
    {
        name: "Forte Flammenkornett",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "-15",
        redSharpness: "28",
        orangeSharpness: "28",
        yellowSharpness: "6",
        greenSharpness: "15",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost III/Brutal Strike",
        melody: " Stamina Recovery Up\n Health Recovery (S)\n Attack Up",
    },
    {
        name: "Valkyrie Chordmaker I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "11",
        yellowSharpness: "24",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Fire Boost I/Small Monster Exploit",
        melody: "Defense Up\n Stamina Use Reduced\n Divine Protection",
    },
    {
        name: "Valkyrie Chordmaker II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Fire",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "12",
        yellowSharpness: "22",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Fire Boost I/Small Monster Exploit",
        melody: "Defense Up\n Stamina Use Reduced\n Divine Protection",
    },
    {
        name: "Queen Chordmaker",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "14",
        yellowSharpness: "21",
        greenSharpness: "20",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Fire Boost I/Small Monster Exploit",
        melody: "Defense Up\n Stamina Use Reduced\n Divine Protection",
    },
    {
        name: "Sandpipe I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "8",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "30",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Brutal Strike",
        melody: " Defense Up\n Sonic Wave\n Stamina Use Reduced",
    },
    {
        name: "Sandpipe II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "8",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "16",
        orangeSharpness: "16",
        yellowSharpness: "27",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost II/Brutal Strike",
        melody: " Defense Up\n Sonic Wave\n Stamina Use Reduced",
    },
    {
        name: "Sandcrier",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "31",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Brutal Strike",
        melody: " Defense Up\n Sonic Wave\n Stamina Use Reduced",
    },
    {
        name: "Frog Flute I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Water",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost I/Dulling Strike",
        melody: " Health Recovery (S)\n Attack Up\n Tremors Negated",
    },
    {
        name: "Frog Flute II",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "21",
        yellowSharpness: "26",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost I/Dulling Strike",
        melody: " Health Recovery (S)\n Attack Up\n Tremors Negated",
    },
    {
        name: "Amphibia Allargando",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Water",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "21",
        yellowSharpness: "26",
        greenSharpness: "21",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost III/Dulling Strike",
        melody: " Health Recovery (S)\n Attack Up\n Tremors Negated",
    },
    {
        name: "Wind Thief Horn I",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "11",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
        melody: " Stamina Recovery Up\n Affinity Up\n Health Recovery (S)",
    },
    {
        name: "Wind Thief Horn II",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "19",
        orangeSharpness: "11",
        yellowSharpness: "16",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Buddy Rally",
        melody: " Stamina Recovery Up\n Affinity Up\n Health Recovery (S)",
    },
    {
        name: "Gale Horn",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "7",
        greenSharpness: "18",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Buddy Rally",
        melody: " Stamina Recovery Up\n Affinity Up\n Health Recovery (S)",
    },
    {
        name: "Droth Drone I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Water",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost /Water Boost I/Waterblight Exploit",
        melody: " Blight Negated\n Defense Up\n Sonic Wave",
    },
    {
        name: "Droth Drone II",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Water",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "19",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost/Water Boost I/Waterblight Exploit",
        melody: " Blight Negated\n Defense Up\n Sonic Wave",
    },
    {
        name: "Droth Roar",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "20",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/Waterblight Exploit",
        melody: " Blight Negated\n Defense Up\n Sonic Wave",
    },
    {
        name: "Bone Horn I",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "21",
        yellowSharpness: "9",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
        melody: " Environment Damage Negated\n Defense Up\n Attack Up",
    },
    {
        name: "Bone Horn II",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
        melody: " Environment Damage Negated\n Defense Up\n Attack Up",
    },
    {
        name: "Hardened Bone Horn",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
        melody: " Environment Damage Negated\n Defense Up\n Attack Up",
    },
    {
        name: "Hunter's Horn I",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
        melody: " Environment Damage Negated\n Divine Protection\n Attack Up",
    },
    {
        name: "Native's Horn",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "29",
        yellowSharpness: "4",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Dulling Strike",
        melody: " Environment Damage Negated\n Divine Protection\n Attack Up",
    },
    {
        name: "Duo Horn I",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "24",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Brutal Strike",
        melody: " Defense Up\n Stamina Use Reduced\n Earplugs (L)",
    },
    {
        name: "Duo Horn II",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "20",
        orangeSharpness: "14",
        yellowSharpness: "20",
        greenSharpness: "27",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Brutal Strike",
        melody: " Defense Up\n Stamina Use Reduced\n Earplugs (L)",
    },
    {
        name: "Bull Grunt I",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-5",
        redSharpness: "15",
        orangeSharpness: "23",
        yellowSharpness: "25",
        greenSharpness: "4",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Dulling Strike/Maximum Volume",
        melody: "Divine Protection\n Knockacks Negated\n Stun Negated",
    },
    {
        name: "Bull Grunt II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-5",
        redSharpness: "16",
        orangeSharpness: "19",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Dulling Strike/Maximum Volume",
        melody: "Divine Protection\n Knockacks Negated\n Stun Negated",
    },
    {
        name: "Wild Grunt",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-5",
        redSharpness: "19",
        orangeSharpness: "21",
        yellowSharpness: "25",
        greenSharpness: "14",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Dulling Strike/Maximum Volume",
        melody: "Divine Protection\n Knockacks Negated\n Stun Negated",
    },
    {
        name: "Flame Feroce I",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Fire",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "19",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
        melody: " Elemental Attack Boost\n Sonic Wave\n Stamina Recovery Up",
    },
    {
        name: "Flame Feroce II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "21",
        yellowSharpness: "19",
        greenSharpness: "21",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
        melody: " Elemental Attack Boost\n Sonic Wave\n Stamina Recovery Up",
    },
    {
        name: "Rathalos Feroce",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "22",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
        melody: " Elemental Attack Boost\n Sonic Wave\n Stamina Recovery Up",
    },
    {
        name: "Kulu Mosso I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Spiribird Doubled",
        melody: " Defense Up\n Stamina Recovery Up\n Stun Negated",
    },
    {
        name: "Kulu Mosso II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "15",
        orangeSharpness: "16",
        yellowSharpness: "9",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Spiribird Doubled",
        melody: " Defense Up\n Stamina Recovery Up\n Stun Negated",
    },
    {
        name: "Kulu Grosso",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "25",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "13",
        greenSharpness: "22",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Spiribird Doubled",
        melody: " Defense Up\n Stamina Recovery Up\n Stun Negated",
    },
    {
        name: "Khezu Horn I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "6",
        yellowSharpness: "26",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
        melody: " Earplugs (S)\n Health Regeneration\n Elemental Attack Boost",
    },
    {
        name: "Khezu Horn II",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "9",
        yellowSharpness: "30",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Thunder Boost I/Thunderblight Exploit",
        melody: " Earplugs (S)\n Health Regeneration\n Elemental Attack Boost",
    },
    {
        name: "Khezu Flute",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Thunder",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "9",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
        melody: " Earplugs (S)\n Health Regeneration\n Elemental Attack Boost",
    },
    {
        name: "Vicello Nulo I",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Silkbind Boost",
        melody: " Health Recovery (S)\n Stamina Use Reduced\n Earplugs (S)",
    },
    {
        name: "Vicello Nulo II",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "7",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Silkbind Boost",
        melody: " Health Recovery (S)\n Stamina Use Reduced\n Earplugs (S)",
    },
    {
        name: "Vicello Unu",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "5",
        yellowSharpness: "8",
        greenSharpness: "17",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Silkbind Boost",
        melody: " Health Recovery (S)\n Stamina Use Reduced\n Earplugs (S)",
    },
    {
        name: "Vicello Nulo Black I",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "6",
        yellowSharpness: "6",
        greenSharpness: "15",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost II/Silkbind Boost",
        melody: " Health Recovery (S)\n Stamina Use Reduced\n Earplugs (L)",
    },
    {
        name: "Vicello Nulo Black II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "17",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost III/Silkbind Boost",
        melody: " Health Recovery (S)\n Stamina Use Reduced\n Earplugs (L)",
    },
    {
        name: "Vicello Uno Black",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Dragon",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "37",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "20",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Dragon Boost III/Silkbind Boost",
        melody: " Health Recovery (S)\n Stamina Use Reduced\n Earplugs (L)",
    },
    {
        name: "Vicello Nulo Green I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Paralysis",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "10",
        yellowSharpness: "6",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Paralysis Boost I/Silkbind Boost",
        melody: " Defense Up\n Tremors Negated\n Health Recovery (S)",
    },
    {
        name: "Vicello Nulo Green II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Paralysis",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "18",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Paralysis Boost I/Silkbind Boost",
        melody: " Defense Up\n Tremors Negated\n Health Recovery (S)",
    },
    {
        name: "Vicello Unu Green",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Paralysis",
        elementalDamage: "21",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "10",
        yellowSharpness: "4",
        greenSharpness: "20",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Paralysis Boost I/Silkbind Boost",
        melody: " Defense Up\n Tremors Negated\n Health Recovery (S)",
    },
    {
        name: "Vicello Nulo White I",
        type: "HuntingHorn",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "8",
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "2",
        yellowSharpness: "5",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost I/Silkbind Boost",
        melody: " Health Regeneration\n Stamina Use Reduced\n Sonic Wave",
    },
    {
        name: "Vicello Nulo White II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Ice",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "5",
        yellowSharpness: "7",
        greenSharpness: "18",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Ice Boost II/Silkbind Boost",
        melody: " Health Regeneration\n Stamina Use Reduced\n Sonic Wave",
    },
    {
        name: "Vicello Unu White",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "19",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Ice Boost III/Silkbind Boost",
        melody: " Health Regeneration\n Stamina Use Reduced\n Sonic Wave",
    },
    {
        name: "Sinister Strum I",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Blast",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "37",
        orangeSharpness: "4",
        yellowSharpness: "10",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
        melody: " Sonic Barrier\n Attack and Defense Up\n Health Regeneration",
    },
    {
        name: "Sinister Strum II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
        melody: " Sonic Barrier\n Attack and Defense Up\n Health Regeneration",
    },
    {
        name: "Sinister Shadestrum",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Blast",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "4",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
        melody: " Sonic Barrier\n Attack and Defense Up\n Health Regeneration",
    },
    {
        name: "Denden Daiko I",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "6",
        orangeSharpness: "10",
        yellowSharpness: "35",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Thunder Boost I/Dulling Strike/Maximum Volume",
        melody: " Attack and Defense Up\n Environment Damage Negated\n Tremors Negated",
    },
    {
        name: "Denden Daiko II",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "17",
        affinity: "-10",
        redSharpness: "6",
        orangeSharpness: "11",
        yellowSharpness: "43",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Thunder Boost I/Dulling Strike/Maximum Volume",
        melody: " Attack and Defense Up\n Environment Damage Negated\n Tremors Negated",
    },
    {
        name: "Azure Elder Horn I",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "9",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "10",
        blueSharpness: "24",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
        melody: " Stamina Use Reduced\n Divine Protection\n Sonic Barrier",
    },
    {
        name: "Azure Elder Horn II",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Dragon",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
        melody: " Stamina Use Reduced\n Divine Protection\n Sonic Barrier",
    },
    {
        name: "Thunderbolt Horn I",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "45",
        greenSharpness: "10",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
        melody: " Stun Negated\n Health Recovery (L)\n Health Regeneration",
    },
    {
        name: "Rookslayer Drum I",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "15",
        orangeSharpness: "22",
        yellowSharpness: "15",
        greenSharpness: "23",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Maximum Volume",
        melody: "Earplugs (S)\n Attack Up\n Health Recovery (L)",
    },
    {
        name: "Rookslayer Drum II",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "16",
        affinity: "-10",
        redSharpness: "15",
        orangeSharpness: "26",
        yellowSharpness: "24",
        greenSharpness: "20",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Maximum Volume",
        melody: "Earplugs (S)\n Attack Up\n Health Recovery (L)",
    },
    {
        name: "Bazelreid Rookslayer",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Blast",
        elementalDamage: "18",
        affinity: "-10",
        redSharpness: "15",
        orangeSharpness: "26",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Blast Boost III/Maximum Volume",
        melody: "Earplugs (S)\n Attack Up\n Health Recovery (L)",
    },
    {
        name: "Daora's Taus I",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "32",
        affinity: "10",
        redSharpness: "12",
        orangeSharpness: "14",
        yellowSharpness: "33",
        greenSharpness: "16",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
        melody: " Environment Damage Negated\n Stamina Use Reduced\nSharpness Loss Reduced",
    },
    {
        name: "Teostra's Tiple I",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "17",
        yellowSharpness: "20",
        greenSharpness: "32",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
        melody: " Health Regeneration\n Health Recovery (S) + Antidote\n Attsack and Defense Up",
    },
    {
        name: "Blessed Ocarina I",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Poison",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "42",
        orangeSharpness: "6",
        yellowSharpness: "15",
        greenSharpness: "17",
        blueSharpness: "5",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
        melody: " Earplugs (L)\n Wind Pressure Negated\n Elemental Attack Boost",
    },
    {
        name: "Poison Fungasax I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Poison",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "14",
        yellowSharpness: "35",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dulling Strike/Spiribird Doubled",
        melody: " Stamina Use Reduced\n Health Recovery (S)\n Defense Up",
    },
    {
        name: "Poison Fungasax II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Poison",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "15",
        yellowSharpness: "40",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dulling Strike/Spiribird Doubled",
        melody: " Stamina Use Reduced\n Health Recovery (S)\n Defense Up",
    },
    {
        name: "Toxic Fungasax",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Poison",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "16",
        yellowSharpness: "34",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Dulling Strike/Spiribird Doubled",
        melody: " Stamina Use Reduced\n Health Recovery (S)\n Defense Up",
    },
    {
        name: "Magia Charm I",
        type: "HuntingHorn",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Ice",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "6",
        yellowSharpness: "25",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Ice Boost I/Dulling Strike/Silkbind Boost",
        melody: " Health Recovery (S)\n Sonic Barrier\n Health Recovery (S) + Antidote",
    },
    {
        name: "Magia Charm II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "14",
        yellowSharpness: "25",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Ice Boost I/Dulling Strike/Silkbind Boost",
        melody: " Health Recovery (S)\n Sonic Barrier\n Health Recovery (S) + Antidote",
    },
    {
        name: "Magia Charm III",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "26",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Ice Boost I/Dulling Strike/Silkbind Boost",
        melody: " Health Recovery (S)\n Sonic Barrier\n Health Recovery (S) + Antidote",
    },
    {
        name: "Magia Charmbell",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "25",
        greenSharpness: "30",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Ice Boost III/Dulling Strike/Silkbing Boost",
        melody: " Health Recovery (S)\n Sonic Barrier\n Health Recovery (S) + Antidote",
    },
    {
        name: "Cornupion I",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Paralysis",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "9",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Paralysis Boost I/Silkbind Boost",
        melody: " Health Recovery (S) + Antidote\n Defense Up\n Affinity Up",
    },
    {
        name: "Cornupion II",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Paralysis",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "6",
        yellowSharpness: "24",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Paralysis Boost I/Silkbind Boost",
        melody: " Health Recovery (S) + Antidote\n Defense Up\n Affinity Up",
    },
    {
        name: "Webbed Cornupion",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Paralysis",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "11",
        yellowSharpness: "20",
        greenSharpness: "23",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Paralysis Boost I/Silkbind Boost",
        melody: " Health Recovery (S) + Antidote\n Defense Up\n Affinity Up",
    },
    {
        name: "Grass Flute I",
        type: "HuntingHorn",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost I/Dulling Strike",
        melody: " Wind Pressure Negated\n Health Regeneration\n Sonic Barrier",
    },
    {
        name: "Grass Flute II",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Blast",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Blast Boost II/Dulling Strike",
        melody: " Wind Pressure Negated\n Health Regeneration\n Sonic Barrier",
    },
    {
        name: "Bombadgy's Cry",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "30",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost I/Dulling Strike",
        melody: " Wind Pressure Negated\n Health Regeneration\n Sonic Barrier",
    },
    {
        name: "Rampage Agitato I",
        type: "HuntingHorn",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
        melody: " Earplugs (S)\n Health Recovery (S)\n Sonic Wave",
    },
    {
        name: "Rampage Agitato II",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
        melody: " Earplugs (S)\n Health Recovery (S)\n Sonic Wave",
    },
    {
        name: "Rampage Agitato III",
        type: "HuntingHorn",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "6",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
        melody: " Earplugs (S)\n Health Recovery (S)\n Sonic Wave",
    },
    {
        name: "Rampage Agitato IV",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "6",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
        melody: " Earplugs (S)\n Health Recovery (S)\n Sonic Wave",
    },
    {
        name: "Rampage Agitato V",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "17",
        yellowSharpness: "12",
        greenSharpness: "12",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
        melody: " Earplugs (S)\n Health Recovery (S)\n Sonic Wave",
    },
    {
        name: "Summoning Bell",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Water",
        elementalDamage: "28",
        affinity: "15",
        redSharpness: "15",
        orangeSharpness: "8",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Element Exploit",
        melody: " Health Recovery (S)\n Blight Negated\n Stamina Use Reduced",
    },
    {
        name: "Redwing Flute I",
        type: "HuntingHorn",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Dragon",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
        melody: " Elemental Attack Boost\n Attack and Affinity Up\n Sonic Wave",
    },
    {
        name: "Abyssal Gale Horn",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
        melody: " Stamina Use Reduced\n Divine Protection\n Sonic Barrier",
    },
    {
        name: "Abyssal Storm Horn",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "41",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "50",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
        melody: " Stun Negated\n Health Recovery (L)\n Health Regeneration",
    },
    {
        name: "Cursed Ocarina",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
        melody: " Earplugs (L)\n Wind Pressure Negated\n Elemental Attack Boost",
    },
    {
        name: "Daora's Baphophone",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "35",
        affinity: "10",
        redSharpness: "14",
        orangeSharpness: "18",
        yellowSharpness: "25",
        greenSharpness: "8",
        blueSharpness: "6",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
        melody: " Environment Damage Negated\n Stamina Use Reduced\n Sharpness Loss Reduced",
    },
    {
        name: "Denden Doomsounder",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "-10",
        redSharpness: "7",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Thunder Boost II/Dulling Strike/Maximum Volume",
        melody: " Attack and Defense Up\n Environment Damage Negated\n Tremors Negated",
    },
    {
        name: "Duo Risoluto",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "18",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Brutal Strike",
        melody: "Defense Up\n Stamina Use Reduced\n Earplugs (L)",
    },
    {
        name: "Teostra's Orphee",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "42",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "18",
        yellowSharpness: "18",
        greenSharpness: "25",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
        melody: " Health Regeneration\n Health Recovery (S) + Antidote\n Attack and Defense Up",
    },
    {
        name: "Reddnaught Ritmico",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
        melody: " Environment Attack Boost\n Attack and Affinity Up\n Sonic Wave",
    },
    {
        name: "Rampage Agitato S",
        type: "HuntingHorn",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
        melody: " Earplugs (S)\n Health Recovery (S)\n Sonic Wave",
    },
];

export default huntingHornData;