let insectGlaiveData = [
    {
        name: "Kamura Glaive I",
        type: "InsectGlaive",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "1",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Glaive II",
        type: "InsectGlaive",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "1",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Glaive III",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "13",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Glaive IV",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "18",
        greenSharpness: "8",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Glaive V",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "17",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Glaive",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Hidden Scythe I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "10",
        orangeSharpness: "17",
        yellowSharpness: "18",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Scythe II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "24",
        orangeSharpness: "6",
        yellowSharpness: "15",
        greenSharpness: "25",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Evening Calm",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "17",
        orangeSharpness: "10",
        yellowSharpness: "28",
        greenSharpness: "21",
        blueSharpness: "16",
        whiteSharpness: "8",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
    },
    {
        name: "Fox Halberd I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "120",
        elementType: "Water",
        elementalDamage: "12",
        affinity: "10",
        redSharpness: "26",
        orangeSharpness: "9",
        yellowSharpness: "7",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity I/Water Boost I",
    },
    {
        name: "Fox Halberd II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "170",
        elementType: "Water",
        elementalDamage: "16",
        affinity: "10",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "17",
        greenSharpness: "11",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity II/Water Boost II",
    },
    {
        name: "Frilled Jab I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "110",
        elementType: "Sleep",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "12",
        yellowSharpness: "29",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Frilled Jab II",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "120",
        elementType: "Sleep",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "13",
        yellowSharpness: "29",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Illusory Frilled Jab",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "190",
        elementType: "Sleep",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "20",
        yellowSharpness: "30",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Tigrex Kaina I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "16",
        orangeSharpness: "7",
        yellowSharpness: "24",
        greenSharpness: "24",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Tigrex Kaina II",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "11",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tigerclaw Glaive",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "11",
        orangeSharpness: "9",
        yellowSharpness: "30",
        greenSharpness: "30",
        blueSharpness: "13",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Leaping Glaive I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "2",
        damage: "100",
        elementType: "Water",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "17",
        yellowSharpness: "19",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost I/Dulling Strike",
    },
    {
        name: "Leaping Glaive II",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "20",
        phialOrShellingType: "4",
        damage: "160",
        elementType: "Water",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost II/Dulling Strike",
    },
    {
        name: "Leapfrog",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "20",
        phialOrShellingType: "7",
        damage: "210",
        elementType: "Water",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost III/Dulling Strike",
    },
    {
        name: "Iron Blade I",
        type: "InsectGlaive",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "1",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "15",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Iron Blade II",
        type: "InsectGlaive",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "1",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "11",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Steel Blade",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "19",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Iron Bayonet I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "17",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Iron Bayonet II",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "19",
        yellowSharpness: "14",
        greenSharpness: "11",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Hiten Blade",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "19",
        yellowSharpness: "10",
        greenSharpness: "12",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Rathmaul I",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "19",
        yellowSharpness: "20",
        greenSharpness: "23",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Rathmaul II",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "7",
        yellowSharpness: "32",
        greenSharpness: "22",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Firedance Rathmaul",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "1",
        yellowSharpness: "17",
        greenSharpness: "25",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Bolt Chamber I",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "150",
        elementType: "Thunder",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "19",
        greenSharpness: "19",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Bolt Chamber II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "19",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Full Bolt Chamber",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "16",
        yellowSharpness: "21",
        greenSharpness: "25",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Princess Regalia I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "110",
        elementType: "Poison",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "19",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Princess Regalia II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit\n",
    },
    {
        name: "Queen Regalia",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "210",
        elementType: "Poison",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "20",
        yellowSharpness: "16",
        greenSharpness: "30",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Aknosom Pike I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Aknosom Pike II",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "110",
        elementType: "Fire",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "20",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Daybreak Glaive",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "12",
        yellowSharpness: "28",
        greenSharpness: "13",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Fire Boost II/Fire Blight Exploit",
    },
    {
        name: "Kulu Glaive I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Kinsect Level Boost/Spiribird Doubled",
    },
    {
        name: "Kulu Glaive II",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Kinsect Level Boost/Spiribird Doubled",
    },
    {
        name: "Kulu Pike",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "14",
        orangeSharpness: "18",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost III/Kinsect Level Boost/Spiribird Doubled",
    },
    {
        name: "Kadachi Glaive I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "12",
        affinity: "10",
        redSharpness: "30",
        orangeSharpness: "7",
        yellowSharpness: "11",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Thunder Boost II",
    },
    {
        name: "Kadachi Glaive II",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "140",
        elementType: "Thunder",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "30",
        orangeSharpness: "5",
        yellowSharpness: "9",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Thunder Boost II",
    },
    {
        name: "Shocking Pike",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "22",
        affinity: "10",
        redSharpness: "24",
        orangeSharpness: "20",
        yellowSharpness: "7",
        greenSharpness: "7",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Thunder Boost III",
    },
    {
        name: "Lagombaglaive I",
        type: "InsectGlaive",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "12",
        yellowSharpness: "25",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Ice Boost II/Small Monster Exploit",
    },
    {
        name: "Lagombaglaive II",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "23",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost II/Dulling Strike",
    },
    {
        name: "Lagombavarice",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "9",
        yellowSharpness: "19",
        greenSharpness: "20",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost II/Dulling Strike",
    },
    {
        name: "Bone Staff I",
        type: "InsectGlaive",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "20",
        yellowSharpness: "9",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Staff II",
        type: "InsectGlaive",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "15",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Aerial Glaive",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "8",
        yellowSharpness: "13",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Sturdy Glaive I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Sturdy Glaive II",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Sturdy Glaive Redux",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "14",
        greenSharpness: "16",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Sky-High Glaive I",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "130",
        elementType: "Paralysis",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "14",
        yellowSharpness: "28",
        greenSharpness: "7",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Silkbind Boost/Anti-Aerial Species",
    },
    {
        name: "Sky-High Glaive II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "150",
        elementType: "Paralysis",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "7",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Silkbind Boost/Anti-Aerial Species",
    },
    {
        name: "Highest of Glaives",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "170",
        elementType: "Paralysis",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "5",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Silkbind Boost/Anti-Aerial Species",
    },
    {
        name: "Diablos Rod I",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "43",
        orangeSharpness: "7",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost I/Kinsect Level Boost",
    },
    {
        name: "Diablos Rod II",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "43",
        orangeSharpness: "7",
        yellowSharpness: "16",
        greenSharpness: "9",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost II/Kinsect Level Boost",
    },
    {
        name: "Flammenkaefer I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "12",
        affinity: "-15",
        redSharpness: "23",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flammenkaefer II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "15",
        affinity: "-15",
        redSharpness: "33",
        orangeSharpness: "16",
        yellowSharpness: "19",
        greenSharpness: "9",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
    },
    {
        name: "Gnashing Flammenkaefer",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "220",
        elementType: "Fire",
        elementalDamage: "18",
        affinity: "-15",
        redSharpness: "30",
        orangeSharpness: "14",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost III/Brutal Strike",
    },
    {
        name: "Gossglaive I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "10",
        affinity: "-20",
        redSharpness: "21",
        orangeSharpness: "7",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost I/Brutal Strike",
    },
    {
        name: "Gossglaive II",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "210",
        elementType: "Ice",
        elementalDamage: "12",
        affinity: "-20",
        redSharpness: "21",
        orangeSharpness: "9",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost II/Brutal Strike",
    },
    {
        name: "Abominable Glaive",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "230",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "-20",
        redSharpness: "21",
        orangeSharpness: "9",
        yellowSharpness: "25",
        greenSharpness: "8",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Ice Boost III/Brutal Strike",
    },
    {
        name: "Pukei Rod I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "100",
        elementType: "Poison",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "26",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dulling Strike/Poison Boost I",
    },
    {
        name: "Pukei Rod II",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "150",
        elementType: "Poison",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "26",
        orangeSharpness: "19",
        yellowSharpness: "16",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dulling Strike/Poison Boost I",
    },
    {
        name: "Datura Pike",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "19",
        yellowSharpness: "16",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dulling Strike/Poison Boost II",
    },
    {
        name: "Amber Piton I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "16",
        affinity: "15",
        redSharpness: "11",
        orangeSharpness: "12",
        yellowSharpness: "18",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Amber Piton II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "22",
        affinity: "15",
        redSharpness: "11",
        orangeSharpness: "9",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Fenrir Storm",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "25",
        affinity: "15",
        redSharpness: "11",
        orangeSharpness: "17",
        yellowSharpness: "20",
        greenSharpness: "24",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Royal Bloom I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "2",
        damage: "80",
        elementType: "Water",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "14",
        yellowSharpness: "25",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/ Waterblight Exploit",
    },
    {
        name: "Royal Bloom II",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "130",
        elementType: "Water",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "29",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/ Waterblight Exploit",
    },
    {
        name: "Bloom Royale",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "160",
        elementType: "Water",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "5",
        yellowSharpness: "19",
        greenSharpness: "20",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/ Waterblight Exploit",
    },
    {
        name: "Royal Bolt Scepter I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "21",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Royal Bolt Scepter II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "8",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "16",
        greenSharpness: "23",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Despot's Twinbolt",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "8",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "24",
        greenSharpness: "24",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Hortadent I",
        type: "InsectGlaive",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "19",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Kinsect Level Boost/Small Monster Exploit",
    },
    {
        name: "Hortadent II",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "12",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Kinsect Level Boost/Small Monster Exploit",
    },
    {
        name: "Hortadent Brada",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "19",
        yellowSharpness: "21",
        greenSharpness: "9",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost IV/Kinsect Level Boost/Small Monster Exploit",
    },
    {
        name: "Rielle Nulo I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "28",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Silkbind Boost",
    },
    {
        name: "Rielle Nulo II",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "7",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Silkbind Boost",
    },
    {
        name: "Rielle Unu",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "28",
        orangeSharpness: "5",
        yellowSharpness: "7",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Silkbind Boost",
    },
    {
        name: "Rielle Nulo Red I",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "9",
        yellowSharpness: "7",
        greenSharpness: "14",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost II/Silkbind Boost",
    },
    {
        name: "Rielle Nulo Red II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "9",
        yellowSharpness: "5",
        greenSharpness: "14",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost II/Silkbind Boost",
    },
    {
        name: "Rielle Vermiglio",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "8",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "9",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Fire Boost III/Silkbind Boost",
    },
    {
        name: "Rielle Nulo Black I",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "140",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "9",
        yellowSharpness: "7",
        greenSharpness: "14",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost II/Silkbind Boost",
    },
    {
        name: "Rielle Nulo Black II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "9",
        yellowSharpness: "5",
        greenSharpness: "14",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost II/Silkbind Boost",
    },
    {
        name: "Rielle Nerissimo",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "8",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "9",
        yellowSharpness: "5",
        greenSharpness: "9",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Dragon Boost III/Silkbind Boost",
    },
    {
        name: "Rielle Nulo White I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "120",
        elementType: "Ice",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "28",
        orangeSharpness: "5",
        yellowSharpness: "7",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Ice Boost II/Silkbind Boost",
    },
    {
        name: "Rielle Nulo White II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "4",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Ice Boost II/Silkbind Boost",
    },
    {
        name: "Rielle Unu White",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "8",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "9",
        yellowSharpness: "5",
        greenSharpness: "9",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Ice Boost III/Silkbind Boost",
    },
    {
        name: "Rielle Nulo Green I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "100",
        elementType: "Paralysis",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "28",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Paralysis Boost I/SilkBind Boost",
    },
    {
        name: "Rielle Nulo Green II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "130",
        elementType: "Paralysis",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "9",
        yellowSharpness: "7",
        greenSharpness: "13",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost II/Paralysis Boost I/SilkBind Boost",
    },
    {
        name: "Rielle Unu Green",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "170",
        elementType: "Paralysis",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "9",
        yellowSharpness: "5",
        greenSharpness: "9",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Paralysis Boost I/SilkBind Boost",
    },
    {
        name: "Sinister Staff I",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "5",
        yellowSharpness: "9",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Staff II",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "21",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Shadowstaff",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Metal Mauler I",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "10",
        yellowSharpness: "28",
        greenSharpness: "18",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Metal Mauler II",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "7",
        yellowSharpness: "35",
        greenSharpness: "22",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Azure Elder Glaive I",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Glaive II",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "13",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Glaive I",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "45",
        greenSharpness: "9",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora's Entom I",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "25",
        yellowSharpness: "27",
        greenSharpness: "15",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost I/Kushala Daora Soul",
    },
    {
        name: "Caster's Rod I",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "31",
        yellowSharpness: "10",
        greenSharpness: "25",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Deathport Staff I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "4",
        damage: "100",
        elementType: "Dragon",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "9",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dragon Boost I/Dragon Exploit",
    },
    {
        name: "Deathport Staff II",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "15",
        phialOrShellingType: "5",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "24",
        yellowSharpness: "9",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Garamorse",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "7",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "24",
        yellowSharpness: "14",
        greenSharpness: "23",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Magia Pitareen I",
        type: "InsectGlaive",
        rarity: "2",
        defenseIncrease: "5",
        phialOrShellingType: "3",
        damage: "70",
        elementType: "Blast",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "27",
        orangeSharpness: "8",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I/Silkbind Boost",
    },
    {
        name: "Magia Pitareen II",
        type: "InsectGlaive",
        rarity: "3",
        defenseIncrease: "5",
        phialOrShellingType: "4",
        damage: "100",
        elementType: "Blast",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "28",
        orangeSharpness: "9",
        yellowSharpness: "18",
        greenSharpness: "2",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Silkbind Boost",
    },
    {
        name: "Magia Pitareen III",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "5",
        phialOrShellingType: "5",
        damage: "150",
        elementType: "Blast",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "28",
        orangeSharpness: "12",
        yellowSharpness: "15",
        greenSharpness: "13",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost IV/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Magia Crescent",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "5",
        phialOrShellingType: "8",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "17",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Brush Glaive I",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "4",
        damage: "200",
        elementType: "Water",
        elementalDamage: "8",
        affinity: "-10",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "22",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Water Boost II/Dulling Strike/Master Rider",
    },
    {
        name: "Brush Glaive II",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "210",
        elementType: "Water",
        elementalDamage: "9",
        affinity: "-10",
        redSharpness: "14",
        orangeSharpness: "19",
        yellowSharpness: "29",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Water Boost III/Dulling Strike/Master Rider",
    },
    {
        name: "Watercolor Glaive",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "220",
        elementType: "Water",
        elementalDamage: "10",
        affinity: "-10",
        redSharpness: "9",
        orangeSharpness: "14",
        yellowSharpness: "29",
        greenSharpness: "14",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Water Boost IV/Dulling Strike/Master Rider",
    },
    {
        name: "Rampage Glaive I",
        type: "InsectGlaive",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "16",
        yellowSharpness: "5",
        greenSharpness: "22",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Glaive II",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "19",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Glaive III",
        type: "InsectGlaive",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "16",
        yellowSharpness: "19",
        greenSharpness: "8",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Glaive IV",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "16",
        yellowSharpness: "17",
        greenSharpness: "7",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Glaive V",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "3 ",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "17",
        yellowSharpness: "11",
        greenSharpness: "10",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Curved Naganagi",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "190",
        elementType: "Water",
        elementalDamage: "20",
        affinity: "15",
        redSharpness: "20",
        orangeSharpness: "14",
        yellowSharpness: "16",
        greenSharpness: "12",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Water Boost II",
    },
    {
        name: "Redwing Glaive",
        type: "InsectGlaive",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Abyssal Gale Glaive",
        type: "InsectGlaive",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Glaive",
        type: "InsectGlaive",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "8",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "50",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora's Tethidine",
        type: "InsectGlaive",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "7",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Ice Boost II/Kushala Daora Soul",
    },
    {
        name: "Hazy Caster",
        type: "InsectGlaive",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "25",
        yellowSharpness: "8",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Metalmangler",
        type: "InsectGlaive",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "220",
        elementType: "Thunder",
        elementalDamage: "22",
        affinity: "-20",
        redSharpness: "20",
        orangeSharpness: "8",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Tyrant Rod",
        type: "InsectGlaive",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "6",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "8",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Kinsect Level Boost",
    },
    {
        name: "Reddnaught Shuma",
        type: "InsectGlaive",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "5",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rampage Glaive S",
        type: "InsectGlaive",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "3",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
];

export default insectGlaiveData;