let lanceData = [
    {
        name: "Kamura Spear I",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Spear II",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Spear III",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Spear IV",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Spear V",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Spear",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Goss Lance I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "10",
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost I/Brutal Strike",
    },
    {
        name: "Goss Lance II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Ice",
        elementalDamage: "12",
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost II/Brutal Strike",
    },
    {
        name: "Abominable Lance",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "Ice",
        elementalDamage: "14",
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Ice Boost III/Brutal Strike",
    },
    {
        name: "Hana Mo Hana Nare I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Water14",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
    },
    {
        name: "Hana Mo Hana Nare II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water20",
        affinity: "10",
        redSharpness: "25",
        orangeSharpness: "25",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Kimi Ga Kiru",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Water28",
        affinity: "15",
        redSharpness: "25",
        orangeSharpness: "25",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "15",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Water Boost II",
    },
    {
        name: "Naag Serpentblade I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Poison",
        elementalDamage: "26",
        affinity: "5",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Poison Boost I/Dulling Strike",
    },
    {
        name: "Naag Serpentblade II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Poison",
        elementalDamage: "31",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Poison Boost I/Dulling Strike",
    },
    {
        name: "Devta Serpentblade",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Poison",
        elementalDamage: "41",
        affinity: "10",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Poison Boost I/Dulling Strike",
    },
    {
        name: "Distension I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Water",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost I/Dulling Strike",
    },
    {
        name: "Distension II",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Water Boost III/Dulling Strike",
    },
    {
        name: "Croaker",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Water",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Water Boost III/Dulling Strike",
    },
    {
        name: "Wind Thief Lance I",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "70",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Wind Thief Lance II",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "5",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Gale Lance",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Sharktooth Spear I",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost I/Master Rider/Small Monster Exploit",
    },
    {
        name: "Sharktooth Spear II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Ice",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Master Rider/Small Monster Exploit",
    },
    {
        name: "Razortooth Spear",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Ice",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Master Rider/Element Exploit",
    },
    {
        name: "Iron Lance I",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Iron Lance II",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Millennial Lance",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Paladin Lance I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Silkbind Boost",
    },
    {
        name: "Paladin Lance II",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Silkbind Boost",
    },
    {
        name: "Rampart",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Silkbind Boost",
    },
    {
        name: "Babel Spear I",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "30",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dragon Exploit",
    },
    {
        name: "Babel Spear II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "40",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dragon Exploit",
    },
    {
        name: "Elder Babel Spear",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "7",
        yellowSharpness: "43",
        greenSharpness: "22",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Defense Boost III/Dragon Exploit",
    },
    {
        name: "Venom Lance I",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "14",
        affinity: "-15",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Poison Boost I/Dulling Strike",
    },
    {
        name: "Venom Lance II",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Poison",
        elementalDamage: "20",
        affinity: "-15",
        redSharpness: "20",
        orangeSharpness: "25",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Poison Boost I/Dulling Strike",
    },
    {
        name: "Basarios Venom Spear",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Poison",
        elementalDamage: "23",
        affinity: "-15",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Poison Boost II/Dulling Strike",
    },
    {
        name: "Hidden Stinger I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Stinger II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "15",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Night Rains Black",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "35",
        redSharpness: "16",
        orangeSharpness: "10",
        yellowSharpness: "27",
        greenSharpness: "22",
        blueSharpness: "17",
        whiteSharpness: "8",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
    },
    {
        name: "Growling Wyvern I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Element Exploit",
    },
    {
        name: "Growling Wyvern II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Element Exploit",
    },
    {
        name: "Roaring Wyvern",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost IV/Defense Boost III/Element Exploit",
    },
    {
        name: "Kadachi Lance I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "13",
        affinity: "10",
        redSharpness: "30",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost I/Thunderblight Exploit",
    },
    {
        name: "Kadachi Lance II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "15",
        redSharpness: "30",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Thunderblight Exploit",
    },
    {
        name: "Shockspear",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "15",
        redSharpness: "35",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Thunderblight Exploit",
    },
    {
        name: "Aknosom Lance I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Aknosom Lance II",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Fire",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Aknosom Lance III",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "13",
        blueSharpness: "2",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost II/Fireblight Exploit",
    },
    {
        name: "Dawnbreaker Lance",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "40",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Fire Boost III/Fireblight Exploit",
    },
    {
        name: "Rugged Lance I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "30",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost I/Brutal Strike",
    },
    {
        name: "Rugged Lance II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "40",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost II/Brutal Strike",
    },
    {
        name: "Barroth Carver",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "45",
        greenSharpness: "12",
        blueSharpness: "3",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Brutal Strike",
    },
    {
        name: "Drill Lance I",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "8",
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Element Exploit",
    },
    {
        name: "Drill Lance II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "11",
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "30",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Element Exploit",
    },
    {
        name: "Gigadrill Lance",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "15",
        affinity: "10",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "38",
        blueSharpness: "2",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost IV/Defense Boost III/Element Exploit",
    },
    {
        name: "Volvi Stroke I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Paralysis",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Dulling Strike",
    },
    {
        name: "Volvi Stroke II",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Paralysis",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost II/Dulling Strike",
    },
    {
        name: "Volvi Sweep",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Paralysis",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Defense Boost II/Dulling Strike",
    },
    {
        name: "Heat Lance I",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Fire",
        elementalDamage: "9",
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Dulling Strike",
    },
    {
        name: "Heat Lance II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Dulling Strike",
    },
    {
        name: "Heatstinger",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "17",
        affinity: "-10",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost IV/Defense Boost III/Dulling Strike",
    },
    {
        name: "Bone Lance I",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Hard Bone Lance",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Longhorn Spear I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Longtusk Spear",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "22",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "3",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Barbarian Tusk I",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Barbarian Fang",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Tiger Stinger I",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "10",
        orangeSharpness: "5",
        yellowSharpness: "30",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tiger Stinger II",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tusk Lance I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "30",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Tusk Lance II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "24",
        affinity: "35",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Sabertooth",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "26",
        affinity: "40",
        redSharpness: "12",
        orangeSharpness: "17",
        yellowSharpness: "21",
        greenSharpness: "25",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost III/Iceblight Exploit",
    },
    {
        name: "Pukei Spear I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Poison",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I/Poison Boost I",
    },
    {
        name: "Pukei Spear II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Poison Boost II",
    },
    {
        name: "Datura Spear",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Poison Boost II",
    },
    {
        name: "Red Tail I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Spear of Prominence",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "10",
        yellowSharpness: "29",
        greenSharpness: "29",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Red Tail II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Spiral Lance I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Water",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Spiral Lance II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Water",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Spiral Splash",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "31",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Ploshasta I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "5",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost I/Brutal Strike/Small Monster Exploit",
    },
    {
        name: "Ploshasta II",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Brutal Strike/Small Monster Exploit",
    },
    {
        name: "Rhenoshasta",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Brutal Strike/Small Monster Exploit",
    },
    {
        name: "Diablos Lance I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Brutal Strike",
    },
    {
        name: "Diablos Lance II",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "5",
        greenSharpness: "30",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Brutal Strike",
    },
    {
        name: "Diablos Spear",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "250",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-30",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "30",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Brutal Strike",
    },
    {
        name: "Kulu Spear I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Master Rider/Spiribird Doubled",
    },
    {
        name: "Kulu Spear II",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Master Rider/Spiribird Doubled",
    },
    {
        name: "Kulu Skewer",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "25",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Affinity Boost II/Master Rider/Spiribird Doubled",
    },
    {
        name: "Usurper's Coming I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Coming II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "21",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot's Cacophony",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "25",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Azure Crest I",
        type: "Lance",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "70",
        elementType: "Sleep",
        elementalDamage: "9",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinty Boost I/Sleep Boost I/Buddy Rally",
    },
    {
        name: "Azure Crest II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Sleep",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Sleep Boost I/Buddy Rally",
    },
    {
        name: "Azure Crest III",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Sleep",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Sleep Boost II/Buddy Rally",
    },
    {
        name: "Great Azure",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Sleep",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "5",
        yellowSharpness: "25",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Sleep Boost II/Buddy Rally",
    },
    {
        name: "Sinister Spear I",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Spear II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Shadespear",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Demon Lance I",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "5",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "5",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Demon Lance II",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "7",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Azure Elder Spear I",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "6",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "20",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Spear II",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Dragon",
        elementalDamage: "9",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "25",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Spear I",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "45",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial/Species",
    },
    {
        name: "Rookslayer Lance I",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "10",
        affinity: "-10",
        redSharpness: "18",
        orangeSharpness: "15",
        yellowSharpness: "18",
        greenSharpness: "22",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Brutal Strike",
    },
    {
        name: "Rookslayer Lance II",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Blast",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "20",
        orangeSharpness: "18",
        yellowSharpness: "18",
        greenSharpness: "18",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Brutal Strike",
    },
    {
        name: "Bazel Myniad Lance",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "20",
        orangeSharpness: "18",
        yellowSharpness: "18",
        greenSharpness: "16",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Blast Boost III/Brutal Strike",
    },
    {
        name: "Icesteel Spear I",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "30",
        affinity: "10",
        redSharpness: "16",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "22",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Teostra's Howl I",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "25",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Plegis Needle I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Paralysis",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Paralysis Boost I/Dulling Strike/Spiribird Doubled",
    },
    {
        name: "Plegis Needle II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Paralysis",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "35",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Paralysis Boost I/Dulling Strike/Spiribird Doubled",
    },
    {
        name: "Mighty Plegis",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Paralysis",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "50",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Paralysis Boost I/Dulling Strike/Spiribird Double",
    },
    {
        name: "Alacrantze I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Poison",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Poison Boost I/Silkbind Boost",
    },
    {
        name: "Alacrantze II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Poison",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Poison Boost I/Silkbind Boost",
    },
    {
        name: "Alacrantze III",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Poison",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Poison Boost I/Silkbind Boost",
    },
    {
        name: "Scorpion Lance",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "29",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "35",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost III/Poison Boost I/Silkbind Boost",
    },
    {
        name: "Fragrance I",
        type: "Lance",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Sleep",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "28",
        orangeSharpness: "2",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Sleep Boost I/Anti-Aquatic Species",
    },
    {
        name: "Fragrance II",
        type: "Lance",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Sleep",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Sleep Boost II/Anti-Aquatic Species",
    },
    {
        name: "Classy Fragrance",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Sleep",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Sleep Boost III/Anti-Aquatic Species",
    },
    {
        name: "Rampage Spear I",
        type: "Lance",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Spear II",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "18",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Spear III",
        type: "Lance",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Spear IV",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "10",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Spear V",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "18",
        yellowSharpness: "12",
        greenSharpness: "12",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Redwing Spear I",
        type: "Lance",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Abyssal Gale Lance",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Lance",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "50",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Daora's Fang",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "36",
        affinity: "10",
        redSharpness: "17",
        orangeSharpness: "19",
        yellowSharpness: "15",
        greenSharpness: "8",
        blueSharpness: "6",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Great Demon Lance",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Thunder",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "13",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "22",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Tigrex Lance",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "13",
        orangeSharpness: "13",
        yellowSharpness: "26",
        greenSharpness: "24",
        blueSharpness: "15",
        whiteSharpness: "4",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Teostra's Roar",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "12",
        yellowSharpness: "8",
        greenSharpness: "18",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Reddnaught Spear",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rampage Spear S",
        type: "Lance",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
];

export default lanceData;