let lightBowgunData = [
    {
        name: "Kamura L. Bowgun I",
        type: "LightBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernblast",
        damage: "50",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura L. Bowgun II",
        type: "LightBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernblast",
        damage: "60",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura L. Bowgun III",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernblast",
        damage: "90",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura L. Bowgun IV",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernblast",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura L. Bowgun V",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernblast",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja L. Bowgun",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Hidden Eye I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Avergage//Above Avg.//N/A//Wyvernblast",
        damage: "100",
        affinity: "35",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Eye II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Avergage//Above Avg.//N/A//Wyvernblast",
        damage: "160",
        affinity: "35",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Night Owl",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Avergage//Above Avg.//N/A//Wyvernblast",
        damage: "180",
        affinity: "40",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
    },
    {
        name: "Lumier Bowgun I",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernblast",
        damage: "160",
        affinity: "30",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Spread Effect II/Silkbind Boost",
    },
    {
        name: "Lumier Bowgun II",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Above Avg.//N/A//Wyvernblast",
        damage: "170",
        affinity: "30",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Spread Effect II/Silkbind Boost",
    },
    {
        name: "Araknabolt",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Fast//Arc Shot//Wyvernblast",
        damage: "180",
        affinity: "35",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost III/Spread Effect II/Silkbind Boost",
    },
    {
        name: "Lotus Bowgun I",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Some//Below Avg.//Arc Shot//Wyvernblast",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Shrapnel Effect I/Silkbind Boost",
    },
    {
        name: "Lotus Bowgun II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Some//Below Avg.//Arc Shot//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Shrapnel Effect I/Silkbind Boost",
    },
    {
        name: "Great Lotus Bowgun",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Some//Below Avg.//Arc Shot//Wyvernblast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Shrapnel Effect II/Silkbind Boost",
    },
    {
        name: "Khezu Syringe I",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//N/A//Wyvernblast",
        damage: "80",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Spread Effect I/Thunderblight Exploit",
    },
    {
        name: "Khezu Syringe II",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//N/A//Wyvernblast",
        damage: "90",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Spread Effect I/Thunderblight Exploit",
    },
    {
        name: "Khezu Syringe III",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//N/A//Wyvernblast",
        damage: "140",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Spread Effect II/Thunderblight Exploit",
    },
    {
        name: "Khezu Hypo",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//N/A//Wyvernblast",
        damage: "160",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Spread Effect II/Thunderblight Exploit",
    },
    {
        name: "Shotgun (Viper) I",
        type: "LightBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//N/A//Wyvernblast",
        damage: "70",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Shotgun (Viper) II",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//N/A//Wyvernblast",
        damage: "80",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Shotgun (Viper) III",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//N/A//Wyvernblast",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Bullet Rain (Viper)",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//N/A//Wyvernblast",
        damage: "140",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost III/Defense Boost II",
    },
    {
        name: "Barro Barrel I",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Slow//Arc Shot//Wyvernblast",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost I/Pierce Effect I",
    },
    {
        name: "Barro Barrel II",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Slow//Arc Shot//Wyvernblast",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost II/Pierce Effect I",
    },
    {
        name: "Barro Blaster",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Slow//Arc Shot//Wyvernblast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost II/Pierce Effect I",
    },
    {
        name: "Gossgun I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Low//Very Slow//N/A//Wyvernblast",
        damage: "160",
        affinity: "-15",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Pierce Effect I/Brutal Strike",
    },
    {
        name: "Gossgun II",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Low//Very Slow//N/A//Wyvernblast",
        damage: "170",
        affinity: "-15",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Pierce Effect I/Brutal Strike",
    },
    {
        name: "Gossgun III",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Low//Very Slow//N/A//Wyvernblast",
        damage: "190",
        affinity: "-15",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Pierce Effect II/Brutal Strike",
    },
    {
        name: "Abominable Bowgun",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Low//Very Slow//N/A//Wyvernblast",
        damage: "220",
        affinity: "-15",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Pierce Effect II/Brutal Strike",
    },
    {
        name: "Hunter's Rifle I",
        type: "LightBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "70",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Hunter's Rifle II",
        type: "LightBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "90",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Sniper Shot",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Jaeger I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Average//N/A//Wyvernblast",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Dragon Exploit",
    },
    {
        name: "Jaeger II",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Average//N/A//Wyvernblast",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Dragon Exploit",
    },
    {
        name: "Jaeger Prime",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Average//N/A//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Dragon Exploit",
    },
    {
        name: "Usurper's Crime I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "120",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper's Crime II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "170",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot's Wildfire",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "190",
        affinity: "10",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Pierce Effect II/Anti-Aquatic",
    },
    {
        name: "Almudron Bowgun I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//N/A//Wyvernblast",
        damage: "140",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Normal Effect II/Element Exploit",
    },
    {
        name: "Almudron Bowgun II",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//N/A//Wyvernblast",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Normal Effect II/Element Exploit",
    },
    {
        name: "Doom Bringer Bowgun",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Some//Below Avg.//N/A//Wyvernblast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Normal Effect II/Element Exploit",
    },
    {
        name: "Scale Tornado I",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Pierce Effect I/Fireblight Exploit",
    },
    {
        name: "Scale Tornado II",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Pierce Effect I/Fireblight Exploit",
    },
    {
        name: "Uroktor Vortex",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Average//Below Avg.//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Pierce Effect I/Fireblight Exploit",
    },
    {
        name: "Desolate Mist I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Low//Average//Arc Shot//Wyvernblast",
        damage: "110",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Sticky Effect I",
    },
    {
        name: "Desolate Mist II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Low//Average//Arc Shot//Wyvernblast",
        damage: "160",
        affinity: "10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Sticky Effect I",
    },
    {
        name: "Nifl Mist",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Low//Above Avg.//Arc Shot//Wyvernblast",
        damage: "170",
        affinity: "10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Sticky Effect I",
    },
    {
        name: "Wind Thief L. Bowgun I",
        type: "LightBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernblast",
        damage: "70",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Wind Thief L. Bowgun II",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernblast",
        damage: "80",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Wind Thief L. Bowgun III",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernblast",
        damage: "140",
        affinity: "15",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Gale Bowgun",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernblast",
        damage: "160",
        affinity: "15",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Flammenkanone I",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "200",
        affinity: "-30",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Cluster Effect I/Brutal Strike",
    },
    {
        name: "Flammenkanone II",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "220",
        affinity: "-30",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Cluster Effect I/Brutal Strike",
    },
    {
        name: "Furious Flammenkanone",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "230",
        affinity: "-30",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Cluster Effect I/Brutal Strike",
    },
    {
        name: "Valkyrie Fire I",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernblast",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Pierce Effect I/Small Monster Exploit",
    },
    {
        name: "Valkyrie Fire II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernblast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Pierce Effect I/Small Monster Exploit",
    },
    {
        name: "Valkyrie Blaze",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Pierce Effect I/Small Monster Exploit",
    },
    {
        name: "Cross Bowgun I",
        type: "LightBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernblast",
        damage: "80",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Cross Bowgun II",
        type: "LightBowgun",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernblast",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Cross Blitz",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//High//Average//Arc Shot//Wyvernblast",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affiinity Boost II/Defense Boost I",
    },
    {
        name: "Yakt Shooter I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernblast",
        damage: "110",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Silkbind Boost",
    },
    {
        name: "Yakt Shooter II",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernblast",
        damage: "150",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Silkbind Boost",
    },
    {
        name: "Wyvern Chaser",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernblast",
        damage: "170",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Silkbind Boost",
    },
    {
        name: "Wishing Star I",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Below Avg.//N/A//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Defense Boost II/Normal Effect I",
    },
    {
        name: "Wishing Star II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Defense Boost III/Normal Effect II",
    },
    {
        name: "Comet Bolt",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "200",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost III/Normal Effect II",
    },
    {
        name: "Rathling Gun I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernblast",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Shrapnel Effect I/Element Exploit",
    },
    {
        name: "Rathling Gun II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//Arc Shot//Wyvernblast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Shrapnel Effect I/Element Exploit",
    },
    {
        name: "Rathling Phoenix",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Shrapnel Effect I/Element Exploit",
    },
    {
        name: "Blizzard Cannon I",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernblast",
        damage: "80",
        affinity: "15",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Blizzard Cannon II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Above Avg.//N/A//Wyvernblast",
        damage: "150",
        affinity: "20",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Blizzard Volley",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//N/A//Wyvernblast",
        damage: "170",
        affinity: "25",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Grenade Launcher I",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//Arc Shot//Wyvernblast",
        damage: "90",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Grenade Launcher II",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//Arc Shot//Wyvernblast",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Grenade Launcher III",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//Arc Shot//Wyvernblast",
        damage: "160",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Grenade Revolver",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Cluster Effect I",
    },
    {
        name: "Tigrex Tank I",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//Average//Average//Arc Shot//Wyvernblast",
        damage: "200",
        affinity: "-20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Tigrex Tank II",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//Average//Above Avg.//Arc Shot//Wyvernblast",
        damage: "210",
        affinity: "-20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Royal Launcher I",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "100",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Spread Effect I/Waterblight Exploit",
    },
    {
        name: "Royal Launcher II",
        type: "LightBowgun",
        rarity: "2",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Spread Effect I/Waterblight Exploit",
    },
    {
        name: "Royal Torrent",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Average//N/A//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Spread Effect II/Waterblight Exploit",
    },
    {
        name: "Sinister Bowgun I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//High//Fast//Arc Shot//Wyvernblast",
        damage: "120",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Cluster Effect I/Magnamalo Soul",
    },
    {
        name: "Sinister Bowgun II",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//High//Fast//Arc Shot//Wyvernblast",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Cluster Effect I/Magnamalo Soul",
    },
    {
        name: "Sinsiter Shadow Bolt",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//High//Fast//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Cluster Effect I/Magnamalo Soul",
    },
    {
        name: "Rajang Barrage I",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Average//Average//Arc Shot//Wyvernblast",
        damage: "180",
        affinity: "-15",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Brutal Strike/Master Rider",
    },
    {
        name: "Rajang Barrage II",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Average//Average//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "-15",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Brutal Strike/Master Rider",
    },
    {
        name: "Azure Elder Bowgun I",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Above Avg.//Arc Shot//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Normal Effect I/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Bowgun II",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Above Avg.//Arc Shot//Wyvernblast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Normal Effect II/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Bowgun I",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Some//Average//Arc Shot//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Rookslayer Bowgun I",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Some//Below Avg.//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "-10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Shrapnel Effect I/Brutal Strike",
    },
    {
        name: "Rookslayer Bowgun II",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Some//Below Avg.//Arc Shot//Wyvernblast",
        damage: "200",
        affinity: "-10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Shrapnel Effect I/Brutal Strike",
    },
    {
        name: "Bazelfetter Rookslayer",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Mild//Some//Below Avg.//Arc Shot//Wyvernblast",
        damage: "210",
        affinity: "-10",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Shrapnel Effect II/Brutal Strike",
    },
    {
        name: "Icesteel Wasp I",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//Low //Average//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Teostra's Dart I",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Severe//Average//Average//Arc Shot//Wyvernblast",
        damage: "190",
        affinity: "5",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Blessed Lamp I",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "None//Average//Fast//Arc Shot//Wyvernblast",
        damage: "180",
        affinity: "20",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Wooden Dog Bowgun I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Master Rider/Buddy Rally",
    },
    {
        name: "Wooden Dog Bowgun II",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "140",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Master Rider/Buddy Rally",
    },
    {
        name: "Watchdog's Howl",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Below Avg.//N/A//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Master Rider/Buddy Rally",
    },
    {
        name: "Springnight Shot I",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Some//Average//Arc Shot//Wyvernblast",
        damage: "110",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Anti-Aquatic Species/Small Monster Exploit",
    },
    {
        name: "Springnight Shot II",
        type: "LightBowgun",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Some//Average//Arc Shot//Wyvernblast",
        damage: "130",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Anti-Aquatic Species/Small Monster Exploit",
    },
    {
        name: "Springnight Spawn",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Some//Average//Arc Shot//Wyvernblast",
        damage: "160",
        affinity: "0",
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost III/Anti-Aquatic Species/Small Monster Exploit",
    },
    {
        name: "Rampage L. Bowgun I",
        type: "LightBowgun",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Below Avg.//N/A//Wyvernblast",
        damage: "140",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage L. Bowgun II",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Below Avg.//N/A//Wyvernblast",
        damage: "150",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage L. Bowgun III",
        type: "LightBowgun",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Below Avg.//N/A//Wyvernblast",
        damage: "160",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage L. Bowgun IV",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Below Avg.//N/A//Wyvernblast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage L. Bowgun V",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Average//N/A//Wyvernablast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Redwing Shooter I",
        type: "LightBowgun",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "--//Low//Very Fast//Arc Shot//Wyvernablast",
        damage: "160",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Abyssal Gale Bolt",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Average//Fast//Arc Shot//Wyvernablast",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Normal Effect II/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Bolt",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Some//Above Avg.//Arc Shot//Wyvernablast",
        damage: "180",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Cursed Lamp",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "--//Average//Fast//Arc Shot//Wyvernablast",
        damage: "190",
        affinity: "20",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Daora's Hornet",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Mild//Low//Average//Arc Shot//Wyvernablast",
        damage: "200",
        affinity: "10",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Tigrex Wargun",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Mild//Average//Above Avg.//Arc Shot//Wyvernablast",
        damage: "220",
        affinity: "-20",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Ten Thousand Volts",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "LR Severe//Average//Above Avg.//Arc Shot//Wyvernablast",
        damage: "210",
        affinity: "-15",
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Brutal Strike/Master Rider",
    },
    {
        name: "Teostra's Flamebolt",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "L Severe//Average//Average//Arc Shot//Wyvernablast",
        damage: "200",
        affinity: "5",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Reddnaught Bowgun",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "--//Low//Very Fast//Arc Shot//Wyvernablast",
        damage: "170",
        affinity: "0",
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rampage L.Bowgun S",
        type: "LightBowgun",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        bowGunSpecs: "R Severe//Average//Average//N/A//Wyvernablast",
        damage: "190",
        affinity: "0",
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
];

export default lightBowgunData;