let longSwordData = [
    {
        name: "Kamura Blade I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "19",
        yellowSharpness: "13",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I",
    },
    {
        name: "Kamura Blade II",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "13",
        orangeSharpness: "19",
        yellowSharpness: "19",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost I",
    },
    {
        name: "Kamura Blade III",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "14",
        yellowSharpness: "19",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II",
    },
    {
        name: "Kamura Blade IV",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "14",
        yellowSharpness: "17",
        greenSharpness: "6",
        blueSharpness: "4",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Blade V",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "17",
        yellowSharpness: "19",
        greenSharpness: "7",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Blade",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "18",
        yellowSharpness: "13",
        greenSharpness: "11",
        blueSharpness: "9",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Usurper Boltslicer I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Usurper Boltslicer II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "3",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "7",
        yellowSharpness: "23",
        greenSharpness: "16",
        blueSharpness: "7",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-Aquatic Species",
    },
    {
        name: "Despot Boltbreaker",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "9",
        yellowSharpness: "28",
        greenSharpness: "19",
        blueSharpness: "8",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-Aquatic Species",
    },
    {
        name: "Aknosom Sabre I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "11",
        yellowSharpness: "18",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Aknosom Sabre II",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "11",
        yellowSharpness: "28",
        greenSharpness: "7",
        blueSharpness: "4",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Daybreak Blade",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "11",
        yellowSharpness: "28",
        greenSharpness: "18",
        blueSharpness: "5",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost II/Fireblight Exploit",
    },
    {
        name: "Ivory Rabbit I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Ice",
        elementalDamage: "10",
        affinity: "-10",
        redSharpness: "17",
        orangeSharpness: "17",
        yellowSharpness: "13",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost I/Small Monster Exploit",
    },
    {
        name: "Ivory Rabbit II",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Ice",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "21",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Ice Boost II/Small Monster Exploit",
    },
    {
        name: "Iced Rabbit",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "13",
        orangeSharpness: "7",
        yellowSharpness: "34",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost II/Dulling Strike",
    },
    {
        name: "Guardian Sword I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "5",
        redSharpness: "21",
        orangeSharpness: "18",
        yellowSharpness: "18",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Guardian Sword II",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "5",
        redSharpness: "13",
        orangeSharpness: "18",
        yellowSharpness: "12",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Imperial Sword",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "10",
        orangeSharpness: "11",
        yellowSharpness: "17",
        greenSharpness: "19",
        blueSharpness: "11",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Castello Saif I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "13",
        yellowSharpness: "30",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Brutal Strike",
    },
    {
        name: "Castello Saif II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "16",
        orangeSharpness: "13",
        yellowSharpness: "30",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost II/Brutal Strike",
    },
    {
        name: "Castellum Long Sword",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "12",
        yellowSharpness: "30",
        greenSharpness: "20",
        blueSharpness: "3",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Brutal Strike",
    },
    {
        name: "Gigant Makra I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Fire",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "23",
        orangeSharpness: "18",
        yellowSharpness: "15",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Fire Boost I/Dulling Strike",
    },
    {
        name: "Gigant Makra II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Fire",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "26",
        orangeSharpness: "23",
        yellowSharpness: "16",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Fire Boost II/Dulling Strike",
    },
    {
        name: "Titanic Makra",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "26",
        orangeSharpness: "18",
        yellowSharpness: "21",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Fire Boost III/Dulling Strike",
    },
    {
        name: "Almudron Blade I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Water",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "11",
        yellowSharpness: "23",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Water Boost I/Element Exploit",
    },
    {
        name: "Almudron Blade II",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        elementalDamage: "41",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "18",
        greenSharpness: "13",
        blueSharpness: "8",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost I/Element Exploit",
    },
    {
        name: "Doom Bringer Blade",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Water",
        elementalDamage: "48",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "18",
        greenSharpness: "21",
        blueSharpness: "13",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost I/Element Exploit",
    },
    {
        name: "Iron Katana I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost II",
    },
    {
        name: "Iron Katana II",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "13",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost II",
    },
    {
        name: "Iron Gospel",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "13",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Keen Edge I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "16",
        yellowSharpness: "9",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbind Boost",
    },
    {
        name: "Keen Edge II",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "23",
        orangeSharpness: "20",
        yellowSharpness: "21",
        greenSharpness: "10",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbind Boost",
    },
    {
        name: "Julienne Blade",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "21",
        yellowSharpness: "18",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Bost/Silkbind Boost",
    },
    {
        name: "Tigrine Edge I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "16",
        orangeSharpness: "7",
        yellowSharpness: "23",
        greenSharpness: "21",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Tigrine Edge II",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "12",
        orangeSharpness: "9",
        yellowSharpness: "32",
        greenSharpness: "22",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Tigrine Need",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "30",
        blueSharpness: "10",
        whiteSharpness: "5",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost III/Brutal Strike",
    },
    {
        name: "Kakaru Kumo Naki I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Water",
        elementalDamage: "16",
        affinity: "10",
        redSharpness: "16",
        orangeSharpness: "10",
        yellowSharpness: "8",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
    },
    {
        name: "Kakaru Kumo Naki II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Water",
        elementalDamage: "19",
        affinity: "10",
        redSharpness: "25",
        orangeSharpness: "23",
        yellowSharpness: "19",
        greenSharpness: "4",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Hidden Saber I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "30",
        redSharpness: "12",
        orangeSharpness: "17",
        yellowSharpness: "18",
        greenSharpness: "23",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Master Rider",
    },
    {
        name: "Hidden Saber II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "35",
        redSharpness: "15",
        orangeSharpness: "16",
        yellowSharpness: "8",
        greenSharpness: "27",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost I/Master Rider",
    },
    {
        name: "Deepest Night",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "18",
        orangeSharpness: "11",
        yellowSharpness: "25",
        greenSharpness: "21",
        blueSharpness: "18",
        whiteSharpness: "7",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Affinity Boost II/Master Rider",
    },
    {
        name: "Eager Cleaver I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "11",
        yellowSharpness: "11",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Thunder Boost I/Dulling Strike/Thunderblight Exploit",
    },
    {
        name: "Eager Cleaver II",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Thunder",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "9",
        yellowSharpness: "22",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Thunder Boos/Dulling Strike/Thunderblight Exploit",
    },
    {
        name: "Devil Slicer",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "11",
        yellowSharpness: "21",
        greenSharpness: "22",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Thunder Boost II/Dulling Strike/Thunderblight Exploit",
    },
    {
        name: "Kulu Katana I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "16",
        orangeSharpness: "11",
        yellowSharpness: "6",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Spiribird Doubled",
    },
    {
        name: "Kulu Katana II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "19",
        orangeSharpness: "15",
        yellowSharpness: "8",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Spiribird Doubled",
    },
    {
        name: "Kulu Slicer",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "20",
        redSharpness: "19",
        orangeSharpness: "19",
        yellowSharpness: "17",
        greenSharpness: "12",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Spiribird Doubled",
    },
    {
        name: "Chillblade I",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "14",
        greenSharpness: "10",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost I/Silkbind Boost",
    },
    {
        name: "Chillblade II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "10",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost II/Silkbind Boost",
    },
    {
        name: "Rimeblossom",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Ice",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "17",
        orangeSharpness: "17",
        yellowSharpness: "17",
        greenSharpness: "9",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Ice Boost II/Silkbind Boost",
    },
    {
        name: "Wyvern Blade Verde I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Poison",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "19",
        yellowSharpness: "12",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Wyvern Blade Verde II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "19",
        yellowSharpness: "18",
        greenSharpness: "13",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Wyvern Blade Holly",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Poison",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "23",
        orangeSharpness: "21",
        yellowSharpness: "16",
        greenSharpness: "16",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Wyvern Blade Blood I",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "3",
        yellowSharpness: "9",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Wyvern Blade Blood II",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Fire",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "3",
        yellowSharpness: "11",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Wyvern Blade Maple",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "50",
        orangeSharpness: "2",
        yellowSharpness: "2",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Serrated Jaw I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "21",
        yellowSharpness: "9",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Serrated Jaw II",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Serrated Maw",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "21",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Canine Katana I",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "14",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Canine Katana II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "26",
        yellowSharpness: "5",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Gnash Katana",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "28",
        yellowSharpness: "5",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Flammenschwert I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "11",
        affinity: "-20",
        redSharpness: "23",
        orangeSharpness: "18",
        yellowSharpness: "9",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flammenschwert II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "-20",
        redSharpness: "23",
        orangeSharpness: "18",
        yellowSharpness: "13",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
    },
    {
        name: "Fervid Flammenschwert",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "230",
        elementType: "Fire",
        elementalDamage: "24",
        affinity: "-20",
        redSharpness: "24",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "14",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost III/Brutal Strike",
    },
    {
        name: "Bastine Edge I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "30",
        redSharpness: "8",
        orangeSharpness: "10",
        yellowSharpness: "15",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Bastine Edge II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Ice",
        elementalDamage: "19",
        affinity: "30",
        redSharpness: "7",
        orangeSharpness: "14",
        yellowSharpness: "15",
        greenSharpness: "23",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Bastizan Edge",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "27",
        affinity: "35",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "10",
        whiteSharpness: "3",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Wroggi Sword I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Poison",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "8",
        yellowSharpness: "9",
        greenSharpness: "4",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Poison Boost I/Buddy Rally",
    },
    {
        name: "Wroggi Sword II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "Poison",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "14",
        yellowSharpness: "10",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Poison Boost I/Buddy Rally",
    },
    {
        name: "Poison Barb",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Poison",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "15",
        yellowSharpness: "13",
        greenSharpness: "17",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Poison Boost II/Buddy Rally",
    },
    {
        name: "Ananta Blade I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "80",
        elementType: "Paralysis",
        elementalDamage: "9",
        affinity: "0",
        redSharpness: "21",
        orangeSharpness: "7",
        yellowSharpness: "8",
        greenSharpness: "3",
        blueSharpness: "1",
        whiteSharpness: 0,
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Paralysis Boost I/Buddy Rally",
    },
    {
        name: "Ananta Blade II",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Paralysis",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "4",
        yellowSharpness: "9",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Paralysis Boost I/Buddy Rally",
    },
    {
        name: "Shadow Slasher",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Paralysis",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "22",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Paralysis Boost II/Buddy Rally",
    },
    {
        name: "Bone Scythe I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost I",
    },
    {
        name: "Bone Scythe II",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "26",
        orangeSharpness: "4",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost I",
    },
    {
        name: "Bone Reaper",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "22",
        orangeSharpness: "4",
        yellowSharpness: "17",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Defense Boost II",
    },
    {
        name: "Spark Slicer I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "19",
        affinity: "10",
        redSharpness: "30",
        orangeSharpness: "6",
        yellowSharpness: "12",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Thunder Boost II",
    },
    {
        name: "Spark Slicer II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Thunder",
        elementalDamage: "21",
        affinity: "10",
        redSharpness: "25",
        orangeSharpness: "14",
        yellowSharpness: "18",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Thunder Boost II",
    },
    {
        name: "Shocking Slicer",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "24",
        affinity: "15",
        redSharpness: "35",
        orangeSharpness: "23",
        yellowSharpness: "7",
        greenSharpness: "6",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost III/Thunder Boost III",
    },
    {
        name: "Jyura Saber I",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Water",
        elementalDamage: "14",
        affinity: "-10",
        redSharpness: "20",
        orangeSharpness: "18",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Water Boost I/Brutal Strike",
    },
    {
        name: "Jyura Saber II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "20",
        orangeSharpness: "18",
        yellowSharpness: "14",
        greenSharpness: "8",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Water Boost II/Brutal Strike",
    },
    {
        name: "Jyura Reaver",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Water",
        elementalDamage: "16",
        affinity: "-10",
        redSharpness: "22",
        orangeSharpness: "21",
        yellowSharpness: "17",
        greenSharpness: "9",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Water Boost II/Brutal Strike",
    },
    {
        name: "Anteka Blade I",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "5",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "28",
        orangeSharpness: "11",
        yellowSharpness: "3",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Spiribird Doubled/Master Rider",
    },
    {
        name: "Anteka Blade II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "38",
        orangeSharpness: "5",
        yellowSharpness: "10",
        greenSharpness: "3",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Spiribird Doubled/Master Rider",
    },
    {
        name: "Antecka Rack",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "15",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "55",
        orangeSharpness: "3",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Spiribird Doubled/Master Rider",
    },
    {
        name: "Frilled Slah I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Sleep",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "27",
        yellowSharpness: "5",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Frilled Slah II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Sleep",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "14",
        yellowSharpness: "28",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Illusory Frilled Slash",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Sleep",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "30",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Sleep Boost I/Dulling Strike",
    },
    {
        name: "Drowning Shaft I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "Water",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "15",
        yellowSharpness: "13",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Drowning Shaft II",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Water",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "20",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Douser Bardiche",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Water",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "9",
        yellowSharpness: "22",
        greenSharpness: "22",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 2,
        stringRampageSkills:
            "Attack Boost III/Water Boost II/Waterblight Exploit",
    },
    {
        name: "Arzuros Naginata I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Defense Boost I/Smaill Monster Exploit",
    },
    {
        name: "Arzuros Naginata II",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "8",
        yellowSharpness: "30",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Defense Boost I/Smaill Monster Exploit",
    },
    {
        name: "Arzuros Strikequill",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "8",
        yellowSharpness: "10",
        greenSharpness: "28",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost II/Dulling Strike",
    },
    {
        name: "Wind Thief Scimitar I",
        type: "LongSword",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "70",
        elementType: "None",
        elementalDamage: 0,
        affinity: "10",
        redSharpness: "18",
        orangeSharpness: "11",
        yellowSharpness: "7",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost I/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Wind Thief Scimitar II",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "19",
        orangeSharpness: "11",
        yellowSharpness: "5",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Gale Scimitar",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "16",
        orangeSharpness: "10",
        yellowSharpness: "7",
        greenSharpness: "8",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Small Monster Exploit/Buddy Rally",
    },
    {
        name: "Dark Scythe I",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "23",
        orangeSharpness: "17",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost II/Dulling Strike",
    },
    {
        name: "Tormentor",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-10",
        redSharpness: "23",
        orangeSharpness: "18",
        yellowSharpness: "14",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost II/Defense Boost III/Dulling Strike",
    },
    {
        name: "Scythe of Menace I",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "25",
        affinity: "-10",
        redSharpness: "7",
        orangeSharpness: "8",
        yellowSharpness: "36",
        greenSharpness: "10",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Poison Boost I/Brutal Strike",
    },
    {
        name: "Scythe of Menace II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "29",
        affinity: "-10",
        redSharpness: "7",
        orangeSharpness: "9",
        yellowSharpness: "36",
        greenSharpness: "5",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Poison Boost I/Brutal Strike",
    },
    {
        name: "Big Menacing Scythe",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Poison",
        elementalDamage: "34",
        affinity: "-10",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "45",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Poison Boost II/Brutal Strike",
    },
    {
        name: "Sinister Long Sword I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "36",
        orangeSharpness: "5",
        yellowSharpness: "9",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Long Sword II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "Blast",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "37",
        orangeSharpness: "5",
        yellowSharpness: "7",
        greenSharpness: "17",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Shade Sword",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "5",
        yellowSharpness: "20",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Demon Halberd I",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "10",
        affinity: "-10",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "17",
        greenSharpness: "17",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Demon Halberd II",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "12",
        affinity: "-10",
        redSharpness: "15",
        orangeSharpness: "17",
        yellowSharpness: "20",
        greenSharpness: "23",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Azure Elder Long sword I",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "3",
        yellowSharpness: "6",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Azure Elder Long sword II",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Dragon",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "7",
        orangeSharpness: "13",
        yellowSharpness: "11",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Thunderbolt Long Sword I",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "38",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "46",
        yellowSharpness: "5",
        greenSharpness: "3",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Rookslayer Saber I\n",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "13",
        affinity: "-10",
        redSharpness: "16",
        orangeSharpness: "13",
        yellowSharpness: "16",
        greenSharpness: "20",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defesnse Boost I/Blast Boost II/Brutal Strike",
    },
    {
        name: "Rookslayer Saber II",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "18",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defesnse Boost I/Blast Boost II/Brutal Strike",
    },
    {
        name: "Icesteel Blade I",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "43",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Imperial Saber I",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Mirage Finsword I",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Cawscythe I",
        type: "LongSword",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "100",
        elementType: "Dragon",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "13",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Cawscythe II",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "140",
        elementType: "Dragon",
        elementalDamage: "21",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "17",
        yellowSharpness: "14",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost I/Dragon Exploit",
    },
    {
        name: "Cawscythe III",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "19",
        yellowSharpness: "14",
        greenSharpness: "14",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Squawkscythe",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "22",
        orangeSharpness: "20",
        yellowSharpness: "17",
        greenSharpness: "11",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Hand-Me-Down Sword I",
        type: "LongSword",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "120",
        elementType: "Fire",
        elementalDamage: "7",
        affinity: "10",
        redSharpness: "10",
        orangeSharpness: "14",
        yellowSharpness: "25",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Hand-Me-Down Sword II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Fire",
        elementalDamage: "10",
        affinity: "10",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "19",
        greenSharpness: "15",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Anti-Aerial Species/Anti-Aquatic Species",
    },
    {
        name: "Rampage Blade I",
        type: "LongSword",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "22",
        greenSharpness: "3",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Blade II",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Blade III",
        type: "LongSword",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Blade IV",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "5",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Blade V",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "20",
        yellowSharpness: "12",
        greenSharpness: "12",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Tamonowo",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "Water",
        elementalDamage: "22",
        affinity: "15",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Attack Boost II/Water Boost II",
    },
    {
        name: "Abyssal Gale Sword",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Sword",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "42",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "50",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Great Demon Halberd",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Thunder",
        elementalDamage: "15",
        affinity: "-10",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "18",
        greenSharpness: "20",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Kamura's Inheritance",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "15",
        affinity: "40",
        redSharpness: "15",
        orangeSharpness: "16",
        yellowSharpness: "14",
        greenSharpness: "17",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Anti-Aerial Species/Anti-Aquatic Species",
    },
    {
        name: "Rampage Blade S",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Bazel Varga Rookslayer",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "Blast",
        elementalDamage: "17",
        affinity: "-10",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "16",
        greenSharpness: "14",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Blast Boost III/Brutal Strike",
    },
    {
        name: "Daora's Raid",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "45",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "15",
        greenSharpness: "8",
        blueSharpness: "6",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Imperial Shimmer",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "41",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Phantom Mirage",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "10",
        phialOrShellingType: "None",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "15",
        redSharpness: "22",
        orangeSharpness: "23",
        yellowSharpness: "14",
        greenSharpness: "16",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Reddnaught Blade",
        type: "LongSword",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "39",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Redwing Long Sword I",
        type: "LongSword",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "None",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
];

export default longSwordData;