let switchAxeData = [
    {
        name: "Kamura Iron Axe I",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "50",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "20",
        yellowSharpness: "14",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Iron Axe II",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "60",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Kamura Iron Axe III",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Iron Axe IV",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "15",
        yellowSharpness: "17",
        greenSharpness: "6",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost II",
    },
    {
        name: "Kamura Iron Axe V",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "17",
        yellowSharpness: "20",
        greenSharpness: "9",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Defense Boost II/Master Rider",
    },
    {
        name: "Kamura Ninja Axe",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "21",
        yellowSharpness: "14",
        greenSharpness: "14",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost IV/Defense Boost II/Master Rider",
    },
    {
        name: "Fond Farewell I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "110",
        elementType: "Water",
        elementalDamage: "19",
        affinity: "10",
        redSharpness: "11",
        orangeSharpness: "13",
        yellowSharpness: "10",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Water Boost I",
    },
    {
        name: "Fond Farewell II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "170",
        elementType: "Water",
        elementalDamage: "19",
        affinity: "10",
        redSharpness: "20",
        orangeSharpness: "22",
        yellowSharpness: "19",
        greenSharpness: "15",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Water Boost II",
    },
    {
        name: "Parting Slice",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "Water",
        elementalDamage: "29",
        affinity: "15",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "16",
        greenSharpness: "15",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Water Boost II",
    },
    {
        name: "Rath Flamesplitter I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "120",
        elementType: "Fire",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "23",
        yellowSharpness: "7",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Rath Flamesplitter II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "140",
        elementType: "Fire",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "7",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Rath Flamesplitter III",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "190",
        elementType: "Fire",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "23",
        orangeSharpness: "28",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Element Exploit",
    },
    {
        name: "Rath Blaze Splitter",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "30",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "25",
        yellowSharpness: "6",
        greenSharpness: "22",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fire Boost I/Element Exploit",
    },
    {
        name: "Wheel Axe I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Dragon Phial\nDragon 20",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "34",
        yellowSharpness: "10",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Boost Equipped Coating/Silkbind Boost",
    },
    {
        name: "Wheel Axe II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Dragon Phial\nDragon 23",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "35",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Boost Equipped Coating/Silkbind Boost",
    },
    {
        name: "Axe of Wisdom",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Dragon Phial\nDragon 25",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "35",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Boost Equipped Coating/Silkbind Boost",
    },
    {
        name: "Delex Sail I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "100",
        elementType: "Water",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "20",
        yellowSharpness: "10",
        greenSharpness: "7",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Water Boost II/Master Rider",
    },
    {
        name: "Delex Sail II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "150",
        elementType: "Water",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "24",
        yellowSharpness: "16",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Water Boost II/Master Rider",
    },
    {
        name: "Delex Cleaver",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "Water",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "30",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Water Boost II/Master Rider",
    },
    {
        name: "Khezu Axe I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "80",
        elementType: "Thunder",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "13",
        yellowSharpness: "6",
        greenSharpness: "8",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Khezu Axe II",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "100",
        elementType: "Thunder",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "16",
        yellowSharpness: "8",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Thunderblight Exploit",
    },
    {
        name: "Khezu Cleaver",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "140",
        elementType: "Thunder",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "16",
        yellowSharpness: "14",
        greenSharpness: "10",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Thunder Boost II/Thunderblight Exploit",
    },
    {
        name: "Arzuros Axe I",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Poison Phial\nPoison 23",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "14",
        yellowSharpness: "11",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Defense Boost I/Small Monster Exploit",
    },
    {
        name: "Arzuros Axe II",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Poison Phial\nPoison 23",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "11",
        yellowSharpness: "16",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Defense Boost I/Small Monster Exploit",
    },
    {
        name: "Arzuros Revelax",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Poison Phial\nPoison 29",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "10",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost II/Small Monster Exploit",
    },
    {
        name: "Amber Slash I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "80",
        elementType: "Ice",
        elementalDamage: "19",
        affinity: "20",
        redSharpness: "10",
        orangeSharpness: "11",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Amber Slash II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "120",
        elementType: "Ice",
        elementalDamage: "23",
        affinity: "25",
        redSharpness: "10",
        orangeSharpness: "11",
        yellowSharpness: "20",
        greenSharpness: "16",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Amber Slash III",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "170",
        elementType: "Ice",
        elementalDamage: "26",
        affinity: "30",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "19",
        greenSharpness: "16",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Amber Hoarfrost",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "29",
        affinity: "30",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "19",
        greenSharpness: "24",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Affinity Boost II/Iceblight Exploit",
    },
    {
        name: "Proto Iron Axe I",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 10",
        damage: "70",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Proto Iron Axe II",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 12",
        damage: "90",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "17",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Improved Steel Axe",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 14",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "15",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Defense Boost II",
    },
    {
        name: "Elite Switch Axe I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 17",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "15",
        yellowSharpness: "11",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Silkbing Boost",
    },
    {
        name: "Elite Switch Axe II",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 18",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "11",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost III/Silkbing Boost",
    },
    {
        name: "Czar Switch Axe",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 22",
        damage: "200",
        elementType: "None",
        elementalDamage: "0",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "20",
        yellowSharpness: "18",
        greenSharpness: "10",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Silkbing Boost",
    },
    {
        name: "Limus Os I",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Water",
        elementalDamage: "17",
        affinity: "-15",
        redSharpness: "24",
        orangeSharpness: "19",
        yellowSharpness: "17",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Water Boost I/Brutal Strike",
    },
    {
        name: "Limus Os II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "210",
        elementType: "Water",
        elementalDamage: "21",
        affinity: "-15",
        redSharpness: "24",
        orangeSharpness: "24",
        yellowSharpness: "19",
        greenSharpness: "16",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Water Boost II/Brutal Strike",
    },
    {
        name: "Luto Ascia",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "230",
        elementType: "Water",
        elementalDamage: "25",
        affinity: "-15",
        redSharpness: "24",
        orangeSharpness: "24",
        yellowSharpness: "17",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Water Boost II/Brutal Strike",
    },
    {
        name: "Dragonmaiden Axe I",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "170",
        elementType: "Poison",
        elementalDamage: "19",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Dragonmaiden Axe II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "15",
        yellowSharpness: "23",
        greenSharpness: "26",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "Grior's Landmaker",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Elemental Phial",
        damage: "210",
        elementType: "Poison",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "10",
        yellowSharpness: "25",
        greenSharpness: "16",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Poison Boost I/Small Monster Exploit",
    },
    {
        name: "General's Strongaxe I",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "10",
        phialOrShellingType: "Exhaust Phial\nExhaust 25",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "19",
        yellowSharpness: "16",
        greenSharpness: "9",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost I/Boost Equipped Coating/Silkbing Boost",
    },
    {
        name: "General's Strongaxe II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "Exhaust Phial\nExhaust 28",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "11",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost II/Boost Equipped Coating/Silkbing Boost",
    },
    {
        name: "Conqueress",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "10",
        phialOrShellingType: "Exhaust Phial\nExhaust 30",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills:
            "Affinity Boost III/Boost Equipped Coating/Silkbing Boost",
    },
    {
        name: "The Shredder I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "Power Phial",
        damage: "120",
        elementType: "Thunder",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "21",
        yellowSharpness: "20",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Thunder Boost I/Master Rider",
    },
    {
        name: "The Shredder II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "10",
        phialOrShellingType: "Power Phial",
        damage: "140",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "16",
        yellowSharpness: "14",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Thunder Boost II/Master Rider",
    },
    {
        name: "The Power Shredder",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "10",
        phialOrShellingType: "Power Phial",
        damage: "170",
        elementType: "Thunder",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "19",
        yellowSharpness: "18",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Thunder Boost III/Master Rider",
    },
    {
        name: "Ash Drache I",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "5",
        phialOrShellingType: "Power Phial",
        damage: "150",
        elementType: "Dragon",
        elementalDamage: "19",
        affinity: "5",
        redSharpness: "19",
        orangeSharpness: "19",
        yellowSharpness: "16",
        greenSharpness: "11",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dragon Boost I",
    },
    {
        name: "Ash Drache II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "5",
        phialOrShellingType: "Power Phial",
        damage: "170",
        elementType: "Dragon",
        elementalDamage: "21",
        affinity: "5",
        redSharpness: "14",
        orangeSharpness: "19",
        yellowSharpness: "16",
        greenSharpness: "11",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dragon Boost I",
    },
    {
        name: "Fall Drache",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "5",
        phialOrShellingType: "Power Phial",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "22",
        affinity: "5",
        redSharpness: "14",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "15",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Dragon Boost II",
    },
    {
        name: "Almudron Axe I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "130",
        elementType: "Water",
        elementalDamage: "31",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "11",
        yellowSharpness: "24",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Water Boost I/Element Exploit",
    },
    {
        name: "Almudron Axe II",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "140",
        elementType: "Water",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "24",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost I/Element Exploit",
    },
    {
        name: "Doom Bringer Axe",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "180",
        elementType: "Water",
        elementalDamage: "42",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "30",
        greenSharpness: "13",
        blueSharpness: "9",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Water Boost II/Element Exploit",
    },
    {
        name: "Axenosom I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "100",
        elementType: "Fire",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Axenosom II",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "110",
        elementType: "Fire",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "14",
        yellowSharpness: "26",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Axenosom III",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "160",
        elementType: "Fire",
        elementalDamage: "21",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "14",
        yellowSharpness: "29",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost I/Fireblight Exploit",
    },
    {
        name: "Daybreak Silvaris",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "170",
        elementType: "Fire",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "6",
        orangeSharpness: "11",
        yellowSharpness: "29",
        greenSharpness: "15",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fire Boost II/Fireblight Exploit",
    },
    {
        name: "Assault Axe I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 9",
        damage: "120",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "30",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Brutal Strike",
    },
    {
        name: "Assault Axe II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 11",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "15",
        orangeSharpness: "14",
        yellowSharpness: "30",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost II/Brutal Strike",
    },
    {
        name: "Blitzkrieg",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Paralysis Phial\nParalysis 15",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost II/Brutal Strike",
    },
    {
        name: "Snowfall Axe I",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "80",
        elementType: "Sleep",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "23",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Sleep Boost I/Buddy Rally",
    },
    {
        name: "Snowfall Axe II",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "90",
        elementType: "Sleep",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "14",
        yellowSharpness: "11",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Sleep Boost I/Buddy Rally",
    },
    {
        name: "Snowfall Axe III",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "140",
        elementType: "Sleep",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Sleep Boost II/Buddy Rally",
    },
    {
        name: "Dewdrop Dream",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "170",
        elementType: "Sleep",
        elementalDamage: "22",
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "21",
        yellowSharpness: "20",
        greenSharpness: "14",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost III/Sleep Boost II/Buddy Rally",
    },
    {
        name: "Bone Axe I",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "80",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "20",
        yellowSharpness: "9",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Bone Axe II",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "12",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Defense Boost I",
    },
    {
        name: "Daidalos Axe",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "110",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "9",
        yellowSharpness: "14",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Defense Boost I",
    },
    {
        name: "Power Gasher I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "140",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "24",
        orangeSharpness: "16",
        yellowSharpness: "16",
        greenSharpness: "3",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Power Gasher II",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "15",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Maximal Gasher",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Affinity Boost II/Dulling Strike",
    },
    {
        name: "Flammenbeil I",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "210",
        elementType: "Fire",
        elementalDamage: "14",
        affinity: "-20",
        redSharpness: "33",
        orangeSharpness: "29",
        yellowSharpness: "9",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost I/Brutal Strike",
    },
    {
        name: "Flammenbeil II",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "220",
        elementType: "Fire",
        elementalDamage: "17",
        affinity: "-20",
        redSharpness: "30",
        orangeSharpness: "30",
        yellowSharpness: "8",
        greenSharpness: "12",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Fire Boost II/Brutal Strike",
    },
    {
        name: "Gnashing Flammenbeil",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "230",
        elementType: "Fire",
        elementalDamage: "20",
        affinity: "-20",
        redSharpness: "30",
        orangeSharpness: "30",
        yellowSharpness: "10",
        greenSharpness: "12",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Fire Boost III/Brutal Strike",
    },
    {
        name: "Rex Slasher I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Exhaust Phial\nExhaust 17",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "16",
        orangeSharpness: "8",
        yellowSharpness: "24",
        greenSharpness: "21",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost I/Brutal Strike",
    },
    {
        name: "Rex Slasher II",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Exhaust Phial\nExhaust 20",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "10",
        orangeSharpness: "10",
        yellowSharpness: "30",
        greenSharpness: "25",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Rex Gnasher",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Exhaust Phial\nExhaust 24",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-20",
        redSharpness: "14",
        orangeSharpness: "9",
        yellowSharpness: "30",
        greenSharpness: "29",
        blueSharpness: "9",
        whiteSharpness: "9",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Affinity Boost II/Brutal Strike",
    },
    {
        name: "Axe Semper Tyrannis I",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "15",
        phialOrShellingType: "Exhaust Phial\nExhaust 12",
        damage: "220",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "10",
        orangeSharpness: "38",
        yellowSharpness: "6",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Defense Boost I/Dulling Strike",
    },
    {
        name: "Axe Semper Tyrannis II",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "15",
        phialOrShellingType: "Exhaust Phial\nExhaust 14",
        damage: "230",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "11",
        orangeSharpness: "39",
        yellowSharpness: "5",
        greenSharpness: "28",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost II/Defense Boost I/Dulling Strike",
    },
    {
        name: "Grand Chaos",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "15",
        phialOrShellingType: "Exhaust Phial\nExhaust 16",
        damage: "240",
        elementType: "None",
        elementalDamage: 0,
        affinity: "-15",
        redSharpness: "12",
        orangeSharpness: "40",
        yellowSharpness: "3",
        greenSharpness: "32",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost III/Defense Boost II/Dulling Strike",
    },
    {
        name: "Venom Hatchet I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "90",
        elementType: "Poison",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "17",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Poison Boost I/Dulling Strike",
    },
    {
        name: "Venom Hatchet II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "110",
        elementType: "Poison",
        elementalDamage: "34",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "15",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Poison Boost I/Dulling Strike",
    },
    {
        name: "Mortal Serpent",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "140",
        elementType: "Poison",
        elementalDamage: "40",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "15",
        yellowSharpness: "14",
        greenSharpness: "16",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost IV/Poison Boost I/Coating Switch Boost",
    },
    {
        name: "Hidden Axe I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Poison Phial\nPoison 12",
        damage: "100",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "10",
        orangeSharpness: "16",
        yellowSharpness: "19",
        greenSharpness: "24",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost I/Boost Equipped Coating",
    },
    {
        name: "Hidden Axe II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Poison Phial\nPoison 15",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "10",
        orangeSharpness: "16",
        yellowSharpness: "19",
        greenSharpness: "24",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost I/Boost Equipped Coating",
    },
    {
        name: "Night's Crescent",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Poison Phial\nPoison 17",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "40",
        redSharpness: "10",
        orangeSharpness: "16",
        yellowSharpness: "24",
        greenSharpness: "25",
        blueSharpness: "14",
        whiteSharpness: "9",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost II/Boost Equipped Coating",
    },
    {
        name: "Binding Roller I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "110",
        elementType: "Paralysis",
        elementalDamage: "10",
        affinity: "0",
        redSharpness: "33",
        orangeSharpness: "9",
        yellowSharpness: "9",
        greenSharpness: "6",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Dulling Strike",
    },
    {
        name: "Binding Roller II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "130",
        elementType: "Paralysis",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "37",
        orangeSharpness: "8",
        yellowSharpness: "10",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Dulling Strike",
    },
    {
        name: "Binding Roller III",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "180",
        elementType: "Paralysis",
        elementalDamage: "13",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "10",
        yellowSharpness: "10",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Defense Boost I/Dulling Strike",
    },
    {
        name: "Vermilingua",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "200",
        elementType: "Paralysis",
        elementalDamage: "16",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "21",
        yellowSharpness: "14",
        greenSharpness: "14",
        blueSharpness: "11",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Defense Boost II/Dulling Strike",
    },
    {
        name: "Ludroth Axe I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "90",
        elementType: "Water",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "9",
        orangeSharpness: "16",
        yellowSharpness: "11",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Ludroth Axe II",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "100",
        elementType: "Water",
        elementalDamage: "26",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "19",
        yellowSharpness: "15",
        greenSharpness: "11",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Water Boost I/Waterblight Exploit",
    },
    {
        name: "Splish Splax",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "160",
        elementType: "Water",
        elementalDamage: "33",
        affinity: "0",
        redSharpness: "11",
        orangeSharpness: "17",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 1,
        stringRampageSkills: "Attack Boost /Water Boost II/Waterblight Exploit",
    },
    {
        name: "Usurper's Downpour I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "110",
        elementType: "Thunder",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "9",
        yellowSharpness: "22",
        greenSharpness: "12",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Thunder Boost I/Anti-aquatic Species",
    },
    {
        name: "Usurper's Downpour II",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "10",
        yellowSharpness: "38",
        greenSharpness: "13",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost I/Anti-aquatic Species",
    },
    {
        name: "Despot's Cloudburst",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "200",
        elementType: "Thunder",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "9",
        yellowSharpness: "29",
        greenSharpness: "19",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Thunder Boost II/Anti-aquatic Species",
    },
    {
        name: "Longear Axe I",
        type: "SwitchAxe",
        rarity: "1",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "90",
        elementType: "Ice",
        elementalDamage: "12",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "14",
        yellowSharpness: "11",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost I/Ice Boost I/Small Monster Exploit",
    },
    {
        name: "Longear Axe II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "130",
        elementType: "Ice",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "16",
        orangeSharpness: "11",
        yellowSharpness: "20",
        greenSharpness: "9",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Ice Boost II/Small Monster Exploit",
    },
    {
        name: "Longear Axe III",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "160",
        elementType: "Ice",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "13",
        orangeSharpness: "7",
        yellowSharpness: "24",
        greenSharpness: "24",
        blueSharpness: "2",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Ice Boost II/Small Monster Exploit",
    },
    {
        name: "Longear Weiss",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "8",
        orangeSharpness: "7",
        yellowSharpness: "24",
        greenSharpness: "24",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Ice Boost II/Coating Switch Boost",
    },
    {
        name: "Sinister Axe I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "130",
        elementType: "Blast",
        elementalDamage: "17",
        affinity: "0",
        redSharpness: "37",
        orangeSharpness: "4",
        yellowSharpness: "9",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Axe II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "140",
        elementType: "Blast",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "40",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost I/Magnamalo Soul",
    },
    {
        name: "Sinister Shadowslice",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "45",
        orangeSharpness: "2",
        yellowSharpness: "4",
        greenSharpness: "21",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Blast Boost II/Magnamalo Soul",
    },
    {
        name: "Undying Axe I",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "16",
        affinity: "10",
        redSharpness: "11",
        orangeSharpness: "4",
        yellowSharpness: "24",
        greenSharpness: "20",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Undying Axe II",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "210",
        elementType: "Thunder",
        elementalDamage: "20",
        affinity: "15",
        redSharpness: "11",
        orangeSharpness: "11",
        yellowSharpness: "24",
        greenSharpness: "25",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Affinity Boost I/Thunder Boost I/Dulling Strike",
    },
    {
        name: "Azure Elder Axe I",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "9",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "9",
        blueSharpness: "23",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Dragon Boost III/Anti-Aerial Species/Defense Boost I",
    },
    {
        name: "Azure Elder Axe II",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "200",
        elementType: "Dragon",
        elementalDamage: "11",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "11",
        greenSharpness: "11",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost III/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Thunderbolt Axe I",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "180",
        elementType: "Thunder",
        elementalDamage: "35",
        affinity: "0",
        redSharpness: "4",
        orangeSharpness: "4",
        yellowSharpness: "45",
        greenSharpness: "10",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Rookslayer Axe I",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "200",
        elementType: "Blast",
        elementalDamage: "13",
        affinity: "-15",
        redSharpness: "11",
        orangeSharpness: "13",
        yellowSharpness: "17",
        greenSharpness: "14",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Brutal Strike",
    },
    {
        name: "Rookslayer Axe II",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "210",
        elementType: "Blast",
        elementalDamage: "15",
        affinity: "-15",
        redSharpness: "20",
        orangeSharpness: "22",
        yellowSharpness: "19",
        greenSharpness: "15",
        blueSharpness: "6",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost I/Blast Boost II/Brutal Strike",
    },
    {
        name: "Bazelrush Rookslayer",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "220",
        elementType: "Blast",
        elementalDamage: "17",
        affinity: "-15",
        redSharpness: "22",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Defense Boost II/Blast Boost II/Brutal Strike",
    },
    {
        name: "Daora's Farasa I",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "Ice",
        elementalDamage: "39",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "12",
        blueSharpness: "10",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Kushala Daora Soul",
    },
    {
        name: "Teostra's Arx I",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Blast",
        elementalDamage: "31",
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "22",
        yellowSharpness: "20",
        greenSharpness: "15",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Waxglare Wand I",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "Poison",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "19",
        orangeSharpness: "7",
        yellowSharpness: "20",
        greenSharpness: "22",
        blueSharpness: "17",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Defense Boost II/Chameleos Soul",
    },
    {
        name: "Origami Axe I",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Dragon Phial\nDragon 13",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "20",
        orangeSharpness: "16",
        yellowSharpness: "10",
        greenSharpness: "6",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Coating Switch Boost",
    },
    {
        name: "Origami Axe II",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Dragon Phial\nDragon 13",
        damage: "160",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "25",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "6",
        blueSharpness: "4",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Coating Switch Boost",
    },
    {
        name: "Petal Cloud",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Dragon Phial\nDragon 17",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "29",
        orangeSharpness: "21",
        yellowSharpness: "16",
        greenSharpness: "6",
        blueSharpness: "4",
        whiteSharpness: "4",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost IV/Coating Switch Boost",
    },
    {
        name: "Grim Cat I",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "140",
        elementType: "Paralysis",
        elementalDamage: "23",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "19",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost I/Paralysis Boost I",
    },
    {
        name: "Grim Cat II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "170",
        elementType: "Paralysis",
        elementalDamage: "25",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "27",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost I/Affinity Boost II/Paralysis Boost I",
    },
    {
        name: "Grimmige Katze",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "Paralysis",
        elementalDamage: "27",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "22",
        greenSharpness: "27",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost II/Affinity Boost II/Paralysis Boost I",
    },
    {
        name: "Infernal Axe I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "100",
        elementType: "Dragon",
        elementalDamage: "18",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "7",
        yellowSharpness: "7",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dragon Boost I/Dragon Exploit",
    },
    {
        name: "Infernal Axe II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "140",
        elementType: "Dragon",
        elementalDamage: "20",
        affinity: "0",
        redSharpness: "35",
        orangeSharpness: "5",
        yellowSharpness: "5",
        greenSharpness: "15",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost II/Dragon Boost I/Dragon Exploit",
    },
    {
        name: "Hellish Edge",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Dragon",
        elementalDamage: "24",
        affinity: "0",
        redSharpness: "37",
        orangeSharpness: "4",
        yellowSharpness: "4",
        greenSharpness: "30",
        blueSharpness: "5",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 2,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost IV/Dragon Boost II/Dragon Exploit",
    },
    {
        name: "Sleepy Shellslice I",
        type: "SwitchAxe",
        rarity: "2",
        defenseIncrease: "15",
        phialOrShellingType: "Power Phial",
        damage: "90",
        elementType: "Sleep",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost I/Sleep Boost I/Anti-Aquatic Species",
    },
    {
        name: "Sleepy Shellslice II",
        type: "SwitchAxe",
        rarity: "3",
        defenseIncrease: "15",
        phialOrShellingType: "Power Phial",
        damage: "120",
        elementType: "Sleep",
        elementalDamage: "15",
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "20",
        yellowSharpness: "20",
        greenSharpness: "5",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost II/Sleep Boost I/Anti-Aquatic Species",
    },
    {
        name: "Schale Batis",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "20",
        phialOrShellingType: "Power Phial",
        damage: "170",
        elementType: "Sleep",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "20",
        yellowSharpness: "25",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Defense Boost III/Sleep Boost II/Anti-Aquatic Species",
    },
    {
        name: "Rampage Slicer I",
        type: "SwitchAxe",
        rarity: "4",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "150",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "4",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Slicer II",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "170",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "16",
        yellowSharpness: "20",
        greenSharpness: "10",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Slicer III",
        type: "SwitchAxe",
        rarity: "5",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "180",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "20",
        greenSharpness: "6",
        blueSharpness: "3",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Slicer IV",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "190",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "15",
        greenSharpness: "7",
        blueSharpness: "7",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Rampage Slicer V",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "200",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "12",
        orangeSharpness: "18",
        yellowSharpness: "12",
        greenSharpness: "13",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
    {
        name: "Redwing Switch Axe I",
        type: "SwitchAxe",
        rarity: "6",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "160",
        elementType: "Dragon",
        elementalDamage: "32",
        affinity: "0",
        redSharpness: "30",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "15",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Abyssal Gale Axe",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "210",
        elementType: "Dragon",
        elementalDamage: "14",
        affinity: "0",
        redSharpness: "5",
        orangeSharpness: "5",
        yellowSharpness: "18",
        greenSharpness: "12",
        blueSharpness: "25",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Dragon Boost IV/Anti-Aerial Species/Ibushi Soul",
    },
    {
        name: "Abyssal Storm Axe",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "190",
        elementType: "Thunder",
        elementalDamage: "43",
        affinity: "0",
        redSharpness: "2",
        orangeSharpness: "3",
        yellowSharpness: "50",
        greenSharpness: "8",
        blueSharpness: "12",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Anti-Aerial Species/Narwa Soul",
    },
    {
        name: "Balor's Mirage",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "190",
        elementType: "Poison",
        elementalDamage: "28",
        affinity: "0",
        redSharpness: "14",
        orangeSharpness: "8",
        yellowSharpness: "22",
        greenSharpness: "20",
        blueSharpness: "18",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 1,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Defense Boost III/Chameleos Soul",
    },
    {
        name: "Daora's Janah",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "190",
        elementType: "Ice",
        elementalDamage: "41",
        affinity: "0",
        redSharpness: "17",
        orangeSharpness: "15",
        yellowSharpness: "17",
        greenSharpness: "9",
        blueSharpness: "7",
        whiteSharpness: "2",
        purpleSharpness: 0,
        decoSlot1Lvl: 1,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Attack Boost III/Affinity Boost III/Kushala Daora Soul",
    },
    {
        name: "Undying Light",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "220",
        elementType: "Thunder",
        elementalDamage: "22",
        affinity: "15",
        redSharpness: "14",
        orangeSharpness: "14",
        yellowSharpness: "18",
        greenSharpness: "22",
        blueSharpness: "0",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 3,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills:
            "Affinity Boost II/Thunder Boost II/Dulling Strike",
    },
    {
        name: "Teostra's Castle",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "210",
        elementType: "Blast",
        elementalDamage: "36",
        affinity: "0",
        redSharpness: "18",
        orangeSharpness: "18",
        yellowSharpness: "12",
        greenSharpness: "10",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Fireblight Exploit/Teostra Soul",
    },
    {
        name: "Reddnaught Dunat",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Element Phial",
        damage: "180",
        elementType: "Dragon",
        elementalDamage: "37",
        affinity: "0",
        redSharpness: "15",
        orangeSharpness: "0",
        yellowSharpness: "0",
        greenSharpness: "0",
        blueSharpness: "0",
        whiteSharpness: "20",
        purpleSharpness: 0,
        decoSlot1Lvl: 2,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Attack Boost III/Wyvern Exploit/Valstrax Soul",
    },
    {
        name: "Rampage Slicer S",
        type: "SwitchAxe",
        rarity: "7",
        defenseIncrease: "0",
        phialOrShellingType: "Power Phial",
        damage: "210",
        elementType: "None",
        elementalDamage: 0,
        affinity: "0",
        redSharpness: "10",
        orangeSharpness: "15",
        yellowSharpness: "7",
        greenSharpness: "15",
        blueSharpness: "8",
        whiteSharpness: "0",
        purpleSharpness: 0,
        decoSlot1Lvl: 0,
        decoSlot2Lvl: 0,
        decoSlot3Lvl: 0,
        stringRampageSkills: "Any",
    },
];

export default switchAxeData